Repository vegaprotocol/vega, pull requests merged in 2022-07, with the labels that each got.

#5531 ci: Update smoke test in Jenkinsfile
  Jenkinsfile
Labels: no-changelog

#5532 fix: register processor conf update on startup success
  protocol/protocol.go
Labels: no-changelog

#5545 fix: reward.staking.delegation.competitionLevel can be 1.0
  netparams/defaults.go
Labels: no-changelog

#5534 fix: do not accept tx with unexpected pubkeys.
  CHANGELOG.md
  assets/asset.go
  execution/engine.go
  execution/mocks/oracle_engine_mock.go
  oracles/engine.go
  oracles/engine_subscribers.go
  oracles/engine_test.go
  oracles/oracle_spec.go
  processor/abci.go
  processor/mocks/checkpoint_mock.go
  processor/mocks/limits_mock.go
  processor/mocks/oracles_engine_mock.go
  processor/processor.go
  products/mocks/oracle_engine_mock.go
  products/products.go
  types/market_test.go
Labels: maybe bug

#5553 feat: update the project board GH actions
  .github/workflows/conventional_commits.yml
  .github/workflows/project_manage.yml
  .github/workflows/project_management.yml
Labels: no-changelog, no-issue

#5558 feat: build docker image for vegawallet
  .github/workflows/build-vegawallet-docker-image.yml
  docker/vegawallet.dockerfile
Labels: no-changelog, no-issue

#5564 feat: upload binaries when release already exists in vega
  Jenkinsfile
Labels: no-changelog, no-issue

#5569 feat: add lifetime_limit and withdaw_threshold to genesis assets
  assets/genesis_state.go
  cmd/vega/verify/genesis.go
Labels: no-changelog

#5566 fix: reopen and close a correctly closed issue bug
  .github/workflows/project_management.yml
Labels: no-changelog

#5576 fix: do not put merged PRs into `in progress`
  .github/workflows/project_management.yml
Labels: no-changelog

#5575 feat: test slippage calculation used in margin level calculation
  integration/features/verified/Slippage-Calc-in-Margin-Level.feature
Labels: feature tests, no-changelog, no-issue

#5557 fix: call unsubscribe at mkt settlement
  CHANGELOG.md
  execution/engine.go
  execution/market.go
  execution/mocks/oracle_engine_mock.go
  liquidity/mocks/mocks.go
  markets/instrument.go
  oracles/engine.go
  oracles/engine_subscribers.go
  oracles/engine_test.go
  products/future.go
  products/future_test.go
  products/mocks/oracle_engine_mock.go
  products/products.go
  products/products_test.go
  settlement/engine.go
  settlement/mocks/settlement_product_mock.go
Labels: bug

#5559 chore: update ethereum library (dependabot security alert)
  contracts/erc20/erc20.go
  contracts/erc20_bridge_logic_restricted/erc20_bridge_logic_restricted.go
  contracts/multisig_control/multisig_control.go
  go.mod
  go.sum
Labels: no-changelog, no-issue

#5580 fix: add locks on subscribers add and remove
  oracles/engine.go
  oracles/engine_subscribers.go
Labels: no-changelog

#5590 fix: panic in banking when restoring an AssetList from snapshot
  banking/snapshot_test.go
  types/snapshot_nodes.go
Labels: no-changelog, no-issue

#5594 feat: 0032-PRIM-price_monitoring
  integration/features/verified/0032-PRIM-price_monitoring_lognormal.feature
Labels: no-changelog, no-issue

#5597 chore(jenkins): remove deprecated vegawallet repo from pipeline
  Jenkinsfile
Labels: no-changelog, no-issue

#5599 ci: add develop release action
  Jenkinsfile
Labels: no-changelog, no-issue

#5595 chore: cleanup with version, remove tendermint version checker, share…
  assets/snapshot_test.go
  banking/snapshot_test.go
  cmd/vega/main.go
  cmd/vega/node.go
  cmd/vega/node/node.go
  cmd/vega/version.go
  cmd/vegawallet/commands/root.go
  collateral/snapshot_test.go
  delegation/engine_test.go
  evtforward/forwarder_test.go
  execution/market_activity_tracker_test.go
  execution/snapshot_test.go
  monitoring/status.go
  monitoring/version.go
  monitoring/version_test.go
  pow/snapshot_test.go
  stats/stats.go
  version/version.go
  wallet/proxy/proxy.go
  wallet/service/service.go
  wallet/version/version.go
Labels: no-changelog, no-issue

#5593 fix: don't skip check when review is dismissed
  .github/workflows/project_management.yml
Labels: no-changelog, no-issue

#5612 chore: update tendermint version
  go.mod
  go.sum
Labels: no-changelog, no-issue

#5596 feat: question line 44
  integration/features/verified/0032-PRIM-price_monitoring_lognormal.feature
Labels: no-changelog, no-issue

#5603 chore: remove unused plugins
  plugins/assets.go
  plugins/deposits.go
  plugins/deposits_test.go
  plugins/notary.go
  plugins/withdrawals.go
  plugins/withdrawals_test.go
  protocol/all_services.go
Labels: no-changelog, no-issue

#5607 chore: remove monitoring package
  api/core.go
  api/grpc.go
  cmd/vega/node/node.go
  config/config.go
  monitoring/config.go
  monitoring/mocks/blockchain_client_mock.go
  monitoring/status.go
  monitoring/status_test.go
Labels: no-changelog, no-issue

#5630 chore: update protos
  collateral/engine_test.go
  go.mod
  go.sum
  types/collateral.go
Labels: no-changelog, no-issue

#5628 chore: remove unused script
  script/build-multiarch-no-cgo.sh
  script/fix_imports.sh
Labels: no-changelog, no-issue

#5604 refactor: ignore stale trigger when in auction
  CHANGELOG.md
  execution/market.go
  execution/market_snapshot.go
  integration/features/auctions/3528-indefinite-auction-extension.feature
  integration/features/price_monitoring/price-monitoring-for-system-test.feature
  integration/features/price_monitoring/price-monitoring-lognormal-decimals.feature
  integration/features/price_monitoring/price-monitoring-lognormal.feature
  integration/features/price_monitoring/price-monitoring-simple.feature
  integration/features/verified/0026-AUCT-auction_interaction.feature
  integration/features/verified/0032-PRIM-price_monitoring_lognormal.feature
  monitor/price/pricemonitoring.go
  monitor/price/pricemonitoring_test.go
  monitor/price/snapshot.go
  monitor/price/snapshot_test.go
Labels: no-issue

#5634 feat: add AC check the existence of position record 0006-POSI-027
  integration/features/verified/0003-MTMK-mark_to_market_settlement.feature
Labels: no-changelog, no-issue

#5635 feat: use block hash as tx hash for events that are sent at begin/end…
  libs/context/context.go
Labels: no-changelog, no-issue

#5414 Add UpdateAsset proposal
  assets/asset.go
  assets/assets.go
  assets/assets_test.go
  assets/erc20/erc20.go
  assets/erc20/erc20_test.go
  assets/erc20/mocks/eth_client_mock.go
  assets/snapshot.go
  assets/snapshot_test.go
  banking/asset_action.go
  banking/engine.go
  banking/erc20.go
  banking/mocks/assets_mock.go
  banking/mocks/collateral_mock.go
  banking/snapshot.go
  bridges/erc20_logic.go
  collateral/engine.go
  collateral/snapshot.go
  collateral/snapshot_test.go
  events/asset_test.go
  events/governance_proposal_test.go
  evtforward/ethereum/filterer.go
  execution/engine.go
  governance/asset.go
  governance/engine.go
  governance/netparams.go
  governance/node_validation.go
  governance/proposal.go
  integration/stubs/assets.go
  netparams/defaults.go
  netparams/keys.go
  processor/abci.go
  processor/process_chain_event.go
  processor/processor.go
  types/asset.go
  types/chain_events.go
  types/governance_new_asset.go
  types/governance_proposal.go
  types/governance_update_asset.go
  types/nodes.go
  types/snapshot_nodes.go
Labels: no-changelog

#5637 fix: update corrected AC/Spec code
  integration/features/verified/liquidity-provision-bond-account.feature
Labels: no-changelog, no-issue

#5654 chore: move around some libraries
  core/admin/nodewallets.go
  core/assets/erc20/erc20_test.go
  core/nodewallets/eth/clef/wallet.go
  core/nodewallets/eth/keystore/wallet.go
  core/nodewallets/eth/wallet.go
  core/nodewallets/vega/loader.go
  core/nodewallets/vega/wallet.go
  core/oracles/adaptors/adaptors.go
  core/oracles/adaptors/adaptors_test.go
  core/oracles/adaptors/json.go
  core/oracles/adaptors/json_test.go
  core/oracles/adaptors/openoracle.go
  core/oracles/adaptors/openoracle_test.go
  core/processor/abci.go
  core/processor/mocks/oracle_adaptors_mock.go
  core/processor/mocks/witness_mock.go
  core/processor/processor.go
  core/types/banking.go
  core/validators/mocks/wallet_mock.go
  core/validators/topology.go
  core/validators/topology_test.go
  core/validators/witness.go
  core/validators/witness_test.go
  libs/crypto/public_key.go
Labels: no-changelog, no-issue

#5664 ci: optimise pipeline by building docker images during system-tests
  Jenkinsfile
Labels: no-changelog, no-issue
