Repository vegaprotocol/vega, pull requests merged in 2022-09, with the labels that each got.

#6028 chore: added unit tests and a fix for 5972
  CHANGELOG.md
  core/execution/market_test.go
  core/governance/engine.go
  core/governance/engine_test.go
  core/governance/engine_update_market_test.go
Labels: no-changelog

#6030 Attempt to fix a flickering test
  core/broker/broker.go
  core/broker/broker_test.go
Labels: no-changelog

#5965 feat: scenarios for AC 0042-LIQF-001 added
  core/integration/features/verified/0042-LIQF-fees_rewards_VirtualStake.feature
Labels: no-changelog, no-issue

#6035 fix: add missing conversion
  datanode/broker/convert.go
Labels: no-changelog, no-issue

#6043 ci: support running PRs with forks (#1500)
  .github/workflows/project_management.yml
  Jenkinsfile
Labels: no-changelog, no-issue

#6045 Ensuring restricted key in wallet permissions now checks against all keys
  wallet/wallet/hd_wallet.go
  wallet/wallet/hd_wallet_test.go
Labels: no-changelog, no-issue

#6051 ci: disable unit tests for release binaries pipeline
  .github/workflows/release-binaries.yml
Labels: no-changelog, no-issue

#6052 draft: experiment with using github actions for linting
  .github/workflows/golangci-lint.yml
  Jenkinsfile
Labels: no-changelog, no-issue

#6047 feat: test probability of trading refactoring
  core/integration/features/verified/Issue-6004-ProbOfTrading_Refactoring.feature
Labels: feature tests, no-changelog

#6053 Cleanup waiter implementation
  core/broker/broker_test.go
Labels: no-changelog, no-issue

#6068 fix: add validation to prevent invalid one off transfers
  commands/transfer_funds.go
  commands/transfer_funds_test.go
Labels: no-changelog

#6070 chore: added logging for unsubscribing of oracles and a unit test for #6056
  core/execution/market_test.go
  core/products/future.go
Labels: no-changelog, no-issue

#6074 ci: add visor to standard release binaries
  .github/workflows/release-binaries.yml
Labels: no-changelog, no-issue

#6058 feat: add protocol_upgrade_event convertion
  datanode/broker/convert.go
Labels: no-changelog, no-issue

#6084 Add permissions management on wallet admin API
  cmd/vegawallet/commands/permissions_describe.go
  cmd/vegawallet/commands/permissions_describe_test.go
  cmd/vegawallet/commands/permissions_list.go
  cmd/vegawallet/commands/permissions_purge.go
  cmd/vegawallet/commands/permissions_purge_test.go
  cmd/vegawallet/commands/permissions_revoke.go
  cmd/vegawallet/commands/permissions_revoke_test.go
  wallet/api/admin_describe_permissions.go
  wallet/api/admin_describe_permissions_test.go
  wallet/api/admin_list_permissions.go
  wallet/api/admin_list_permissions_test.go
  wallet/api/admin_purge_permissions.go
  wallet/api/admin_purge_permissions_test.go
  wallet/api/admin_revoke_permissions.go
  wallet/api/admin_revoke_permissions_test.go
  wallet/api/admin_update_permissions.go
  wallet/api/admin_update_permissions_test.go
  wallet/api/api.go
  wallet/api/openrpc.json
  wallet/wallet/handler.go
  wallet/wallet/handler_test.go
  wallet/wallet/hd_wallet.go
  wallet/wallet/hd_wallet_test.go
Labels: wallet, no-changelog, no-issue

#6082 feat: implements unmarshaller for order type
  datanode/gateway/graphql/marshallers/marshallers.go
  protos/sources/buf.lock
Labels: no-changelog, no-issue

#6076 feature test to cover risk parameters used margin calculation 0019-MCAL
  core/integration/features/verified/0019-MCAL-margin_calculator-risk_parameters.feature
Labels: feature tests, no-changelog, no-issue

#6091 fix: remove block time from event hashing
  core/banking/erc20.go
  core/types/staking.go
Labels: no-changelog, no-issue

#6042 fix: set gql complexity limit
  CHANGELOG.md
  datanode/README.md
  datanode/gateway/graphql/server.go
Labels: improvement, performance, bug, security

#6100 ci: add step to publish to vega-dev-releases
  Jenkinsfile
Labels: no-changelog, no-issue

#6093 5600 port wallet networks
  cmd/vegawallet/commands/network_delete.go
  cmd/vegawallet/commands/network_delete_test.go
  cmd/vegawallet/commands/network_describe.go
  cmd/vegawallet/commands/network_describe_test.go
  cmd/vegawallet/commands/network_import.go
  cmd/vegawallet/commands/network_import_test.go
  cmd/vegawallet/commands/network_list.go
  wallet/api/admin_describe_network.go
  wallet/api/admin_describe_network_test.go
  wallet/api/admin_import_network.go
  wallet/api/admin_import_network_test.go
  wallet/api/admin_list_networks.go
  wallet/api/admin_list_networks_test.go
  wallet/api/admin_remove_network.go
  wallet/api/admin_remove_network_test.go
  wallet/api/api.go
  wallet/api/errors.go
  wallet/api/openrpc.json
  wallet/network/handler.go
  wallet/network/handler_test.go
  wallet/network/mocks/store_mock.go
  wallet/network/network.go
Labels: no-changelog, no-issue

#6120 Reorder liquidity checks
  CHANGELOG.md
  core/execution/engine.go
Labels: bug

#6092 chore: add some new polling settings for ethereum
  cmd/vega/node/node.go
  core/client/eth/config.go
  core/client/eth/ethereum_confirmations.go
  core/client/eth/ethereum_confirmations_test.go
  core/evtforward/config.go
  core/evtforward/engine.go
  core/evtforward/ethereum/config.go
  core/evtforward/ethereum/engine.go
  core/evtforward/ethereum/filterer.go
Labels: no-changelog, no-issue

#6146 feat: add version command to visor
  CHANGELOG.md
  cmd/visor/version.go
Labels: no-issue

#6143 chore: some fixes / style in execution market
  core/execution/auction.go
  core/execution/engine.go
  core/execution/engine_snapshot.go
  core/execution/equity_shares.go
  core/execution/equity_shares_snapshot.go
  core/execution/liquidity_provision_test.go
  core/execution/market.go
  core/execution/market_snapshot.go
  core/execution/market_test.go
  core/execution/reference_price_moves.go
  core/execution/special_orders.go
  core/matching/orderbook.go
Labels: no-changelog, no-issue

#6151 chore: set version 0.56.0+dev
  version/version.go
Labels: no-changelog, no-issue

#6161 fix: handle snapshot errors during statesync when unable to clear and…
  core/snapshot/engine.go
Labels: no-changelog, no-issue

#6152 fix: double undelegateNow bug fixed
  core/delegation/engine.go
  core/delegation/engine_test.go
Labels: no-changelog, no-issue

#6174 fix: swap the order of distribution of the reward and emitting the re…
  core/rewards/engine.go
Labels: no-changelog

#6179 fix: ensure updated asset remains as STATUS_ENABLED
  core/assets/assets.go
Labels: no-changelog, no-issue

#6182 fix: nil reference in missing initialisation of keyRotationService in…
  datanode/api/server.go
Labels: no-changelog

#6104 refactor: extend uncross test with amendment scenario
  CHANGELOG.md
  core/integration/features/auctions/opening-auction-uncross.feature
Labels: feature tests

#6195 fix: have to start nullchain client after server has started
  cmd/vega/node/node.go
Labels: no-changelog, no-issue

#6200 Tidy-up: remove `err` from `GetRiskFactors()` return signature
  core/execution/market.go
  core/execution/market_snapshot.go
  core/risk/engine.go
Labels: no-changelog, no-issue

#6204 fix: Data Node add Ethereum Key Rotations subscriber and rest binding
  CHANGELOG.md
  cmd/data-node/commands/start/node_pre.go
  go.mod
  go.sum
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: no-issue

#6208 chore: update comments
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/schema.graphql
  protos/sources/vega/governance.proto
  protos/sources/vega/markets.proto
  protos/vega/governance.pb.go
  protos/vega/markets.pb.go
Labels: no-changelog, no-issue

#6213 fix: map v1 interval to v2 interval string when handling candle request
  datanode/gateway/graphql/connection_handlers.go
Labels: DatanodeV2, no-changelog, no-issue

#6205 feat: cleanup Jenkinsfile from s3 publish step
  Jenkinsfile
Labels: no-changelog, no-issue

#6177 Add {Begin|End}Block and ProtocolUpgradeStarted events
  core/events/begin_block.go
  core/events/bus.go
  core/events/end_block.go
  core/events/protocol_upgrade_started.go
  core/processor/abci.go
  datanode/broker/convert.go
  protos/sources/vega/events/v1/events.proto
  protos/vega/events/v1/events.pb.go
Labels: no-changelog, no-issue

#6219 fix: non deterministic unit test for listing valid params
  wallet/api/session_list_keys.go
  wallet/api/session_list_keys_test.go
Labels: no-changelog, no-issue

#6218 fix: prevent empty tendermint events
  core/blockchain/abci/abci.go
  go.mod
  go.sum
Labels: no-changelog, no-issue

#6224 feat: enforce skip timeout on commit in tm config
  core/blockchain/abci/tm_node.go
Labels: no-changelog, no-issue

#6223 fix: typo in transfers snapshot
  .vscode/launch.json
  core/types/snapshot_nodes.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog, no-issue

#6199 Snapshot fixes
  core/execution/market_snapshot.go
  core/types/snapshot_nodes.go
Labels: no-changelog, no-issue

#6034 feat: LIQF-fees in growing market feature tests
  core/execution/equity_shares.go
  core/execution/market.go
  core/integration/features/verified/0042-LIQF-fees_rewards_growing_market.feature
Labels: feature tests, no-changelog, no-issue

#6246 fix: error if signature is invalid
  commands/transaction.go
  commands/transaction_test.go
  core/blockchain/client.go
Labels: no-changelog, no-issue

#6249 fix: send ledger movement when loading checkpoint
  core/banking/engine.go
  core/banking/oneoff_transfers.go
  core/banking/recurring_transfers.go
  core/collateral/checkpoint.go
  core/collateral/checkpoint_test.go
  core/collateral/engine.go
  core/events/ledger_movements.go
  core/events/ledger_movements_test.go
  core/execution/bond_topup.go
  core/execution/collateral.go
  core/execution/liquidity_provision.go
  core/execution/market.go
  core/rewards/engine.go
  core/types/transfer.go
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#6252 feat: Add wallet API to the docs release (#6167)
  .github/workflows/release-docs.yml
Labels: no-changelog

#6250 feat: add feature test and AC for position resolution
  core/integration/features/verified/Funding-insurance_pool.feature
Labels: feature tests, no-changelog, no-issue

#6257 Add `admin.update_network` endpoint on wallet API v2
  cmd/vegawallet/commands/network_describe.go
  cmd/vegawallet/commands/service_run.go
  libs/encoding/encoding.go
  wallet/api/admin_describe_network.go
  wallet/api/admin_describe_network_test.go
  wallet/api/admin_update_network.go
  wallet/api/admin_update_network_test.go
  wallet/api/api.go
  wallet/api/errors.go
  wallet/network/network.go
Labels: wallet, no-changelog, no-issue

#6226 feat: close out using log-normal model
  core/integration/features/verified/closeout-lognormal.feature
Labels: feature tests, no-changelog, no-issue

#6268 fix: trim version prefix in protocol upgrade
  core/protocolupgrade/engine.go
Labels: no-changelog, no-issue

#6162 feat: change position subscribtion to return a flattened position update type
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog, no-issue

#6270 fix: fix typo in list parties grpc
  datanode/api/trading_data_v2.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/resolvers_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog

#6272 chore: Tidy up golangci-lint file
  .golangci.toml
Labels: no-changelog, no-issue

#6276 Add missing `admin.update_network` endpoint wallet API v2
  version/version.go
  wallet/api/openrpc.json
Labels: no-changelog, no-issue

#6302 chore: update to ongoing version 0.57.0+dev
  version/version.go
Labels: no-changelog, no-issue

#6328 fix: use offset 0 to set postgres timezone
  datanode/snapshot/compression.go
  datanode/snapshot/service_create_snapshot.go
  datanode/snapshot/service_load_snapshot.go
  datanode/snapshot/service_test.go
Labels: no-changelog, no-issue

#6334 feat: add a simple rate limiter for graphql
  datanode/gateway/config.go
  datanode/gateway/graphql/server.go
  datanode/gateway/middleware.go
Labels: no-changelog, no-issue

#6333 6327 checkpoints delegations to history
  cmd/data-node/commands/start/node_pre.go
  datanode/entities/checkpoint.go
  datanode/entities/delegation.go
  datanode/snapshot/orders/update_current_orders_test.go
  datanode/snapshot/service_test.go
  datanode/sqlstore/checkpoints.go
  datanode/sqlstore/checkpoints_test.go
  datanode/sqlstore/delegations.go
  datanode/sqlstore/delegations_test.go
  datanode/sqlstore/migrations/0001_initial.sql
  datanode/sqlstore/node_test.go
  datanode/sqlstore/sqlstore.go
  datanode/sqlstore/sqlstore_test.go
  datanode/sqlsubscribers/checkpoint.go
  datanode/sqlsubscribers/delegations.go
  datanode/utils/databasetest/setup.go
Labels: no-changelog

#6336 fix: openrpc
  wallet/api/openrpc.json
Labels: wallet, no-changelog, no-issue

#6351 feat: Validate batch market instructions submitted to the wallet
  wallet/commands/commands.go
Labels: no-changelog, no-issue

#6350 fix: openrpc
  wallet/api/admin_sign_message.go
  wallet/api/openrpc.json
Labels: wallet, no-changelog, no-issue

#6346 chore: remove things we no longer snapshot from protos
  core/snapshot/engine.go
  core/types/snapshot.go
  core/types/snapshot_nodes.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: tech-debt, no-changelog, no-issue

#6355 fix: openrpc typo
  wallet/api/openrpc.json
Labels: no-changelog, no-issue

#6352 fix: dropping db intermittently hangs on snapshot test
  datanode/snapshot/service_test.go
Labels: no-changelog

#6339 fix: take epoch snapshot when asked, and propagate restore epoch seq …
  core/epochtime/service.go
  core/epochtime/snapshot.go
  core/epochtime/snapshot_test.go
  core/snapshot/engine.go
Labels: no-changelog, no-issue
