Repository vegaprotocol/vega, pull requests merged in 2022-11, with the labels that each got.

#6610 chore: add research as approvers netparam defaults
  CODEOWNERS
Labels: no-changelog, no-issue

#6666 fix: dehistory - log missed error
  datanode/dehistory/snapshot/block_commit_handler.go
  datanode/dehistory/snapshot/service_create_snapshot.go
Labels: no-changelog

#6677 fix: add to project action update query
  .github/workflows/add_issue_to_project.yml
Labels: no-changelog, no-issue

#6674 fix: ensure read is isolated before returning event processing thread
  datanode/dehistory/snapshot/service_create_snapshot.go
Labels: no-changelog

#6690 chore: add comments LP pegged volume calculation
  core/integration/features/verified/0034-PROB-liquidity_measure.feature
Labels: feature tests, no-changelog, no-issue

#6512 feat: add a FT negative position desimal
  core/integration/features/verified/Negative-Position-Decimal-Places.feature
Labels: feature tests, no-changelog, no-issue

#6693 fix: never wipe dehistory before load
  cmd/data-node/commands/dehistory/load.go
Labels: no-changelog

#6684 feat: update validation range for sigma in risk
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  core/governance/engine_new_market_test.go
  core/governance/market.go
Labels: feature, no-changelog, no-issue

#6710 The node selector is now behaving consitently
  wallet/api/node/round_robin_selector.go
  wallet/api/node/round_robin_selector_test.go
Labels: no-changelog, no-issue

#6695 fix: add issues to project
  .github/workflows/add_issue_to_project.yml
  .github/workflows/project_management.yml
Labels: no-changelog, no-issue

#6708 chore: remove duplicate function
  core/execution/market.go
  core/execution/pegged_orders.go
Labels: no-changelog, no-issue

#6567 Lp margin release issue
  core/integration/features/liquidity-provision/lp-margin-post-auction.feature
Labels: no-changelog, no-issue

#6714 feat: allow target port specification for latest dehistory segment source
  cmd/data-node/commands/dehistory/latest_history_segment.go
  cmd/data-node/commands/dehistory/list_active_peers.go
  cmd/data-node/commands/start/node_pre.go
  datanode/broker/buffered_event_source.go
  datanode/dehistory/initialise/config.go
  datanode/dehistory/initialise/initialise.go
  datanode/dehistory/store/store.go
Labels: no-changelog

#6624 feat: test tau scaling in LP provision
  core/integration/features/verified/test-tau-scaling.feature
Labels: feature tests, no-changelog, no-issue

#6730 dehistory command errors need to unwrap the grpc error
  cmd/data-node/commands/dehistory/dump-segment.go
  cmd/data-node/commands/dehistory/fetch.go
  cmd/data-node/commands/dehistory/latest_history_segment.go
  cmd/data-node/commands/dehistory/list_active_peers.go
Labels: no-changelog

#6734 fix: always wipe database when wipe on startup flag is set
  cmd/data-node/commands/start/node_pre.go
  datanode/dehistory/snapshot/service_load_snapshot.go
  datanode/sqlstore/sqlstore.go
  datanode/utils/databasetest/setup.go
Labels: no-changelog

#6745 chore: re-enable cp test
  core/governance/market_cp_restore_test.go
  core/governance/testcp/checkpoint.cp
Labels: no-changelog, no-issue

#6761 fix: set the snapshot creation timeout log default greater than reasonable snapshot creation time
  datanode/dehistory/snapshot/config.go
  datanode/dehistory/snapshot/service_create_snapshot.go
Labels: no-changelog

#6749 fix: unhandled error when fetching history blocks
  datanode/dehistory/initialise/initialise.go
Labels: no-changelog

#6771 fix: still record a block even if one of the transactions causes a panic
  cmd/vega/node/node.go
  core/blockchain/nullchain/nullchain.go
  core/blockchain/nullchain/nullchain_test.go
  core/blockchain/nullchain/replay.go
Labels: no-changelog, no-issue

#6773 Cover 0003-MTMK-013
  core/integration/features/verified/0003-MTMK-mark_to_market_settlement.feature
Labels: no-changelog, no-issue

#6752 chore: set all release as pre-release
  .github/workflows/release-binaries.yml
Labels: no-changelog, no-issue

#6750 fix: fix data source resolvers
  CHANGELOG.md
  datanode/gateway/graphql/future_product_resolver.go
  datanode/gateway/graphql/future_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/oracles_resolver.go
  datanode/gateway/graphql/oracles_resolver_test.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/gateway/graphql/update_future_resolver.go
Labels: bug

#6740 Fanout event source swallows errors
  datanode/broker/buffered_event_source.go
  datanode/broker/fan_out_event_source.go
Labels: no-changelog

#6779 Chore/release 0.62.1
  .github/workflows/release-binaries.yml
  CHANGELOG.md
  cmd/vega/node/node.go
  commands/transfer_funds.go
  core/blockchain/nullchain/nullchain.go
  core/blockchain/nullchain/nullchain_test.go
  core/blockchain/nullchain/replay.go
  core/execution/market.go
  core/execution/market_test.go
  core/governance/engine.go
  core/governance/engine_new_asset_test.go
  core/governance/market_cp_restore_test.go
  core/governance/testcp/checkpoint.cp
  core/integration/features/verified/0003-MTMK-mark_to_market_settlement.feature
  core/integration/features/verified/0026-AUCT-auction_interaction.feature
  core/liquidity/engine.go
  core/liquidity/engine_test.go
  core/types/banking.go
  core/types/data.go
  core/types/data_source.go
  datanode/broker/buffered_event_source.go
  datanode/broker/fan_out_event_source.go
  datanode/dehistory/initialise/initialise.go
  datanode/dehistory/snapshot/config.go
  datanode/dehistory/snapshot/service_create_snapshot.go
  datanode/entities/transfer.go
  datanode/gateway/graphql/future_product_resolver.go
  datanode/gateway/graphql/future_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/oracles_resolver.go
  datanode/gateway/graphql/oracles_resolver_test.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/gateway/graphql/update_future_resolver.go
  datanode/sqlstore/config.go
  datanode/sqlstore/deposits_test.go
  datanode/sqlstore/erc20_multisig_added_test.go
  datanode/sqlstore/liquidity_provision_test.go
  datanode/sqlstore/margin_level_test.go
  datanode/sqlstore/market_data_test.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/notary_test.go
  datanode/sqlstore/oracle_data_test.go
  datanode/sqlstore/oracle_spec_test.go
  datanode/sqlstore/risk_factor_test.go
  datanode/sqlstore/sqlstore.go
  datanode/sqlstore/sqlstore_test.go
  datanode/sqlstore/stake_linking_test.go
  datanode/sqlstore/withdrawals_test.go
  datanode/utils/databasetest/setup.go
  go.mod
  go.sum
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#6743 chore: update version
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#6778 feat: check liquidity fee between multiple LPs AC 0042-LIQF-010
  core/integration/features/verified/0042-LIQF-fees_rewards_multi_lps.feature
Labels: feature tests, no-changelog, no-issue

#6739 Cover new AC
  core/integration/features/verified/closeout-lognormal.feature
Labels: no-changelog, no-issue

#6786 chore: upgrade gqlgen
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/tools/tools.go
  go.mod
  go.sum
Labels: no-changelog, no-issue

#6791 chore: shorter tmp dir names and cleanup after
  datanode/dehistory/service_test.go
  datanode/dehistory/snapshot/orders/update_current_orders_test.go
  datanode/sqlstore/sqlstore_test.go
Labels: no-changelog, no-issue

#6802 fix: internal data source validations
  CHANGELOG.md
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  protos/vega/spec_definition.go
Labels: bug

#6804 chore: upgrade to tendermint 0.34.23
  go.mod
  go.sum
Labels: no-changelog, no-issue

#6800 test: cover 0042-LIQF-022
  core/integration/features/verified/0042-LIQF-fees_rewards.feature
Labels: no-changelog, no-issue

#6794 feat: label AC for spec 0007
  core/integration/features/liquidity-provision/verify-CcySiska.feature
  core/integration/features/verified/Test-PnL.feature
Labels: feature tests, no-changelog, no-issue

#6811 fix: add inputData validation in nullblockchain
  commands/transaction.go
  core/processor/tx.go
Labels: no-changelog

#6810 test: cover extended AC
  core/integration/features/verified/0042-LIQF-fees_rewards.feature
Labels: no-changelog, no-issue

#6798 chore: remove and reserve unused transfer types
  core/types/transfer.go
  datanode/entities/ledgerentry.go
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#6787 feat: add AC number for 0007
  core/integration/features/verified/verified-positions-resolution-1.feature
Labels: feature tests, no-changelog, no-issue

#6822 fix: log when visor resorts to having to force kill binaries
  visor/visor.go
Labels: no-changelog

#6838 feat: feature test to cover LP shape limits
  core/integration/features/liquidity-provision/lp-invalid-shape.feature
  core/integration/steps/parties_submit_liquidity_provision.go
  core/integration/steps/the_liquidity_provisions_should_have_the_following_states.go
Labels: no-changelog, no-issue

#6836 feat: Start releasing binaries at the very beginning of the pipeline to reduce pipeline duration
  Jenkinsfile
Labels: no-changelog

#6814 fix: wallet openrpc examples
  wallet/api/openrpc.json
Labels: no-changelog, no-issue

#6817 fix: inconsistent use of node field on edges
  CHANGELOG.md
  datanode/entities/account_balance.go
  datanode/entities/ethereum_key_rotation.go
  datanode/gateway/graphql/account_edge_resolver.go
  datanode/gateway/graphql/asset_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: breaking-change

#6847 6746 network data
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/entities/enums.go
  datanode/entities/node.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/node_data_resolver.go
  datanode/gateway/graphql/schema.graphql
  datanode/integration/nodes_test.go
  datanode/integration/testdata/golden/TestNodeData_NodeData
  datanode/sqlstore/node.go
  datanode/sqlstore/node_test.go
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: breaking-change

#6834 fix: add more columns to ledger entries query result
  datanode/api/trading_data_v2.go
  datanode/entities/aggregated_ledgerentries.go
  datanode/entities/ledgerentry_filter.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/service/ledger.go
  datanode/sqlstore/ledger.go
  datanode/sqlstore/ledger_test.go
  datanode/sqlstore/ledgerentry_filter.go
  datanode/sqlstore/migrations/0001_initial.sql
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: breaking-change, no-changelog

#6857 chore: format block duration in statistics
  datanode/gateway/graphql/statistics.go
Labels: no-changelog, no-issue

#6865 chore: remove stray backslash
  blockexplorer/entities/transaction.go
Labels: no-changelog, no-issue

#6874 fix: add limit error to errors
  protos/vega/errors.go
Labels: no-changelog, no-issue

#6868 feat: create feature test for 0044-LIME-009
  core/integration/features/verified/liquidity-provision-bond-account-dp.feature
Labels: no-changelog, no-issue

#6875 feat: correct mystery AC in feature tests
  core/integration/features/verified/0026-AUCT-auction_interaction.feature
  core/integration/features/verified/0034-PROB-liquidity_measure.feature
Labels: no-changelog

#6866 feat: dehistory handle protocol upgrade
  cmd/data-node/commands/dehistory/load.go
  cmd/data-node/commands/start/node_pre.go
  datanode/broker/sqlstore_broker.go
  datanode/broker/sqlstore_broker_test.go
  datanode/dehistory/protocol_upgrade_handler.go
  datanode/dehistory/service.go
  datanode/dehistory/service_test.go
  datanode/dehistory/snapshot/block_commit_handler.go
  datanode/dehistory/snapshot/block_commit_handler_test.go
  datanode/dehistory/snapshot/service.go
  datanode/dehistory/snapshot/service_create_snapshot.go
  datanode/dehistory/snapshot/service_load_snapshot.go
  datanode/dehistory/testdata/testmigration.sql
  datanode/sqlstore/migrations/0001_initial.sql
  datanode/sqlstore/sqlstore.go
Labels: no-changelog

#6933 feat: update datanode ipfs config to specify ipfs peer id and priv key direclty
  datanode/dehistory/service_test.go
  datanode/dehistory/store/config.go
  datanode/dehistory/store/store.go
Labels: no-changelog

#6944 feat: add test to cover 0013-ACCT-022
  core/integration/features/verified/Funding-insurance_pool.feature
Labels: no-changelog

#6946 fix: deshistory was in some cases using the wrong column filter for history tables
  datanode/dehistory/snapshot/database_meta_data.go
  datanode/dehistory/snapshot/history.go
Labels: no-changelog

#6943 feat: label AC: 0013-ACCT-020
  core/integration/features/liquidity-provision/verify-CcySiska.feature
Labels: no-changelog

#6938 Remove redundant TickSize() method
  core/execution/market.go
  core/execution/market_snapshot.go
  core/liquidity/engine.go
  core/liquidity/engine_test.go
  core/liquidity/snapshot.go
  core/types/market.go
Labels: no-changelog, no-issue

#6939 fix: add missing fields in check tx response
  core/api/core.go
  protos/sources/vega/api/v1/core.proto
  protos/vega/api/v1/core.pb.go
Labels: no-changelog, no-issue

#6954 feat: wallet V2 permissions are updated dynamically when an operation…
  CHANGELOG.md
  cmd/vegawallet/commands/service_run.go
  wallet/api/api.go
  wallet/api/client_list_keys.go
  wallet/api/client_list_keys_test.go
  wallet/api/client_request_permissions.go
  wallet/api/interactor/interaction.go
Labels: breaking-change

#6952 docs: fix typos and improve API descriptions
  CHANGELOG.md
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/schema.graphql
  protos/sources/vega/commands/v1/transaction.proto
  protos/sources/vega/commands/v1/validator_commands.proto
  protos/sources/vega/markets.proto
  protos/vega/commands/v1/transaction.pb.go
  protos/vega/commands/v1/validator_commands.pb.go
  protos/vega/markets.pb.go
Labels: documentation

#6968 Improve cucumber reporting
  core/integration/main_test.go
  core/integration/setup_test.go
Labels: no-changelog, no-issue

#6972 fix: use TransferType in LedgerEntre (graphql)
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/modelext.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog, no-issue

#6961 feat: create feature test for 0011-MARA-006
  core/integration/features/verified/0011-MARA-006.feature
Labels: no-changelog, no-issue

#6912 feat: simplify config and make it so only publishing nodes create segments
  cmd/data-node/commands/start/node_pre.go
  datanode/config/config.go
  datanode/dehistory/block_commit_handler.go
  datanode/dehistory/block_commit_handler_test.go
  datanode/dehistory/config.go
  datanode/dehistory/service.go
  datanode/dehistory/service_test.go
Labels: no-changelog

#6979 chore: rename admin.describe_network to name
  CHANGELOG.md
  cmd/vegawallet/commands/network_describe.go
  cmd/vegawallet/commands/network_describe_test.go
  wallet/api/admin_describe_network.go
  wallet/api/admin_describe_network_test.go
  wallet/api/openrpc.json
Labels: breaking-change

#6990 feat: add test for AC 0011-MARA-016, 0011-MARA-017
  core/integration/features/verified/0011-MARA-016017.feature
Labels: no-changelog
