Repository vegaprotocol/vega, pull requests merged in 2022-08, with the labels that each got.

#5669 ci: fix builders
  Jenkinsfile
Labels: no-changelog, no-issue

#5661 docs: update gql fields
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog

#5686 ci: optimise buildx and publish commit hash tags
  Jenkinsfile
  docker/.gitignore
  docker/Dockerfile
  docker/data-node.dockerfile
  docker/vega.dockerfile
  docker/vegawallet.dockerfile
Labels: no-changelog, no-issue

#5716 ci: for PRs compile linux-amd64 only
  Jenkinsfile
Labels: no-changelog, no-issue

#5718 fix: do not trim 0x from the eth address since we now store it with t…
  datanode/api/trading_data_v2.go
Labels: no-changelog, no-issue

#5768 chore: migrate protos linters from previous repo
  .gitignore
  Jenkinsfile
  Makefile
  script/generate.sh
  script/generate_json.sh
  script/gettools.sh
Labels: no-changelog, no-issue

#5784 fix: cursor row filtering
  CHANGELOG.md
  datanode/sqlstore/cursor.go
  datanode/sqlstore/cursor_test.go
  datanode/sqlstore/utils.go
Labels: DatanodeV2

#5780 chore: add frontend team as codeowners of the graphql schema
  CODEOWNERS
Labels: no-changelog, no-issue

#5800 feat: add feature test to cover AC 0006-POSI-008
  core/integration/features/verified/0006-POSI-AC-008.feature
Labels: feature tests, no-changelog, no-issue

#5801 ci: add diff check of go generate
  .golangci.toml
  Jenkinsfile
  Makefile
  core/bridges/mocks/eth_client_mock.go
  go.sum
Labels: no-changelog

#5645 feat: add feature test to cover AC 0006-POSI-009
  core/integration/features/verified/0006-POSI-AC009.feature
Labels: no-changelog, no-issue

#5808 fix: ensure parked orders are kept sorted
  core/execution/pegged_orders.go
Labels: no-changelog, no-issue

#5833 fix: update review comment come after approval
  .github/workflows/project_management.yml
Labels: no-changelog, no-issue

#5668 fix: fix oracle termination before enactment
  CHANGELOG.md
  core/execution/market.go
  core/execution/snapshot_test.go
  core/governance/checkpoint.go
  core/governance/checkpoint_test.go
  core/governance/engine.go
  core/governance/engine_freeform_test.go
  core/governance/engine_new_asset_test.go
  core/governance/engine_new_market_test.go
  core/governance/engine_test.go
  core/governance/engine_update_market_test.go
  core/governance/market.go
  core/governance/mocks/markets_mock.go
  core/governance/snapshot_test.go
  core/integration/features/settlement/0002-STTL-settlement_at_expiry_with_dp.feature
  core/integration/features/settlement/settlement_at_expiry_by_time_from_internal_oracle.feature
  core/integration/features/verified/0002-STTL-settlement_at_expiry.feature
Labels: bug

#5847 Fix update asset snapshot
  core/banking/snapshot.go
  core/types/snapshot_nodes.go
Labels: no-changelog, no-issue

#5844 fix: revisit handling cancelled market
  core/execution/market.go
  core/governance/engine.go
  core/governance/engine_update_market_test.go
Labels: Medium, bug, no-changelog

#5861 fix: remove extra `0` in the AC code tag
  core/integration/features/verified/0006-POSI-AC009.feature
Labels: feature tests, no-changelog, no-issue

#5648 Fix: Eth key rotation fix
  CHANGELOG.md
  core/coreapi/services/validators.go
  core/validators/topology_checkpoint_test.go
  core/validators/topology_eth_key_rotate.go
  core/validators/topology_eth_key_rotate_test.go
  core/validators/topology_snapshot_test.go
Labels: bug

#5894 Standarize system tests
  Jenkinsfile
  Jenkinsfile-system-tests
Labels: no-changelog, no-issue

#5908 fix: equity-like-shares
  datanode/entities/marketdata.go
  datanode/sqlstore/market_data_test.go
Labels: no-changelog, no-issue

#5910 chore: remove flaky tests
  datanode/sqlstore/sqlstore_test.go
  datanode/utils/observer_test.go
Labels: no-changelog, no-issue

#5905 chore: add binaries created by system tests to gitignore
  .gitignore
Labels: no-changelog, no-issue

#5909 feat: AC for 0029-FEES-005
  core/integration/features/verified/0029-FEES-fees.feature
Labels: no-changelog, no-issue

#5658 chore: update readme + move vega readme under the core directory
  README.md
  core/README.md
Labels: no-changelog, no-issue

#5917 chore: add a new network parameter for rewards market creation quantu…
  core/execution/engine.go
  core/netparams/defaults.go
  core/netparams/keys.go
  core/protocol/all_services.go
Labels: no-changelog, no-issue

#5919 ci: fix Publish step
  Jenkinsfile
Labels: no-changelog, no-issue

#5921 chore: update go-ethereum dependency to 1.10.21
  go.mod
  go.sum
Labels: no-changelog, no-issue

#5922 update cosmos/iavl deps to 0.19.1
  core/snapshot/engine.go
  core/snapshot/engine_test.go
  core/snapshot/snapshots.go
  core/types/snapshot.go
  core/types/snapshot_nodes_test.go
  go.mod
  go.sum
Labels: no-changelog, no-issue

#5874 Better notification for version update on the wallet
  CHANGELOG.md
  cmd/vegawallet/commands/cmd.go
  cmd/vegawallet/commands/command_send.go
  cmd/vegawallet/commands/command_sign.go
  cmd/vegawallet/commands/root.go
  cmd/vegawallet/commands/service_run.go
  cmd/vegawallet/commands/tx_send.go
  cmd/vegawallet/commands/version.go
  wallet/version/version.go
Labels: no-issue

#5923 Add chain ID to transaction documentation
  protos/sources/vega/commands/v1/transaction.proto
  protos/vega/commands/v1/transaction.pb.go
Labels: no-changelog, no-issue

#5875 Prepare wallet JSON-RPC API to support admin methods
  cmd/vegawallet/commands/service_run.go
  wallet/api/api.go
  wallet/api/mocks/network_store_mock.go
  wallet/api/openrpc.json
  wallet/api/session_connect_wallet.go
  wallet/api/session_connect_wallet_test.go
  wallet/api/session_disconnect_wallet.go
  wallet/api/session_disconnect_wallet_test.go
  wallet/api/session_get_permissions.go
  wallet/api/session_get_permissions_test.go
  wallet/api/session_list_keys.go
  wallet/api/session_list_keys_test.go
  wallet/api/session_request_permissions.go
  wallet/api/session_request_permissions_test.go
  wallet/api/session_send_transaction.go
  wallet/api/session_send_transaction_test.go
Labels: no-changelog, no-issue

#5876 Add method `session.get_chain_id` to wallet JSON-RPC API
  wallet/api/api.go
  wallet/api/openrpc.json
  wallet/api/session_get_chain_id.go
  wallet/api/session_get_chain_id_test.go
Labels: no-changelog, no-issue

#5927 chore: improve docs generation + add docs comment + openapiv2 in coreapis
  Makefile
  buf.gen.swagger.yaml
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/core_grpc.pb.go
  protos/vega/api/v1/corestate.pb.go
  protos/vega/api/v1/corestate_grpc.pb.go
  version/version.go
Labels: no-changelog, no-issue

#5920 Feature/more go generate speed up
  core/governance/engine.go
  core/governance/mocks/assets_mock.go
  core/governance/mocks/markets_mock.go
  core/governance/mocks/mocks.go
  core/governance/mocks/netparams_mock.go
  core/governance/mocks/staking_accounts_mock.go
  core/governance/mocks/time_service_mock.go
  core/governance/mocks/witness_mock.go
  core/staking/accounting.go
  core/staking/mocks/eth_confirmations_mock.go
  core/staking/mocks/eth_on_chain_verifier_mock.go
  core/staking/mocks/ethereum_client_confirmations_mock.go
  core/staking/mocks/ethereum_event_source_mock.go
  core/staking/mocks/evt_forwarder_mock.go
  core/staking/mocks/mocks.go
  core/staking/mocks/time_service_mock.go
  core/staking/mocks/witness_mock.go
  core/staking/stake_verifier.go
  core/staking/staking.go
  core/validators/erc20multisig/mocks/eth_confirmations_mock.go
  core/validators/erc20multisig/mocks/ethereum_event_source_mock.go
  core/validators/erc20multisig/mocks/mocks.go
  core/validators/erc20multisig/mocks/multisig_on_chain_verifier_mock.go
  core/validators/erc20multisig/mocks/witness_mock.go
  core/validators/erc20multisig/on_chain_verifier.go
  core/validators/erc20multisig/topology.go
  core/validators/mocks/commander_mock.go
  core/validators/mocks/mocks.go
  core/validators/mocks/node_wallet_mock.go
  core/validators/mocks/notary_mock.go
  core/validators/mocks/signatures_mock.go
  core/validators/mocks/time_service_mock.go
  core/validators/mocks/val_performance_mock.go
  core/validators/mocks/validator_topology_mock.go
  core/validators/mocks/wallet_mock.go
  core/validators/node_wallet_wrapper.go
  core/validators/signatures.go
  core/validators/topology.go
  core/validators/validators.go
  core/validators/witness.go
Labels: no-changelog, no-issue

#5924 chore: remove go-proto-validators
  core/netparams/defaults.go
  core/netparams/values.go
  core/netparams/values_test.go
  go.mod
  go.sum
Labels: no-changelog, no-issue

#5911 fix: incorrect data types on some market data fields
  datanode/entities/marketdata.go
  datanode/entities/marketdata_test.go
  datanode/sqlstore/market_data_test.go
  datanode/sqlstore/migrations/0001_initial.sql
Labels: no-changelog, no-issue

#5907 ci: compile and publish vega and data-node with GitHub Workflows
  .github/workflows/release-binaries.yml
  Jenkinsfile
Labels: no-changelog, no-issue

#5939 fix: gql docs for update asset + rename minLpStake to quantum in proposals
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/new_asset_resolver.go
  datanode/gateway/graphql/schema.graphql
  datanode/gateway/graphql/update_asset_resolver.go
Labels: no-changelog

#5942 fix: pending signature snapshots
  core/validators/signatures_snapshot.go
  core/validators/signatures_test.go
Labels: no-changelog, no-issue

#5895 fix: make id queries consitent
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/modelext.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog

#5936 ci: publish git tagged docker images using GitHub Workflows
  .github/workflows/build-vegawallet-docker-image.yml
  .github/workflows/release-binaries.yml
  .github/workflows/release-docker-images.yml
  Jenkinsfile
Labels: no-changelog, no-issue

#5952 fix: restore map to the correct key
  core/validators/signatures_snapshot.go
Labels: no-changelog, no-issue

#5957 chore: tidy up feature test for 0042 equity-like-share scenario3
  core/integration/features/verified/0042-LIQF-fees_rewards_VirtualStake.feature
Labels: no-changelog, no-issue

#5954 fix: add a log with vega version + commit hash on startup
  cmd/vega/node/node.go
Labels: no-changelog, no-issue

#5955 fix: check leveldb was open successfully / return an error
  core/snapshot/engine.go
Labels: no-changelog, no-issue

#5956 feat: add all grpc stream as websocket through the grpc gateway
  datanode/gateway/rest/server.go
  go.mod
  go.sum
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: no-changelog, no-issue

#5953 fix: update oracle relay deps
  go.mod
  go.sum
Labels: no-changelog, no-issue

#5959 ci: fix and improve publishing docker images
  .github/workflows/release-docker-images.yml
Labels: no-changelog, no-issue

#5962 Minor race in chain
  core/api/core.go
  core/processor/abci.go
Labels: no-changelog, no-issue

#5973 feat: change account subscription to have only top level fields
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog, no-issue

#5968 fix: ignore global accounts for market based rewards
  core/rewards/engine.go
Labels: no-changelog, no-issue

#5960 ci: run vega-market-sim tests on develop branch only
  Jenkinsfile
Labels: devops, no-changelog, no-issue

#5982 feat: add AC label 0016-PFUT-012
  core/integration/features/verified/0002-STTL-settlement_at_expiry.feature
Labels: feature, no-changelog, no-issue

#5976 (ci): #5670 add GHA for generating docs
  .github/workflows/release-docs.yml
  Jenkinsfile
  script/gettools.sh
Labels: no-changelog

#6001 feat: update tendermint to version 0.34.21
  go.mod
  go.sum
Labels: no-changelog, no-issue

#5891 Add admin wallet methods on wallet JSON RPC API
  cmd/vegawallet/commands/cmd.go
  cmd/vegawallet/commands/wallet_create.go
  cmd/vegawallet/commands/wallet_create_test.go
  cmd/vegawallet/commands/wallet_delete.go
  cmd/vegawallet/commands/wallet_delete_test.go
  cmd/vegawallet/commands/wallet_import.go
  cmd/vegawallet/commands/wallet_import_test.go
  cmd/vegawallet/commands/wallet_info.go
  cmd/vegawallet/commands/wallet_info_test.go
  cmd/vegawallet/commands/wallet_list.go
  wallet/api/admin_create_wallet.go
  wallet/api/admin_create_wallet_test.go
  wallet/api/admin_describe_wallet.go
  wallet/api/admin_describe_wallet_test.go
  wallet/api/admin_import_wallet.go
  wallet/api/admin_import_wallet_test.go
  wallet/api/admin_list_wallets.go
  wallet/api/admin_list_wallets_test.go
  wallet/api/admin_remove_wallet.go
  wallet/api/admin_remove_wallet_test.go
  wallet/api/api.go
  wallet/api/errors.go
  wallet/api/helpers_for_test.go
  wallet/api/mocks/mocks.go
  wallet/api/mocks/network_store_mock.go
  wallet/api/mocks/node_mock.go
  wallet/api/mocks/node_selector_mock.go
  wallet/api/mocks/pipeline_mock.go
  wallet/api/mocks/wallet_store_mock.go
  wallet/api/node/retrying_grpc_node.go
  wallet/api/node/round_robin_selector.go
  wallet/api/openrpc.json
  wallet/api/pipeline/sequential.go
  wallet/api/session_connect_wallet.go
  wallet/api/session_connect_wallet_test.go
  wallet/api/session_disconnect_wallet.go
  wallet/api/session_get_chain_id_test.go
  wallet/api/session_get_permissions.go
  wallet/api/session_list_keys_test.go
  wallet/api/session_request_permissions.go
  wallet/api/session_request_permissions_test.go
  wallet/api/session_send_transaction.go
  wallet/api/session_send_transaction_test.go
  wallet/api/sessions.go
  wallet/tests/sc_delete_wallet_test.go
  wallet/tests/sc_isolate_wallet_test.go
  wallet/tests/sc_sign_and_verify_command_test.go
  wallet/tests/sc_sign_and_verify_message_test.go
  wallet/wallet/errors.go
  wallet/wallet/handler.go
  wallet/wallet/handler_test.go
  wallet/wallet/hd_wallet.go
  wallet/wallet/hd_wallet_test.go
  wallet/wallet/store/v1/store.go
  wallet/wallets/handler.go
Labels: wallet, api, no-changelog, no-issue

#6019 chore: allow usage as vega tools and not installed as vegatools
  .golangci.toml
  cmd/vega/main.go
  cmd/vega/tools.go
  cmd/vegatools/commands/root.go
  cmd/vegatools/main.go
  vegatools/checkpoint/parse.go
  vegatools/snapshotdb/snapshotdb.go
  vegatools/stream/stream.go
Labels: no-changelog, no-issue

#6025 feat: add checkTx checks for protocol upgrade transaction
  core/processor/abci.go
  core/protocolupgrade/engine.go
Labels: no-changelog, no-issue

#6026 Add timeouts on `go test` commands
  Jenkinsfile
Labels: no-changelog, no-issue

#6018 chore: keep new-asset-proposal events between validator and non-valid…
  core/governance/node_validation.go
Labels: no-changelog, no-issue

#5981 feat: refactor trade subscribtion to use TradeUdpate
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/gateway/graphql/tradable_update_resolver.go
Labels: no-changelog, no-issue
