Repository vegaprotocol/vega, pull requests merged in 2022-10, with the labels that each got.

#6383 fix: copypasta in block explorer paths
  paths/paths.go
Labels: no-changelog, no-issue

#6372 chore: add updated project board automation
  .github/workflows/conventional_commits.yml
  .github/workflows/project_management.yml
Labels: no-changelog, no-issue

#6403 chore: add address to output when importing/generating ethereum keys
  core/nodewallets/eth/keystore/loader.go
Labels: no-changelog, no-issue

#6398 chore: add core transaction_result event
  core/events/bus.go
  core/events/transaction_result.go
  core/processor/abci.go
  datanode/broker/convert.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/modelext.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  protos/sources/vega/events/v1/events.proto
  protos/vega/events/v1/events.go
  protos/vega/events/v1/events.pb.go
Labels: no-changelog, no-issue

#6405 feat: multiple transactions submitted with the same proof of work al…
  core/pow/engine.go
  core/pow/engine_test.go
  core/pow/noop_engine.go
  core/processor/abci.go
Labels: no-changelog, no-issue

#6415 feat: add test PnL
  core/integration/features/verified/0002-STTL-settlement_at_expiry.feature
  core/integration/features/verified/Test-PnL.feature
Labels: no-changelog, no-issue

#6423 fix: use factored balance for infrastrctured fee reward for tendermin…
  core/rewards/engine.go
  core/rewards/engine_test.go
Labels: no-changelog, no-issue

#6360 chore: cleanup some more the amend order function
  core/execution/market.go
Labels: no-changelog, no-issue

#6424 feat: add settlement and MTM calculation
  core/integration/features/verified/Test-PnL.feature
Labels: no-changelog, no-issue

#6437 feat: add AC numbers for 0010-MARG
  core/integration/features/verified/0019-MCAL-margin_calculator-risk_parameters.feature
Labels: feature tests, no-changelog, no-issue

#6445 fix: leftover settlement bug fix
  core/collateral/engine.go
  core/collateral/engine_test.go
  core/products/future.go
Labels: no-changelog, no-issue

#6450 chore: update deploy (relates to: https://github.com/vegaprotocol/devops-infra/issues/1554)
  Jenkinsfile
Labels: no-changelog, no-issue

#6368 feat: add ledger entry api
  CHANGELOG.md
  core/collateral/engine.go
  datanode/api/errors.go
  datanode/api/trading_data_v2.go
  datanode/entities/aggregated_ledgerentries.go
  datanode/entities/entities.go
  datanode/entities/ledgerentry_field.go
  datanode/entities/ledgerentry_filter.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/marshallers/ledgerentry_field.go
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/graphql/modelext.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/service/ledger.go
  datanode/sqlstore/accounts_test.go
  datanode/sqlstore/assets_test.go
  datanode/sqlstore/balances_test.go
  datanode/sqlstore/candles_test.go
  datanode/sqlstore/delegations_test.go
  datanode/sqlstore/deposits_test.go
  datanode/sqlstore/helpers/accounts.go
  datanode/sqlstore/helpers/helpers.go
  datanode/sqlstore/helpers/markets.go
  datanode/sqlstore/ledger.go
  datanode/sqlstore/ledger_test.go
  datanode/sqlstore/ledgerentry_filter.go
  datanode/sqlstore/node_test.go
  datanode/sqlstore/oracle_spec_test.go
  datanode/sqlstore/orders_test.go
  datanode/sqlstore/parties_test.go
  datanode/sqlstore/proposals_test.go
  datanode/sqlstore/sqlstore_test.go
  datanode/sqlstore/stake_linking_test.go
  datanode/sqlstore/transfers_test.go
  datanode/sqlstore/votes_test.go
  datanode/sqlstore/withdrawals_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: api, DatanodeV2

#6476 chore: update version 0.59.0+dev
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#6475 feat: add feature test to cover change of CcySiska
  core/integration/features/liquidity-provision/verify-CcySiska.feature
Labels: no-changelog, no-issue

#6490 feat: cutting down core memory for banking and event forwarder
  core/banking/engine.go
  core/banking/snapshot.go
  core/evtforward/forwarder.go
  core/evtforward/snapshot.go
  core/types/snapshot_nodes.go
  core/types/snapshot_nodes_test.go
  go.mod
  go.sum
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog, no-issue

#6491 fix: add ledger entry docs to proto.
  datanode/sqlstore/ledger.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog

#6492 chore: don't copy protos from tendermint
  blockexplorer/entities/transaction.go
  protos/blockexplorer/blockexplorer.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
Labels: no-changelog, no-issue

#6493 Bugfix/6484
  protos/blockexplorer/blockexplorer.pb.go
  protos/blockexplorer/blockexplorer_grpc.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
Labels: no-changelog

#6502 Make the wallet version compatibility check reusable for desktop-wallet
  cmd/vegawallet/commands/cmd.go
  cmd/vegawallet/commands/command_send.go
  cmd/vegawallet/commands/service_run.go
  cmd/vegawallet/commands/version.go
  wallet/version/helpers.go
  wallet/version/version.go
Labels: wallet, no-changelog, no-issue

#6509 fix: rename GetERC20MultiSigSigner APIs to ListERC20MultiSignSigner
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/graphql/resolvers.go
  go.mod
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: breaking change, DatanodeV2

#6516 chore: remove extraneous logging for market settled event
  datanode/sqlsubscribers/position.go
Labels: DatanodeV2, no-changelog, no-issue

#6523 feat: update default retention policies
  datanode/sqlstore/config.go
Labels: no-changelog

#6503 chore: update move item mutation field names
  .github/workflows/project_management.yml
Labels: no-changelog

#6540 chore: add epoch information to statistics on core
  core/api/core.go
  core/protocol/all_services.go
  core/stats/stats.go
  protos/sources/vega/api/v1/core.proto
  protos/vega/api/v1/core.pb.go
Labels: no-changelog, no-issue

#6543 fix: EpochStartTime typo corrected
  core/api/core.go
Labels: no-changelog, no-issue

#6544 chore: improve unit test
  core/events/ledger_movements.go
  core/events/ledger_movements_test.go
  core/integration/stubs/broker_stub.go
Labels: no-changelog, no-issue

#6548 chore: upgrade to tendermint 0.34.22
  go.mod
  go.sum
Labels: no-changelog, no-issue

#6551 fix: output from nodewallet reload is now more useful
  CHANGELOG.md
  cmd/vega/nodewallet/reload.go
  core/admin/nodewallets.go
Labels: breaking change

#6559 chore: set version 0.60.0+dev
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#6562 fix: emit event when external account is created for enabled asset
  core/collateral/checkpoint_test.go
  core/collateral/engine.go
  core/collateral/engine_test.go
Labels: no-changelog, no-issue

#6566 fix: positions inserter not using dedicated postgres connection
  datanode/sqlstore/positions.go
Labels: no-changelog, no-issue

#6575 fix: add nil pointers handling
  datanode/entities/aggregated_ledgerentries.go
Labels: no-changelog

#6573 Restructure logger used in wallet for reusability
  cmd/vegawallet/commands/cmd.go
  cmd/vegawallet/commands/command_send.go
  cmd/vegawallet/commands/command_send_test.go
  cmd/vegawallet/commands/command_sign.go
  cmd/vegawallet/commands/logger.go
  cmd/vegawallet/commands/logger_unix.go
  cmd/vegawallet/commands/service_run.go
  cmd/vegawallet/commands/tx_send.go
  cmd/vegawallet/commands/tx_send_test.go
  cmd/vegawallet/commands/wallet_import.go
  libs/zap/builder.go
  libs/zap/config.go
  libs/zap/config_unix.go
  libs/zap/config_windows.go
  libs/zap/level.go
  libs/zap/sync.go
  paths/file.go
Labels: no-changelog, no-issue

#6580 feat: fix relase-pipeline
  .github/workflows/release-binaries.yml
Labels: no-changelog, no-issue

#6578 chore: dns remove data merge from dehistory
  cmd/data-node/commands/dehistory/load.go
  cmd/data-node/commands/dehistory/show.go
  datanode/dehistory/aggregation/aggregation.go
  datanode/dehistory/aggregation/aggregation_test.go
  datanode/dehistory/service.go
  datanode/dehistory/service_test.go
  datanode/dehistory/snapshot/service.go
  datanode/dehistory/snapshot/service_create_snapshot.go
Labels: no-changelog

#6607 fix: add trading service documentation
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog

#6586 chore: improve TransferType mapping
  CHANGELOG.md
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/marshallers/marshallers.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers.go
Labels: refactor

#6590 fix: improve grpc error when dehistory disabled
  datanode/api/errors.go
  datanode/api/trading_data_v2.go
Labels: no-changelog

#6618 fix: emit event for stopping LP upon settlement
  core/execution/market.go
Labels: no-changelog

#6629 chore: reenable checkpoint restore test
  core/governance/market_cp_restore_test.go
  core/governance/testcp/checkpoint.cp
Labels: no-changelog, no-issue

#6632 fix: improve documentation for OracleSubmission
  CHANGELOG.md
  protos/sources/vega/commands/v1/data.proto
  protos/vega/commands/v1/data.pb.go
Labels: documentation, oracles

#6631 feat: update risk parameter ranges validation
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  core/governance/engine_new_market_test.go
  core/governance/market.go
Labels: feature, no-changelog

#6636 feat: dehistory data retention
  datanode/dehistory/service.go
  datanode/dehistory/service_test.go
  datanode/dehistory/store/config.go
  datanode/dehistory/store/index.go
  datanode/dehistory/store/store.go
  datanode/dehistory/store/store_test.go
Labels: no-changelog

#6625 chore: Update data-node readme
  datanode/README.md
Labels: DatanodeV2, no-changelog, no-issue

#6611 fix: simplify and fix dehistory snapshot paths
  cmd/data-node/commands/dehistory/load.go
  cmd/data-node/commands/start/node_pre.go
  datanode/dehistory/config.go
  datanode/dehistory/initialise/initialise.go
  datanode/dehistory/service_test.go
  datanode/dehistory/snapshot/config.go
  datanode/dehistory/snapshot/service.go
  datanode/dehistory/snapshot/service_create_snapshot.go
  datanode/dehistory/snapshot/service_load_snapshot.go
  datanode/dehistory/store/store.go
  paths/paths.go
  script/postgres-docker.sh
Labels: no-changelog

#6649 chore: set version 0.62.0+dev
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue
