Repository vegaprotocol/vega, pull requests merged in 2022-12, with the labels that each got.

#7003 chore: expose ObserveEventBus on Core REST API
  protos/sources/vega/grpc-rest-bindings.yml
  protos/vega/api/v1/core.pb.gw.go
Labels: no-changelog, no-issue

#7013 Release/v0.63.1
  CHANGELOG.md
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/sources/vega/grpc-rest-bindings.yml
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/core.pb.gw.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#7015 fix: datanode socketDir CLI long option
  datanode/sqlstore/config.go
Labels: no-changelog, no-issue

#7020 feat: add test for AC: 0013-ACCT-001
  core/integration/features/verified/Funding-insurance_pool.feature
Labels: no-changelog

#7050 feat: switching on dehistory store debug logging should enable IPFS debug logging
  datanode/dehistory/store/store.go
Labels: no-changelog

#7043 Rename `network` to `name` in `admin.remove_network`
  CHANGELOG.md
  cmd/vegawallet/commands/network_delete.go
  cmd/vegawallet/commands/network_delete_test.go
  wallet/api/admin_remove_network.go
  wallet/api/admin_remove_network_test.go
  wallet/api/openrpc.json
Labels: breaking-change

#7046 Release/v0.63.2
  CHANGELOG.md
  cmd/vegawallet/commands/network_delete.go
  cmd/vegawallet/commands/network_delete_test.go
  libs/jsonrpc/api.go
  libs/jsonrpc/api_test.go
  wallet/api/admin_remove_network.go
  wallet/api/admin_remove_network_test.go
  wallet/api/api.go
  wallet/api/errors.go
  wallet/api/openrpc.json
  wallet/service/service_v2.go
Labels: no-issue

#7014 Add LP price range prameter to the APIs
  commands/errors.go
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  core/examples/nullchain/transactions.go
  core/execution/market_snapshot.go
  core/governance/engine.go
  core/governance/engine_test.go
  core/governance/market.go
  core/integration/steps/the_markets.go
  core/types/governance_new_market.go
  core/types/governance_proposal.go
  core/types/governance_update_market.go
  core/types/market.go
  core/types/market_test.go
  core/types/snapshot_nodes_test.go
  datanode/entities/market.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/new_market_resolver.go
  datanode/gateway/graphql/schema.graphql
  datanode/sqlstore/markets.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/migrations/0001_initial.sql
  datanode/sqlsubscribers/market_created_test.go
  protos/sources/vega/governance.proto
  protos/sources/vega/markets.proto
  protos/vega/governance.pb.go
  protos/vega/markets.pb.go
  vegatools/checkpoint/type.go
Labels: no-changelog, no-issue

#7084 Check peer swarm key matches when getting latest history segment
  cmd/data-node/commands/dehistory/latest_history_segment.go
  datanode/api/mocks/dehistory_service_mock.go
  datanode/api/server.go
  datanode/api/trading_data_v2.go
  datanode/dehistory/initialise.go
  datanode/dehistory/initialise_test.go
  datanode/dehistory/mocks/dehistory_service_mock.go
  datanode/dehistory/service.go
  datanode/dehistory/store/config.go
  datanode/dehistory/store/store.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog

#7110 feat: label AC 0038-OLIQ-011
  core/integration/features/position_tracking/verified-positions-resolution-5-lognormal.feature
Labels: no-changelog, no-issue

#7111 feat: update AC 0003-015
  core/integration/features/verified/Negative-Position-Decimal-Places.feature
Labels: no-changelog

#7120 Using time.Time as a map key is tricky and should be avoided for maximum predictability
  core/banking/checkpoint.go
  core/banking/engine.go
  core/banking/oneoff_transfers.go
  core/delegation/engine_test.go
  core/integration/stubs/staking_account_stub.go
  datanode/sqlstore/market_data_test.go
Labels: no-changelog, no-issue

#7126 fix: 7097 unstable data node tests
  datanode/dehistory/service_test.go
Labels: no-changelog

#7138 fix: fixed snapshot table setup
  datanode/sqlstore/migrations/0001_initial.sql
  datanode/sqlstore/snapshot_data.go
  datanode/sqlstore/snapshot_data_test.go
Labels: no-changelog, no-issue

#7141 fix: dehistory load was using incorrect database version when selecting constraints metadata
  cmd/data-node/commands/dehistory/load.go
  cmd/data-node/commands/start/node_pre.go
  datanode/dehistory/fsutil/fsutil.go
  datanode/dehistory/initialise.go
  datanode/dehistory/initialise_test.go
  datanode/dehistory/mocks/dehistory_service_mock.go
  datanode/dehistory/service.go
  datanode/dehistory/service_test.go
  datanode/dehistory/snapshot/service_load_snapshot.go
  datanode/dehistory/store/store.go
  datanode/dehistory/testdata/testmigration.sql
  datanode/sqlstore/sqlstore.go
  datanode/utils/databasetest/setup.go
Labels: no-changelog

#7147 fix: rotate key example
  wallet/api/openrpc.json
Labels: no-changelog, no-issue

#7155 fix: allow max connection pool size to be specified
  datanode/sqlstore/config.go
  datanode/sqlstore/connection_source.go
Labels: no-changelog

#7159 fix: add flags to force load and wipe exsiting data to load cmd
  cmd/data-node/commands/dehistory/load.go
Labels: no-changelog

#7161 fix: fix distributed payout type
  core/types/transfer.go
  datanode/dehistory/service_test.go
  datanode/entities/ledgerentry.go
  datanode/gateway/graphql/schema.graphql
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog

#7176 fix: protocolupgrade required majority should allow equality
  core/protocolupgrade/engine.go
Labels: no-changelog, no-issue

#6935 chore: remove decimals value from futures objects
  CHANGELOG.md
  core/collateral/engine.go
  core/collateral/engine_test.go
  core/execution/market.go
  core/execution/market_snapshot.go
  core/execution/market_test.go
  core/governance/engine.go
  core/governance/market.go
  core/integration/steps/market/defaults/oracle-config/default-dai-for-future.json
  core/integration/steps/market/defaults/oracle-config/default-eth-for-future.json
  core/integration/steps/market/defaults/oracle-config/default-usd-for-future.json
  core/integration/steps/the_markets.go
  core/oracles/engine_subscribers.go
  core/oracles/oracle_spec.go
  core/oracles/oracle_spec_test.go
  core/products/future.go
  core/products/future_for_test.go
  core/products/future_test.go
  core/products/products.go
  core/products/products_test.go
  core/types/data.go
  core/types/data_source.go
  core/types/governance_new_market.go
  core/types/governance_update_market.go
  core/types/market.go
  core/types/snapshot_nodes.go
  datanode/dehistory/service_test.go
  datanode/entities/data.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/schema.graphql
  libs/num/numeric.go
  protos/sources/vega/data/v1/data.proto
  protos/sources/vega/data/v1/spec.proto
  protos/sources/vega/governance.proto
  protos/sources/vega/markets.proto
  protos/vega/data/v1/data.pb.go
  protos/vega/data/v1/spec.pb.go
  protos/vega/governance.pb.go
  protos/vega/markets.pb.go
Labels: breaking-change

#7177 feat: add feature test for liquidity fee factors
  core/integration/features/verified/0042-LIQF-fees_rewards.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_rounding.feature
Labels: no-changelog, no-issue

#7201 chore: release version 0.65.1
  CHANGELOG.md
  core/events/market_data_test.go
  core/execution/market.go
  core/integration/features/accounts/2943-distressed-trader-has-general-balance.feature
  core/integration/features/fees/setting-fee-and-rewarding-lps.feature
  core/integration/features/fees/trading-fees-pdp.feature
  core/integration/features/verified/0035-LIQM-liquidity_monitoring.feature
  core/integration/features/verified/0042-LIQF-fees_rewards.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_rounding.feature
  core/liquidity/supplied/engine.go
  core/liquidity/supplied/engine_test.go
  core/liquidity/supplied/statevar.go
  core/liquidity/supplied/statevar_test.go
  core/processor/abci.go
  core/snapshot/engine.go
  datanode/dehistory/service_test.go
  datanode/entities/epoch.go
  datanode/entities/marketdata.go
  datanode/gateway/graphql/epoch_timestamps_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/market_data_resolvers.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/integration/epoch_test.go
  datanode/integration/testdata/golden/TestEpochs_CurrentEpoch
  datanode/integration/testdata/golden/TestEpochs_EpochDelegations
  datanode/integration/testdata/golden/TestEpochs_SpecificEpoch
  datanode/sqlstore/blocks_test.go
  datanode/sqlstore/epoch_test.go
  datanode/sqlstore/epochs.go
  datanode/sqlstore/market_data_test.go
  datanode/sqlstore/testdata/marketdata.csv
  datanode/sqlsubscribers/epoch.go
  go.mod
  go.sum
  protos/blockexplorer/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/sources/vega/vega.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  protos/vega/vega.pb.go
  version/version.go
Labels: no-changelog, no-issue

#7200 chore: round average liquidity score to 10dp
  core/liquidity/engine.go
  core/liquidity/engine_test.go
  core/liquidity/snapshot_test.go
Labels: no-changelog, no-issue

#6993 chore: add support for fgprof
  go.mod
  go.sum
  libs/pprof/pprof.go
Labels: no-changelog, no-issue

#6999 feat: create test to cover 0038-OLIQ-008
  core/integration/features/liquidity-provision/lp-margin-account-transfer-when-bestorder-change.feature
Labels: no-changelog

#7210 fix: trading terminated shouldn't unsubscribe unless in the right state
  core/execution/market.go
Labels: no-changelog, no-issue

#7038 Setup codeQL
  .github/workflows/codeql.yml
  core/api/rest/middleware.go
  core/faucet/service.go
  core/integration/steps/table_wrapper.go
  core/integration/steps/the_oracle_spec_settlement_decimals.go
  core/types/checkpoint.go
  datanode/dehistory/fsutil/fsutil.go
  datanode/gateway/middleware.go
  libs/crypto/hash.go
  libs/fmt/print.go
  libs/jsonrpc/api.go
  wallet/service/service_v2.go
Labels: no-changelog, no-issue

#7218 feat: Reorder lines in risk engine model update
  core/risk/engine.go
Labels: no-changelog, no-issue

#7215 fix: checkoint vegatools hash
  core/types/checkpoint.go
  vegatools/checkpoint/type.go
Labels: no-changelog, no-issue

#7224 feat: add order book checking
  core/integration/features/liquidity-provision/lp-distressed-closeout.feature
Labels: feature tests, no-changelog, no-issue
