Repository vegaprotocol/vega, pull requests merged in 2023-01, with the labels that each got.

#7128 chore: fix endpoint doc name
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog, no-issue

#7240 fix: when gap fill loading dehistory only attempt to load data more recent than the datanode contains
  cmd/data-node/commands/dehistory/load.go
  datanode/dehistory/initialise.go
  datanode/dehistory/initialise_test.go
  datanode/dehistory/mocks/dehistory_service_mock.go
  datanode/dehistory/service.go
  datanode/dehistory/service_test.go
Labels: no-changelog

#7244 feat: simplify dehistory autoinit
  cmd/data-node/commands/start/node_pre.go
  datanode/dehistory/initialise.go
  datanode/dehistory/initialise_test.go
  datanode/dehistory/service.go
  datanode/dehistory/service_test.go
  datanode/dehistory/store/config.go
  datanode/dehistory/store/store.go
Labels: no-changelog

#7222 fix: fix market triggering ratio value type
  CHANGELOG.md
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  core/events/market_event_test.go
  core/integration/steps/market/defaults/liquidity-monitoring/default-parameters.json
  core/integration/steps/market/defaults/liquidity-monitoring/default-tenth.json
  core/integration/steps/market/liquidity_monitoring.go
  core/integration/steps/the_liquidity_monitoring.go
  core/types/governance_new_market.go
  core/types/governance_proposal.go
  core/types/governance_update_market.go
  core/types/liquidity.go
  core/types/market.go
  core/types/market_test.go
  core/types/snapshot_nodes.go
  datanode/entities/market.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers_test.go
  datanode/gateway/graphql/schema.graphql
  datanode/integration/testdata/golden/TestMarkets_LiquidityMonitor
  datanode/sqlstore/markets_test.go
  protos/sources/vega/markets.proto
  protos/vega/markets.pb.go
  vegatools/checkpoint/type.go
Labels: breaking-change

#7259 feat: add metric to capture dehistory ipfs store size
  datanode/dehistory/store/store.go
  datanode/metrics/prometheus.go
Labels: no-changelog

#7175 chore: add SECURITY.md file
  SECURITY.md
Labels: no-changelog, no-issue

#7030 feat: add a type to node votes
  core/banking/asset_action.go
  core/governance/node_validation.go
  core/staking/accounting.go
  core/staking/stake_verifier.go
  core/types/witness.go
  core/validators/erc20multisig/topology.go
  core/validators/witness.go
  core/validators/witness_test.go
  protos/sources/vega/commands/v1/validator_commands.proto
  protos/vega/commands/v1/validator_commands.pb.go
Labels: no-changelog, no-issue

#7194 feat: only report new issues
  .golangci.toml
Labels: no-changelog

#7269 fix: wallet release pipeline
  .github/workflows/release-binaries.yml
Labels: no-changelog, no-issue

#7271 Release/v0.66.1
  .github/workflows/release-binaries.yml
  .golangci.toml
  CHANGELOG.md
  protos/blockexplorer/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#7273 feat: update version check in the docker release of wallet
  .github/workflows/release-docker-images.yml
Labels: wallet, no-changelog, no-issue

#7276 chore: update lp feature test AC tag after spec reshuffle
  core/integration/features/liquidity-provision/verify-CcySiska.feature
Labels: no-changelog, no-issue

#7278 chore: add wallet validation for one off to account type
  commands/transfer_funds.go
  commands/transfer_funds_test.go
Labels: no-changelog, no-issue

#7280 fix: only allow new txn if replay is finished and was successful
  core/blockchain/nullchain/nullchain.go
Labels: no-changelog, no-issue

#7296 feat: add test for AC 0003-MTMK-014
  core/integration/features/verified/Negative-Position-Decimal-Places.feature
Labels: feature tests

#7310 chore: replace float with decimal for determinism
  core/execution/fees.go
  core/spam/engine.go
  core/spam/vote_spam_policy.go
Labels: no-changelog, no-issue

#7320 fix: range for min withdrawal
  core/netparams/defaults.go
Labels: no-changelog, no-issue

#7321 feat: test for insurance pool balance transfer
  core/integration/features/verified/Funding-treasury.feature
Labels: no-changelog

#6326 chore: replace atomics with newer api
  core/api/core.go
  core/banking/asset_action.go
  core/banking/bridge_stop_resume.go
  core/banking/builtin_assets.go
  core/banking/engine.go
  core/banking/erc20.go
  core/banking/snapshot.go
  core/config/watcher.go
  core/governance/node_validation.go
  core/snapshot/engine.go
  core/validators/witness.go
  core/validators/witness_snapshot.go
  datanode/candlesv2/candle_updates.go
  datanode/config/watcher.go
  datanode/utils/observer.go
Labels: no-changelog, no-issue

#7312 chore: add dependency between number of validators and min number of …
  core/netparams/defaults.go
  core/netparams/netparams.go
  core/netparams/netparams_test.go
  core/netparams/values.go
Labels: no-changelog, no-issue

#7340 fix: when not increasing and within pow limit return base diff
  core/pow/engine.go
  core/pow/engine_test.go
Labels: no-changelog, no-issue

#7343 feat: add insurance pool check
  core/integration/features/verified/0002-STTL-settlement-verified-loss-socialization-case5.feature
Labels: no-changelog, no-issue

#7334 chore: add balances to ledger entries object
  CHANGELOG.md
  core/collateral/engine.go
  core/collateral/engine_test.go
  core/events/ledger_movements_test.go
  core/types/collateral.go
  datanode/entities/aggregated_ledgerentries.go
  datanode/entities/ledgerentry.go
  datanode/entities/ledgerentry_filter.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/modelext.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/sqlstore/ledger.go
  datanode/sqlstore/ledger_test.go
  datanode/sqlstore/ledgerentry_filter.go
  datanode/sqlstore/migrations/0001_initial.sql
  datanode/sqlsubscribers/ledger_movement.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: improvement

#7341 feat: network history should pre-allocate connections to use so it is resilient to db connection starvation
  cmd/data-node/commands/networkhistory/fetch.go
  cmd/data-node/commands/networkhistory/load.go
  cmd/data-node/commands/networkhistory/show.go
  cmd/data-node/commands/start/node_pre.go
  datanode/networkhistory/block_commit_handler.go
  datanode/networkhistory/initialise.go
  datanode/networkhistory/initialise_test.go
  datanode/networkhistory/mocks/networkhistory_service_mock.go
  datanode/networkhistory/service.go
  datanode/networkhistory/service_test.go
  datanode/networkhistory/snapshot/database_meta_data.go
  datanode/networkhistory/snapshot/service.go
  datanode/networkhistory/snapshot/service_create_snapshot.go
  datanode/networkhistory/snapshot/service_load_snapshot.go
  datanode/sqlstore/config.go
  datanode/sqlstore/connection_source.go
  datanode/sqlstore/sqlstore.go
Labels: no-changelog

#7348 Prepare code base for 0.67.0
  protos/blockexplorer/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#7025 chore: add csv export to ledger entries
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/gateway/graphql/mocks/mocks.go
  datanode/service/ledger.go
  datanode/sqlstore/accounts_test.go
  datanode/sqlstore/ledger.go
  datanode/sqlstore/ledger_test.go
  datanode/sqlstore/ledgerentry_filter.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: DatanodeV2

#7329 chore: remove unused fields in network limits
  core/limits/engine.go
  core/processor/abci.go
  datanode/entities/network_limits.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0001_initial.sql
  datanode/sqlstore/network_limits.go
  datanode/sqlstore/network_limits_test.go
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#7347 feat: add test for 0024-OSTA-012
  core/integration/features/verified/0026-AUCT-auction_interaction.feature
Labels: no-changelog, no-issue

#7370 fix: archive node should keep network history indefinitely
  cmd/data-node/commands/init.go
Labels: no-changelog

#7371 fix: added all spam policies to snapshot hash keys
  core/spam/engine.go
Labels: spam protection, bug, no-changelog, no-issue

#7377 Ensure the api.ConnectionsManager and *connections.Manager are in sync
  wallet/api/errors.go
  wallet/service/v2/api.go
  wallet/service/v2/connections/manager.go
Labels: wallet, no-changelog, no-issue

#7384 Ensure the state of the service starter is reset when stopped
  wallet/service/starter.go
Labels: no-changelog, no-issue

#7376 feat: system test specific flag to disable retention policy minimum checks
  datanode/sqlstore/config.go
  datanode/sqlstore/sqlstore.go
Labels: no-changelog

#7387 fix: add Access-Control-Expose-Headers to responses
  CHANGELOG.md
  wallet/service/v2/response_writer.go
Labels: bug, no-issue

#7389 Release/v0.67.2
  CHANGELOG.md
  datanode/sqlstore/config.go
  datanode/sqlstore/sqlstore.go
  protos/blockexplorer/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
  wallet/service/v2/response_writer.go
Labels: no-changelog, no-issue

#7392 fix: close down snapshot metadb in all cases
  core/snapshot/engine.go
Labels: no-changelog, no-issue

#7418 chore: add batch instructions to stats
  core/api/core.go
  core/broker/broker.go
  core/broker/broker_test.go
  core/processor/abci.go
  core/processor/batch_market_instructions_processor.go
  core/processor/batch_market_instructions_processor_test.go
  core/processor/mocks/mocks.go
  core/processor/processor.go
  core/processor/stats.go
  core/protocol/all_services.go
  core/stats/blockchain.go
  datanode/broker/broker_test.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/schema.graphql
  datanode/gateway/graphql/statistics.go
  protos/sources/vega/api/v1/core.proto
  protos/vega/api/v1/core.pb.go
Labels: no-changelog, no-issue

#7423 fix: clearFeeActivity now clears fee activity
  CHANGELOG.md
  core/execution/market_activity_tracker.go
Labels: no-issue

#7424 fix: reset event count on new block
  core/stats/blockchain.go
Labels: no-changelog, no-issue

#7404 account for existing data in migration
  CHANGELOG.md
  datanode/sqlstore/migrations/0002_pnl.sql
Labels: no-issue

#7430 fix: set nonce for joining and leaving signatures at the start of eac…
  CHANGELOG.md
  core/validators/mocks/mocks.go
  core/validators/signatures.go
  core/validators/topology.go
  core/validators/topology_eth_key_rotate_test.go
Labels: no-issue

#7435 Broadcast token file updates in a separate goroutine
  wallet/service/v2/connections/store/v1/file_store.go
  wallet/service/v2/connections/store/v1/file_store_test.go
Labels: no-changelog, no-issue

#7442 Change the test setup for token store file system updates
  wallet/service/v2/connections/store/v1/file_store_test.go
Labels: no-changelog, no-issue

#7441 fix: set nonce from restored snapshot time for when restoring right b…
  core/validators/topology_snapshot.go
  core/validators/topology_snapshot_test.go
Labels: no-changelog, no-issue

#7447 fix: intermittent termination error when integation tests are finished
  cmd/data-node/commands/start/node.go
Labels: DatanodeV2, no-changelog, no-issue

#7446 Give up on the flaky token store test
  wallet/service/v2/connections/store/v1/file_store_test.go
Labels: no-changelog, no-issue

#7457 feat: remove AC 0038-OLIQ-009
  core/integration/features/liquidity-provision/lp-margin-account-transfer-when-bestorder-change.feature
Labels: tests, no-changelog

#7463 Network history load and current order set tracking
  CHANGELOG.md
  cmd/data-node/commands/networkhistory/load.go
  cmd/data-node/commands/networkhistory/networkhistory.go
  cmd/data-node/commands/networkhistory/show.go
  datanode/admin/dehistory.go
  datanode/api/mocks/networkhistory_service_mock.go
  datanode/api/server.go
  datanode/api/trading_data_v2.go
  datanode/docs/schema_design_principles.md
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/aggregation/aggregation.go
  datanode/networkhistory/aggregation/aggregation_test.go
  datanode/networkhistory/contiguous_history.go
  datanode/networkhistory/contiguous_history_test.go
  datanode/networkhistory/fsutil/fsutil.go
  datanode/networkhistory/initialise.go
  datanode/networkhistory/initialise_test.go
  datanode/networkhistory/mocks/networkhistory_service_mock.go
  datanode/networkhistory/service.go
  datanode/networkhistory/service_test.go
  datanode/networkhistory/snapshot/orders/restore_current_orders_set.go
  datanode/networkhistory/snapshot/orders/restore_current_orders_set_test.go
  datanode/networkhistory/snapshot/orders/update_current_orders.go
  datanode/networkhistory/snapshot/service.go
  datanode/networkhistory/snapshot/service_load_snapshot.go
  datanode/networkhistory/store/store.go
  datanode/networkhistory/store/store_test.go
  datanode/service/market.go
  datanode/sqlstore/migrations/0001_initial.sql
  datanode/sqlstore/orders.go
  datanode/sqlstore/orders_test.go
  datanode/sqlstore/sqlstore.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: breaking-change

#7467 chore: add documentations notice with the current type of strings and how to scale them with decimal places
  protos/sources/vega/chain_events.proto
  protos/sources/vega/commands/v1/commands.proto
  protos/sources/vega/vega.proto
  protos/vega/chain_events.pb.go
  protos/vega/commands/v1/commands.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue
