Repository vegaprotocol/vega, pull requests merged in 2023-07, with the labels that each got.

#8658 Add tests on snasphot databases
  core/snapshot/databases/metadata/database.go
  core/snapshot/databases/metadata/database_test.go
  core/snapshot/databases/metadata/in_memory.go
  core/snapshot/databases/metadata/level_db.go
  core/snapshot/databases/snapshot/in_memory.go
  core/snapshot/databases/snapshot/in_memory_test.go
  core/snapshot/databases/snapshot/level_db.go
  core/snapshot/databases/snapshot/level_db_test.go
  core/snapshot/engine.go
Labels: no-changelog, no-issue

#8684 update cosmos/iavl to 0.20.0
  cmd/vegatools/snapshot.go
  core/snapshot/databases/snapshot/in_memory.go
  core/snapshot/databases/snapshot/level_db.go
  core/snapshot/engine.go
  core/snapshot/engine_test.go
  core/snapshot/snapshots.go
  core/types/snapshot.go
  core/types/snapshot_nodes_test.go
  go.mod
  go.sum
  vegatools/snapshotdb/snapshotdb.go
Labels: no-changelog

#8700 fix: stop orders expiring in auction cause panic
  CHANGELOG.md
  core/execution/future/market.go
  core/integration/features/orders/stoporders.feature
Labels: feature tests

#8715 chore: changes some eth call oracle proto types
  commands/proposal_submission.go
  core/types/data_source_external_eth_oracle.go
  core/types/data_source_external_eth_oracle_test.go
  core/types/data_source_test.go
  datanode/entities/data_source_definition.go
  datanode/entities/data_source_definition_test.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/resolvers_test.go
  protos/sources/vega/data_source.proto
  protos/vega/data_source.pb.go
  protos/vega/spec_definition.go
  protos/vega/spec_definition_test.go
Labels: no-changelog, no-issue

#8717 chore: release patch 0.72.1
  CHANGELOG.md
  cmd/vegawallet/commands/service_run.go
  core/collateral/engine.go
  core/collateral/engine_test.go
  datanode/networkhistory/service_test.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/migrations/0003_successor_markets.sql
  datanode/sqlstore/migrations/0010_stop_orders.sql
  protos/blockexplorer/api/v1/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/api/v1/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#8708 feat: feature tests for successor markets
  core/integration/features/verified/0081-SUCM-multiple_successor_markets.feature
  core/integration/steps/the_markets.go
Labels: feature tests, no-changelog

#8733 chore: sla interface cleanup
  core/execution/common/interfaces.go
  core/execution/common/liquidity_provision.go
  core/execution/common/mocks/mocks.go
  core/liquidity/supplied/engine.go
  core/liquidity/v2/amendments.go
  core/liquidity/v2/amendments_test.go
  core/liquidity/v2/engine.go
  core/liquidity/v2/engine_test.go
  core/liquidity/v2/scores_test.go
  core/liquidity/v2/sla.go
  core/liquidity/v2/sla_test.go
  core/liquidity/v2/types.go
Labels: no-changelog, no-issue

#8736 feat: check order cancellation in successor market
  core/integration/features/successor-markets-ELS.feature
  core/integration/features/verified/Funding-treasury.feature
Labels: feature tests, bug, no-changelog, no-issue

#8795 fix: token permissions and versions on PM actions
  .github/workflows/add_issue_to_project.yml
  .github/workflows/conventional_commits.yml
  .github/workflows/project_management.yml
Labels: ci, no-changelog, no-issue

#8805 fix: eth call spec not deactivating after market settles
  core/datasource/external/ethcall/engine.go
  core/datasource/external/ethcall/engine_test.go
Labels: no-changelog

#8807 fix: normalise should handle bool values
  core/datasource/external/ethcall/call_test.go
  core/datasource/external/ethcall/result.go
Labels: no-changelog

#8812 fix: tests + clean
  core/datasource/common/data_test.go
  core/datasource/common/spec_test.go
  core/datasource/definition/definition_test.go
Labels: no-changelog, ethereum-oracles

#8819 Adjust the verification on the loaded snapshot to reflect new configuration constraints
  core/snapshot/engine.go
Labels: no-changelog, no-issue

#8822 fix: allow creation of LP commitment in feature tests
  core/integration/features/spots/pegged-orders.feature
  core/integration/steps/parties_submit_liquidity_provision.go
Labels: no-changelog, no-issue

#8825 chore: run go mod tidy
  go.sum
Labels: no-changelog, no-issue

#8834 fix: stop dead lock in candle notional migration script
  datanode/sqlstore/migrations/0012_candles_add_notional.sql
Labels: no-changelog

#8831 chore: allow updating of spot markets in feature tests
  core/integration/features/verified/0080-Spot.feature
  core/integration/main_test.go
  core/integration/steps/the_spot_markets.go
Labels: no-changelog, no-issue

#8858 fix: avoid duplicate events and set market to closed
  core/execution/spot/market.go
Labels: no-changelog, no-issue

#8870 fix: oracle_spec table null data error
  CHANGELOG.md
  datanode/sqlstore/migrations/0004_oracle_specs.sql
Labels: oracles, bug, datanode

#8873 fix: misc lp fixes
  core/execution/spot/liquidity_provision.go
  core/integration/features/spot/liquidity_provision/0044-LIME_spot_LPorders.feature
  core/integration/steps/parties_submit_liquidity_provision.go
  core/liquidity/v2/engine.go
Labels: no-changelog, no-issue

#8886 fix: call liquidity onTick and use correct els instance
  core/execution/spot/market.go
Labels: no-changelog, no-issue

#8889 Remove hard-coded time in proposal test
  .golangci.toml
  commands/announce_node_test.go
  core/assets/snapshot_test.go
  core/banking/cancel_transfer_test.go
  core/banking/checkpoint_test.go
  core/banking/engine_test.go
  core/banking/gov_transfers_test.go
  core/banking/oneoff_transfers_test.go
  core/banking/recurring_transfers_test.go
  core/banking/snapshot_test.go
  core/banking/transfer_common_test.go
  core/broker/broker_test.go
  core/checkpoint/engine_test.go
  core/collateral/checkpoint_test.go
  core/execution/future/equity_share_test.go
  core/execution/future/event_generation_test.go
  core/execution/future/liquidity_provision_test.go
  core/execution/future/margin_test.go
  core/execution/future/market_test.go
  core/execution/future/order_test.go
  core/governance/checkpoint_test.go
  core/governance/engine_freeform_test.go
  core/governance/engine_new_asset_test.go
  core/governance/engine_new_market_test.go
  core/governance/engine_new_net_param_test.go
  core/governance/engine_new_spot_market_test.go
  core/governance/engine_test.go
  core/governance/engine_update_market_state_test.go
  core/governance/engine_update_market_test.go
  core/governance/engine_update_spot_market_test.go
  core/governance/snapshot_test.go
  core/matching/orderbook_test.go
  core/monitor/price/snapshot_test.go
  core/positions/positions_acceptance_criteria_test.go
  core/risk/engine_test.go
  core/settlement/engine_test.go
  datanode/api/trading_test.go
  datanode/entities/reward_test.go
  datanode/sqlstore/market_data_test.go
  libs/num/int_test.go
  protos/vega/data_source.go
Labels: no-changelog, no-issue

#8888 chore: wire liquidity v2 net params in integration tests
  core/integration/setup_test.go
Labels: no-changelog, no-issue

#8904 Fix/sla datanode fixes for market proposals
  datanode/entities/market.go
  datanode/networkhistory/service_test.go
  datanode/sqlstore/markets.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/migrations/0023_market_liquidity_sla_parameters.sql
Labels: datanode, no-changelog, no-issue, liquidity-sla

#8922 fix: Better error message if we fail to unlock the token store
  cmd/vegawallet/commands/api_token_delete.go
  cmd/vegawallet/commands/api_token_describe.go
  cmd/vegawallet/commands/api_token_generate.go
  cmd/vegawallet/commands/api_token_init.go
  cmd/vegawallet/commands/api_token_init_test.go
  cmd/vegawallet/commands/api_token_list.go
  cmd/vegawallet/commands/service_run.go
  wallet/api/errors.go
  wallet/service/v2/connections/store/longliving/v1/errors.go
  wallet/service/v2/connections/store/longliving/v1/file_store.go
Labels: no-changelog, no-issue

#8923 Set the reception date earlier in the wallet API to account for verification time
  wallet/api/admin_check_transaction.go
  wallet/api/admin_send_raw_transaction.go
  wallet/api/admin_send_transaction.go
  wallet/api/client_check_transaction.go
  wallet/api/client_send_transaction.go
  wallet/api/client_sign_transaction.go
Labels: no-changelog, no-issue

#8905 fix: add some tests for eth oracles in sql
  datanode/sqlstore/oracle_spec_test.go
Labels: no-changelog, no-issue
