Repository vegaprotocol/vega, pull requests merged in 2023-06, with the labels that each got.

#8346 fix: fix internal ds listing
  CHANGELOG.md
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  core/types/data_signer.go
  core/types/data_signer_test.go
  core/types/data_source.go
  core/types/data_source_test.go
  core/types/oracles.go
  datanode/entities/data.go
  datanode/entities/data_source.go
  datanode/entities/data_source_definition.go
  datanode/entities/data_source_definition_test.go
  datanode/entities/data_source_spec.go
  datanode/entities/data_source_spec_test.go
  datanode/entities/data_spec.go
  datanode/entities/oracle_spec.go
  datanode/entities/tradable_instrument.go
  datanode/gateway/graphql/data_source_resolver.go
  datanode/gateway/graphql/future_product_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/oracles_resolver.go
  datanode/gateway/graphql/oracles_resolver_test.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/resolvers_test.go
  datanode/gateway/graphql/update_future_resolver.go
  datanode/integration/oracles_test.go
  datanode/integration/testdata/golden/TestOracles_OracleDataConnectionExternal
  datanode/integration/testdata/golden/TestOracles_OracleDataConnectionInternal
  datanode/integration/testdata/golden/TestOracles_OracleDataSourceExternal
  datanode/integration/testdata/golden/TestOracles_OracleDataSourceInternal
  datanode/networkhistory/service_test.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/migrations/0004_oracle_specs.sql
  datanode/sqlstore/oracle_spec.go
  datanode/sqlstore/oracle_spec_test.go
  datanode/sqlsubscribers/market_created_test.go
  datanode/sqlsubscribers/market_updated_test.go
  datanode/sqlsubscribers/oracle_spec.go
  protos/vega/data_source.go
  protos/vega/spec_definition.go
  protos/vega/spec_definition_test.go
Labels: oracles, bug

#8387 feat: ethereum oracles query verifier
  core/evtforward/ethcall/engine_test.go
  core/evtforward/ethcall/filter.go
  core/evtforward/ethcall/normaliser.go
  core/evtforward/ethcall/spec.go
  core/evtforward/ethcall/spec_test.go
  core/oracles/ethereum_oracle_verifier.go
  core/oracles/ethereum_oracle_verifier_snapshot.go
  core/oracles/ethereum_oracle_verifier_snapshot_test.go
  core/oracles/ethereum_oracle_verifier_test.go
  core/oracles/mocks/eth_call_spec_mock.go
  core/oracles/mocks/eth_call_spec_source_mock.go
  core/oracles/mocks/eth_confirmations_mock.go
  core/oracles/mocks/eth_contract_caller.go
  core/oracles/mocks/oracle_data_broadcaster_mock.go
  core/oracles/mocks/witness_mock.go
  core/processor/process_chain_event.go
  core/processor/processor.go
  core/protocol/all_services.go
  core/protocol/protocol.go
  core/types/oracles.go
  core/types/snapshot.go
  core/types/snapshot_nodes.go
  core/types/witness.go
  protos/sources/vega/commands/v1/validator_commands.proto
  protos/sources/vega/data_source.proto
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/commands/v1/validator_commands.pb.go
  protos/vega/data_source.pb.go
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog, no-issue

#8437 Optimise ci times
  .github/workflows/release-docker-images.yml
  Jenkinsfile
Labels: no-changelog

#8441 Eth oracles gov
  core/evtforward/ethcall/engine.go
  core/evtforward/ethcall/filter.go
  core/evtforward/ethcall/normaliser.go
  core/evtforward/ethcall/spec.go
  core/evtforward/ethcall/trigger.go
  core/evtforward/ethcall/trigger_test.go
  core/oracles/adaptors/adaptors.go
  core/oracles/adaptors/ethereum.go
  core/types/data.go
  core/types/data_source_external.go
  core/types/data_source_external_eth_oracle.go
  core/types/data_source_external_eth_oracle_test.go
  core/types/data_source_external_oracle.go
  core/types/ethereum_oracle_filter.go
  core/types/ethereum_oracle_filter_test.go
  core/types/ethereum_oracle_normaliser.go
  core/types/ethereum_oracle_normaliser_test.go
  core/types/ethereum_oracle_trigger.go
  core/types/ethereum_oracle_trigger_test.go
  protos/sources/vega/commands/v1/data.proto
  protos/sources/vega/data_source.proto
  protos/vega/commands/v1/data.pb.go
  protos/vega/data_source.pb.go
Labels: governance, no-changelog, no-issue, ethereum-oracles

#8443 chore: fix outdated docs
  core/docs/problem_diagnosis.md
Labels: no-changelog, no-issue, not-a-bug

#8463 oracle ethereum verifier cleanup
  core/evtforward/ethcall/call.go
  core/evtforward/ethcall/call_test.go
  core/evtforward/ethcall/datasource.go
  core/evtforward/ethcall/engine.go
  core/evtforward/ethcall/engine_test.go
  core/evtforward/ethcall/mocks/datasource_mock.go
  core/oracles/ethereum_oracle_verifier.go
  core/oracles/ethereum_oracle_verifier_snapshot_test.go
  core/oracles/ethereum_oracle_verifier_test.go
  core/oracles/mocks/eth_call_mock.go
  core/oracles/mocks/eth_call_spec_mock.go
  core/oracles/mocks/eth_call_spec_source_mock.go
  core/protocol/all_services.go
  core/types/data_source_test.go
Labels: no-changelog, no-issue, ethereum-oracles

#8445 Iceberg orders integration tests
  CHANGELOG.md
  core/integration/features/orders/iceberg-orders.feature
Labels: no-issue, orders

#8481 Eth oracles gov clean
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  core/events/oracle_spec_test.go
  core/execution/engine_snapshot_test.go
  core/execution/future/market_test.go
  core/execution/snapshot_test.go
  core/governance/engine_new_market_test.go
  core/governance/engine_test.go
  core/governance/engine_update_market_test.go
  core/governance/market.go
  core/integration/steps/the_markets.go
  core/integration/steps/the_oracle_spec.go
  core/markets/instrument_test.go
  core/oracles/engine_test.go
  core/oracles/oracle_spec_test.go
  core/products/future_test.go
  core/products/products_test.go
  core/types/data.go
  core/types/data_source.go
  core/types/data_source_external.go
  core/types/data_source_external_eth_oracle.go
  core/types/data_source_external_eth_oracle_test.go
  core/types/data_source_external_oracle.go
  core/types/data_source_external_oracle_test.go
  core/types/data_source_internal.go
  core/types/data_source_internal_time_test.go
  core/types/data_source_internal_tme.go
  core/types/data_source_test.go
  core/types/governance_new_market.go
  core/types/governance_update_market.go
  core/types/market_test.go
  core/types/snapshot_nodes_test.go
  datanode/entities/data_source_definition_test.go
  datanode/entities/data_source_spec_test.go
  datanode/gateway/graphql/resolvers_test.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/oracle_spec_test.go
  datanode/sqlsubscribers/market_created_test.go
  protos/vega/data_source_test.go
  protos/vega/spec_definition.go
  protos/vega/spec_definition_test.go
Labels: no-changelog, ethereum-oracles

#8457 chore: sync docstrings about icebergs with the truth
  datanode/gateway/graphql/schema.graphql
  protos/sources/vega/commands/v1/commands.proto
  protos/sources/vega/vega.proto
  protos/vega/commands/v1/commands.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#8483 feat: test when FOK market order unable to trade
  core/integration/features/orders/FOK_order_stopped.feature
Labels: no-changelog, no-issue, not-a-bug

#8503 feat: ethereum oracles - handle non validator setup
  core/oracles/ethereum_oracle_verifier.go
  core/oracles/ethereum_oracle_verifier_snapshot_test.go
  core/oracles/ethereum_oracle_verifier_test.go
  core/oracles/mocks/ethcallengine_mock.go
  core/protocol/all_services.go
Labels: no-changelog, no-issue, ethereum-oracles

#8521 feat: add iceberg execution tests
  core/integration/features/orders/iceberg-orders.feature
Labels: feature tests, no-changelog, no-issue

#8485 fix: misleading changelog entry
  CHANGELOG.md
Labels: no-issue

#8531 feat: ethereum oracles - updates required to run end to end system tests
  commands/errors.go
  commands/proposal_submission.go
  core/evtforward/ethcall/call.go
  core/evtforward/ethcall/call_test.go
  core/evtforward/ethcall/engine.go
  core/evtforward/ethcall/engine_test.go
  core/evtforward/ethcall/result.go
  core/execution/future/market_test.go
  core/execution/snapshot_test.go
  core/integration/setup_test.go
  core/markets/instrument_test.go
  core/oracles/engine.go
  core/oracles/engine_test.go
  core/oracles/ethereum_oracle_verifier.go
  core/protocol/all_services.go
  core/types/data_source_external_eth_oracle.go
Labels: no-changelog, no-issue

#8499 feat: add release process markdown file
  .github/release.yml
  .spelling
  RELEASE_PROCESS.md
Labels: no-changelog, no-issue

#8538 feat: iceberg feature tests
  core/integration/features/orders/iceberg-orders.feature
  core/integration/main_test.go
  core/integration/steps/parties_place_the_following_pegged_iceberg_orders.go
Labels: feature tests, no-changelog, no-issue

#8546 fix: update pgp pubkey in security file
  SECURITY.md
Labels: no-changelog, no-issue, not-a-bug

#8530 feat: add ft and lable AC
  core/integration/features/successor-markets-ELS.feature
  core/integration/features/successor-markets-expiration.feature
  core/integration/features/successor-markets-simple.feature
Labels: no-changelog, no-issue

#8553 feat: ethereum oracles error handling
  core/evtforward/ethcall/engine.go
  core/evtforward/ethcall/engine_test.go
  core/evtforward/ethcall/result.go
  core/oracles/ethereum_oracle_verifier.go
  core/oracles/ethereum_oracle_verifier_test.go
  core/protocol/all_services.go
  core/types/oracles.go
  datanode/entities/data.go
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0005_oracle_data.sql
  datanode/sqlstore/oracle_data.go
  datanode/sqlstore/oracle_data_test.go
  protos/sources/vega/chain_events.proto
  protos/sources/vega/data/v1/data.proto
  protos/vega/chain_events.pb.go
  protos/vega/data/v1/data.pb.go
  protos/vega/data_source.go
  protos/vega/spec_definition.go
  protos/vega/spec_definition_test.go
Labels: no-changelog, no-issue, ethereum-oracles

#8575 feat: add stop orders command to the wallet
  protos/sources/vega/wallet/v1/wallet.proto
  protos/vega/wallet/v1/wallet.pb.go
  wallet/commands/commands.go
Labels: no-changelog, no-issue

#8579 feat: persist last processed eth block
  core/evtforward/ethcall/engine.go
  core/oracles/ethereum_oracle_verifier.go
  core/oracles/ethereum_oracle_verifier_snapshot.go
  core/oracles/ethereum_oracle_verifier_snapshot_test.go
  core/oracles/mocks/ethcall_result.go
  core/oracles/mocks/ethcallengine_mock.go
  core/protocol/all_services.go
  core/types/oracles.go
  core/types/snapshot_nodes.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog

#8560 chore: add batch instructions to feature tests
  core/integration/execution_test.go
  core/integration/features/orders/batch-orders.feature
  core/integration/main_test.go
  core/integration/steps/execution.go
  core/integration/steps/parties_place_the_following_iceberg_orders.go
  core/integration/steps/parties_place_the_following_orders.go
  core/processor/abci.go
  core/processor/batch_market_instructions_processor.go
  core/processor/batch_market_instructions_processor_test.go
Labels: no-changelog, no-issue, iceberg-orders

#7743 feat: add verify signatures (list_asset/set_asset_limits)
  cmd/vega/commands/bridge/erc20.go
  core/bridges/erc20_logic.go
  libs/crypto/signature/signature.go
Labels: no-changelog, no-issue

#8392 bug: datanode doc link updates
  datanode/README.md
Labels: no-changelog

#8488 Improve wording for field descriptions
  visor/builddocs.sh
  visor/config/run_config.go
  visor/config/visor_config.go
  visor/run-config.md
  visor/visor-config.md
Labels: no-changelog

#8595 feat: ethereum oracle error handling refactor
  core/evtforward/ethcall/engine.go
  core/oracles/ethereum_oracle_verifier.go
  core/oracles/ethereum_oracle_verifier_test.go
Labels: no-changelog, ethereum-oracles

#8628 Use vega home to locate snapshot databases
  core/snapshot/config.go
  core/snapshot/databases/metadata/database.go
  core/snapshot/databases/metadata/in_memory.go
  core/snapshot/databases/metadata/level_db.go
  core/snapshot/databases/snapshot/in_memory.go
  core/snapshot/databases/snapshot/level_db.go
  core/snapshot/engine.go
  core/snapshot/engine_test.go
  core/snapshot/meta_db.go
  paths/doc.go
  paths/paths.go
Labels: no-changelog, no-issue

#8639 chore: add README for how-to-snapshot
  core/snapshot/README.md
Labels: no-changelog

#8615 feat: error handling on eth oracle spec parsing
  Makefile
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  core/evtforward/config.go
  core/execution/future/market_snapshot_test.go
  core/oracles/adaptors/adaptors.go
  core/oracles/ethereum_oracle_verifier.go
  core/types/data_source_external.go
  core/types/data_source_internal.go
  core/types/data_source_test.go
  core/types/ethereum_oracle_normaliser.go
  core/types/governance_new_market.go
  core/types/governance_new_spot_market.go
  core/types/governance_update_market.go
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0011_oracle_data.sql
  protos/sources/vega/data_source.proto
  protos/vega/data_source.pb.go
Labels: no-changelog, no-issue

#8650 fix: delete the correct folder when clearing up
  core/snapshot/databases/metadata/level_db.go
  core/snapshot/databases/snapshot/level_db.go
Labels: no-changelog, no-issue
