Repository vegaprotocol/vega, pull requests merged in 2023-03, with the labels that each got.

#7705 fix: accept bultin datasource with no signers
  CHANGELOG.md
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  core/integration/steps/the_markets.go
  core/oracles/oracle_spec.go
  core/oracles/oracle_spec_test.go
  core/types/data.go
  core/types/data_source.go
Labels: oracles, bug

#7699 fix: update position_tracking tests
  core/integration/features/position_tracking/verified-positions-resolution-5-lognormal.feature
  core/integration/features/position_tracking/verified-positions-resolution-5-lognormal_pdp.feature
Labels: feature tests, no-changelog, no-issue

#7708 fix: update price_monitoring tests
  core/integration/features/price_monitoring/2668-price-monitoring.feature
  core/integration/features/price_monitoring/2681-price-monitoring.feature
  core/integration/features/price_monitoring/price-monitoring-for-system-test.feature
  core/integration/features/price_monitoring/price-monitoring-lognormal2.feature
Labels: feature tests, no-changelog, no-issue

#7709 fix: update closeouts tests
  core/integration/features/closeouts/1847-closeout-short-with-fees.feature
  core/integration/features/closeouts/network-order-and-trades-sub.feature
Labels: feature tests, no-changelog, no-issue

#7700 test: rebase tests
  core/integration/features/auctions/2952-opening-auction-extension-csv.feature
  core/integration/features/auctions/5460-market-order-cannot-trade-due-to-auction.feature
  core/integration/features/liquidity-provision/bug-5110.feature
  core/integration/features/liquidity-provision/bug-5147.feature
  core/integration/features/liquidity-provision/lp-distressed-closeout-pdp.feature
  core/integration/features/liquidity-provision/lp-distressed-closeout.feature
  core/integration/features/liquidity-provision/verify-CcySiska.feature
Labels: no-changelog, no-issue

#7739 fix: spelling errors in error responses
  core/evtforward/ethereum/filterer.go
Labels: no-changelog, no-issue

#7752 Docs: update type_commit message
  protos/sources/vega/api/v1/core.proto
  protos/vega/api/v1/core.pb.go
Labels: no-changelog, no-issue

#7754 Feature/ipfs version stuff
  CHANGELOG.md
  core/contracts/erc20/erc20.go
  core/contracts/erc20_bridge_logic_restricted/erc20_bridge_logic_restricted.go
  core/contracts/multisig_control/multisig_control.go
  datanode/networkhistory/store/config.go
  datanode/networkhistory/store/store.go
  go.mod
  go.sum
Labels: no-changelog, no-issue

#7733 fix: in amend, use existing order to find order in book
  CHANGELOG.md
  core/execution/market.go
Labels: bug, orders

#7756 Adjust wallet interactions to better fit front-end integration
  wallet/api/client_connect_wallet.go
  wallet/api/client_connect_wallet_test.go
  wallet/api/client_list_keys_test.go
  wallet/api/client_send_transaction_test.go
  wallet/api/client_sign_transaction_test.go
  wallet/api/errors.go
  wallet/api/interactor/interaction.go
  wallet/api/interactor/sequential.go
Labels: no-changelog, no-issue

#7518 feat: add visor autoinstall pipeline for vega PRs pipeline
  Jenkinsfile
Labels: no-changelog

#7773 fix: handle external datasource with settlement data
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  core/oracles/oracle_spec.go
  core/oracles/oracle_spec_test.go
  core/types/data.go
Labels: no-changelog

#7788 feat: update release repository for pup and visor auto install releases
  Jenkinsfile
Labels: no-changelog, no-issue

#7644 feat: create a suicidal trade
  core/integration/features/verified/Funding-insurance_pool.feature
Labels: feature tests, no-changelog, no-issue

#7795 fix: nullblockchain replay file with long lines can be read
  core/blockchain/nullchain/replay.go
Labels: no-changelog, no-issue

#7672 feat: update probability range in Price Monitoring
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
Labels: no-changelog, no-issue

#7777 feat: add tests for new ACs in 0042
  core/integration/features/fees/setting-fee-and-rewarding-lps.feature
Labels: feature tests, no-changelog

#7793 feat: park lp orders when not on book
  core/execution/amend_lp_orders_test.go
  core/execution/liquidity_provision_test.go
  core/execution/special_orders.go
  core/liquidity/engine.go
  core/types/matching.go
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#7801 `client.connect_wallet` example in documentation
  wallet/api/openrpc.json
Labels: no-changelog, no-issue

#7807 fix: add key for internal time sources
  core/types/data_source.go
  core/types/data_source_internal_tme.go
  core/types/data_source_test.go
Labels: no-changelog, no-issue

#7812 fix: ensure netparams checkpoint restore is deterministic and doesn't run validation
  core/netparams/netparams.go
Labels: no-changelog, no-issue

#7839 fix: avoid panic for malformed withdrawal
  core/processor/process_withdraw.go
Labels: no-changelog, no-issue

#7838 7816 require slippage factors
  CHANGELOG.md
  core/integration/features/closeouts/position-resolution-after-auction.feature
  core/integration/features/price_monitoring/price-monitoring-bounds.feature
  core/integration/features/verified/0015-INSR-insurance_pool_balance_test.feature
  core/integration/features/verified/0026-AUCT-auction_interaction.feature
  core/integration/features/verified/0034-PROB-liquidity_TauScaling.feature
  core/integration/features/verified/0041-TSK-target_stake.feature
  core/integration/features/verified/liquidity-provision-bond-account.feature
  core/integration/features/verified/risk-parameters-ranges-test.feature
  core/integration/features/verified/risk-parameters-sigma-test.feature
  core/integration/steps/the_markets.go
  core/risk/engine_test.go
  core/types/governance_new_market.go
  core/types/governance_update_market.go
Labels: breaking-change

#7833 feat: tidy up position and margin ACs
  core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case1.feature
  core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case2.feature
  core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case3.feature
  core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case4.feature
  core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case5.feature
  core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case6.feature
  core/integration/features/verified/closeout-lognormal.feature
Labels: feature tests, no-changelog

#7837 fix: add tests for external termination in commands
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
Labels: oracles, no-changelog, no-issue

#7853 fix: network history load error handling
  datanode/networkhistory/snapshot/service_load_snapshot.go
Labels: no-changelog, no-issue

#7855 Support TLS in wallet gRPC client
  CHANGELOG.md
  wallet/api/node/adapters/adapters.go
  wallet/api/node/adapters/grpc_adapter.go
  wallet/api/node/retrying_node.go
Labels: no-changelog

#7857 fix: fix nil pointer handling in ds
  core/oracles/oracle_spec.go
  core/types/data_source.go
Labels: bug, no-changelog, no-issue

#7850 fix: client.check_transactionCLI client interaction
  cmd/vegawallet/commands/service_run.go
Labels: no-changelog, no-issue

#7858 fix: paths fix
  datanode/networkhistory/snapshot/service.go
  datanode/networkhistory/snapshot/service_create_snapshot.go
  datanode/networkhistory/snapshot/service_load_snapshot.go
Labels: no-changelog

#7861 chore: ensure time_iota_ms is setup properly in genesis with vega verify gensis command
  cmd/vega/verify/genesis.go
  cmd/vega/verify/genesis_test.go
Labels: no-changelog, no-issue

#7841 fix: ensure the reference len are checked
  commands/liquidity_provision_submission.go
  commands/order_submission.go
Labels: no-changelog, no-issue

#7832 fix: add live liquidity provisions table
  CHANGELOG.md
  core/liquidity/engine.go
  datanode/api/trading_data_v2.go
  datanode/integration/testdata/golden/TestMarkets
  datanode/integration/testdata/golden/TestMarkets_LiquidityProvisions
  datanode/networkhistory/service_test.go
  datanode/sqlstore/liquidity_provision.go
  datanode/sqlstore/liquidity_provision_test.go
  datanode/sqlstore/migrations/0012_live_liquidity_provisions.sql
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: discussion

#7884 fix: use nanoseconds for one off transfer deliver on
  CHANGELOG.md
  core/banking/checkpoint.go
  core/types/banking.go
  datanode/entities/transfer.go
  datanode/sqlstore/transfers_test.go
  protos/sources/vega/commands/v1/commands.proto
  protos/vega/commands/v1/commands.pb.go
Labels: breaking-change

#7892 fix: fix changelog for issue 7326
  CHANGELOG.md
Labels: no-changelog, no-issue

#7890 feat: use cached genesis with the tendermint LocalClient as well.
  core/blockchain/abci/client.go
  core/blockchain/abci/local_client.go
Labels: no-changelog, no-issue

#7909 fix: add missing graphql details for liq prov list
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/market_resolvers.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
Labels: breaking-change, no-changelog, no-issue

#7925 feat: implement specific marshaller for the websockets subscribtion to improve payload sizes
  datanode/gateway/rest/server.go
Labels: no-changelog, no-issue, not-a-bug

#7929 feat: create FT to replicate ST
  core/integration/features/system-test-default.feature
Labels: feature tests, no-changelog, no-issue

#7868 feat: reduce default event buffer size
  datanode/broker/config.go
Labels: no-changelog

#7972 Make sure the wallet files watcher is running only when useful
  cmd/vegawallet/commands/api_token_generate.go
  cmd/vegawallet/commands/cmd.go
  cmd/vegawallet/commands/init.go
  cmd/vegawallet/commands/key_annotate.go
  cmd/vegawallet/commands/key_describe.go
  cmd/vegawallet/commands/key_generate.go
  cmd/vegawallet/commands/key_isolate.go
  cmd/vegawallet/commands/key_list.go
  cmd/vegawallet/commands/key_rotate.go
  cmd/vegawallet/commands/key_taint.go
  cmd/vegawallet/commands/key_untaint.go
  cmd/vegawallet/commands/message_sign.go
  cmd/vegawallet/commands/passphrase_update.go
  cmd/vegawallet/commands/permissions_describe.go
  cmd/vegawallet/commands/permissions_list.go
  cmd/vegawallet/commands/permissions_purge.go
  cmd/vegawallet/commands/permissions_revoke.go
  cmd/vegawallet/commands/service_run.go
  cmd/vegawallet/commands/transaction_check.go
  cmd/vegawallet/commands/transaction_send.go
  cmd/vegawallet/commands/transaction_sign.go
  cmd/vegawallet/commands/wallet_create.go
  cmd/vegawallet/commands/wallet_delete.go
  cmd/vegawallet/commands/wallet_describe.go
  cmd/vegawallet/commands/wallet_import.go
  cmd/vegawallet/commands/wallet_list.go
  cmd/vegawallet/commands/wallet_rename.go
  core/examples/nullchain/wallet.go
  core/faucet/wallet.go
  core/nodewallets/vega/loader.go
  wallet/wallet/store/v1/file_store.go
  wallet/wallet/store/v1/file_store_test.go
  wallet/wallets/store.go
Labels: no-changelog, no-issue

#7907 feat: create ft to amend GTT order
  core/integration/features/orders/trader_amends_his_orders.feature
  core/integration/main_test.go
  core/integration/steps/parties_place_the_following_orders.go
  core/integration/stubs/broker_stub.go
Labels: feature tests, no-changelog

#8014 chore: Update CODEOWNERS for API docs reviews
  CODEOWNERS
Labels: no-changelog, no-issue

#8027 Feature/rollback some changes in the evtforwarder
  core/evtforward/ethereum/engine.go
Labels: no-changelog, no-issue

#7813 feat: add slippage feature test
  core/integration/features/verified/0019-MCAL-margin_calculator-slippage.feature
Labels: feature tests, no-changelog

#8029 fix: add tests and minor edits
  core/processor/abci.go
  core/types/data_source.go
  core/types/data_source_test.go
Labels: no-changelog, no-issue

#8037 chore: use retry delay in ethereum client getCurrentHeight
  core/client/eth/client.go
Labels: no-changelog, no-issue

#8036 Add feature tests for 0068-MATC spec
  core/integration/features/orders/760_cancel_filled_order.feature
  core/integration/steps/parties_place_the_following_orders.go
Labels: no-changelog

#8049 fix: fix internal data sources bug
  CHANGELOG.md
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
  core/governance/checkpoint_test.go
  core/governance/engine_new_market_test.go
  core/governance/engine_test.go
  core/governance/engine_update_market_test.go
  core/governance/market.go
  core/governance/snapshot_test.go
  core/oracles/oracle_spec.go
  core/types/data_source.go
  core/types/data_source_external.go
  core/types/data_source_external_oracle.go
  core/types/data_source_internal.go
  core/types/data_source_internal_tme.go
  core/types/data_source_test.go
  core/types/governance_new_market.go
  core/types/governance_update_market.go
  protos/vega/spec_definition.go
  protos/vega/spec_definition_external.go
  protos/vega/spec_definition_test.go
Labels: oracles
