Repository vegaprotocol/vega, pull requests merged in 2023-11, with the labels that each got.

#9957 fix: first apply migration, then register the dispatch strategy
  core/banking/checkpoint.go
Labels: no-changelog, no-issue

#9997 Make the stringer a bit more generic
  core/datasource/common/data_signer.go
  core/types/asset.go
  core/types/chain_events.go
  core/types/collateral.go
  core/types/delegation.go
  core/types/fees.go
  core/types/governance_cancel_transfer.go
  core/types/governance_new_asset.go
  core/types/governance_new_freeform.go
  core/types/governance_new_market.go
  core/types/governance_new_spot_market.go
  core/types/governance_new_transfer.go
  core/types/governance_proposal.go
  core/types/governance_update_asset.go
  core/types/governance_update_market.go
  core/types/governance_update_market_state.go
  core/types/governance_update_network_parameter.go
  core/types/governance_update_referral_program.go
  core/types/governance_update_spot_market.go
  core/types/governance_update_volume_discount_program.go
  core/types/liquidity.go
  core/types/market.go
  core/types/matching.go
  core/types/orders.go
  core/types/pricemonitoring.go
  core/types/processor.go
  core/types/risk.go
  core/types/staking.go
  core/types/transfer.go
  libs/stringer/stringer.go
  libs/stringer/stringer_test.go
Labels: no-changelog, no-issue

#10006 Liquidation strategy
  CHANGELOG.md
  commands/errors.go
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  core/governance/engine_new_market_test.go
  core/governance/engine_test.go
  core/governance/engine_update_market_test.go
  core/governance/market.go
  core/types/governance_new_market.go
  core/types/governance_new_market_test.go
  core/types/governance_update_market.go
  core/types/liquidation.go
  core/types/market.go
  datanode/entities/market.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/liquidation_strategy_resolver.go
  datanode/gateway/graphql/new_market_resolver.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/sqlstore/markets.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/migrations/0056_add_liquidation_strategy.sql
  protos/sources/vega/governance.proto
  protos/sources/vega/markets.proto
  protos/vega/governance.pb.go
  protos/vega/markets.pb.go
Labels: no-issue

#9993 feat: add test for REWA-105
  core/integration/features/rewards/0056-REWA-105.feature
Labels: feature tests, no-changelog

#9996 feat: create test for REWA-108
  core/integration/features/rewards/0056-REWA-108.feature
Labels: feature tests, no-changelog

#10015 chore: add support for liquidity fee settings in feature tests
  core/integration/features/fees/0042-LIQF-fees_settings.feature
  core/integration/steps/the_fees_configuration.go
  core/integration/steps/the_markets.go
Labels: no-changelog

#10018 chore: remove debug println
  core/blockchain/abci/abci.go
Labels: no-changelog, no-issue

#10027 Create api ticket template
  .github/ISSUE_TEMPLATE/api_ticket.md
Labels: no-changelog, no-issue

#10026 feat: update AC number 0019-MCAL-025
  core/integration/features/verified/0019-MCAL-margin_calculator-slippage.feature
Labels: feature tests, no-changelog

#10029 feat: update AC 0019-MCAL-026
  core/integration/features/settlement/0019-MCAL_fundingMargin2.feature
Labels: feature tests, no-changelog

#10030 feat: update AC 0019-MCAL-027, 0019-MCAL-030
  core/integration/features/settlement/0019-MCAL_fundingMargin4.feature
Labels: feature tests, no-changelog

#10031 feat: update AC 0019-MCAL-028, 0019-MCAL-029
  core/integration/features/settlement/0019-MCAL_fundingMargin3.feature
Labels: feature tests, no-changelog

#10034 feat: add feature test for 0042-LIQF-057, 0042-LIQF-058
  core/integration/features/fees/0042-LIQF-fees_settings.feature
Labels: feature tests, no-changelog

#10044 feat: add feature test for 0004-AMND-058
  core/integration/features/orders/amend-order.feature
Labels: feature tests, no-changelog

#10100 chore: renable support for teams in update-referal-set
  commands/update_referral_set.go
  commands/update_referral_set_test.go
Labels: no-changelog, no-issue

#10101 Remove constraint on epoch range to list fees stats
  GETTING_STARTED.md
  datanode/api/errors.go
  datanode/api/trading_data_v2.go
  datanode/gateway/graphql/schema.graphql
  datanode/sqlstore/fees_stats.go
  datanode/sqlstore/fees_stats_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog, no-issue

#10124 fix: estimate position API does not need to scale funding payment sin…
  datanode/api/trading_data_v2.go
Labels: no-changelog

#10140 Wire JoinTeam command in transaction
  commands/transaction.go
Labels: no-changelog, no-issue

#10118 Support filtering on status on transfers
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/gateway/graphql/all_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/sqlstore/transfers.go
  datanode/sqlstore/transfers_helpers_for_test.go
  datanode/sqlstore/transfers_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-issue

#10146 Wire JoinTeam command in transaction result
  core/events/transaction_result.go
Labels: no-changelog

#10139 fix: properly generate gql bindings
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/perps_resolver.go
  datanode/gateway/graphql/resolvers_test.go
Labels: no-changelog, no-issue, mainnet-issue

#10134 refactor: fix `CalculateLiquidationPriceWithSlippageFactors` signature
  core/risk/liquidation_calculation.go
Labels: no-changelog, no-issue

#10148 feat: perps test for ac 0053-PERP-027
  core/integration/features/settlement/0053-PERP-027-twap-calculation.feature
  core/integration/main_test.go
  core/integration/steps/the_product_data_should_be.go
Labels: feature tests, no-changelog, perpetual

#10163 Expose quantum amount in reward event
  core/events/reward_payout.go
  core/rewards/engine.go
  core/rewards/engine_test.go
  core/rewards/mocks/activity_streak_mock.go
  core/rewards/mocks/delegation_engine_mock.go
  core/rewards/mocks/market_tracker_mock.go
  core/rewards/mocks/mocks.go
  core/rewards/mocks/teams_mock.go
  core/rewards/mocks/time_service_mock.go
  core/rewards/mocks/topology_mock.go
  core/rewards/mocks/transfers_mock.go
  core/rewards/mocks/vesting_mock.go
  datanode/entities/reward.go
  datanode/entities/reward_test.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0059_add_quantum_amount_in_rewards.sql
  datanode/sqlstore/rewards.go
  protos/sources/vega/events/v1/events.proto
  protos/sources/vega/vega.proto
  protos/vega/events/v1/events.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#10170 feat: add windows sign action
  .github/actions/sign-windows-binary/action.yml
  .github/workflows/release-binaries.yml
Labels: no-changelog
