Repository vegaprotocol/vega, pull requests merged in 2023-09, with the labels that each got.

#9265 chore: validate transfer dispatch metric window size
  commands/transfer_funds.go
  commands/transfer_funds_test.go
Labels: no-changelog, no-issue

#9274 chore: encapsulate setting of twap period to avoid bugs
  core/products/perpetual.go
  core/products/perpetual_test.go
Labels: no-changelog, no-issue

#9284 fix: allow vested reward accounts as transfer source
  core/types/banking.go
Labels: no-changelog, no-issue

#9285 fix: set LP as cancelled immediately
  core/liquidity/v2/amendments.go
Labels: no-changelog

#9299 test: progress network per epoch
  CHANGELOG.md
  core/integration/features/verified/0061-REWP-delegation_rewards.feature
  core/integration/main_test.go
  core/integration/steps/blocks.go
Labels: no-issue

#9295 fix: use correct vested account when transferring from it
  core/banking/engine.go
  core/banking/mocks/mocks.go
  core/banking/transfers_common.go
  core/collateral/engine.go
Labels: no-changelog, no-issue

#9298 feat: add test for 0044-LIME-020
  core/integration/features/liquidity-provision/0044-LIME-020.feature
Labels: feature tests, no-changelog

#9283 feat: add FT for SLA
  core/integration/features/liquidity-provision/0044-LIME-014.feature
  core/integration/features/liquidity-provision/0044-LIME-016.feature
Labels: feature tests, no-changelog

#9303 chore: remove obsolete network parameters from snapshots
  core/netparams/netparams.go
  core/netparams/snapshot.go
Labels: no-changelog

#9269 Adding test for LIMIT, PEGGED and ICEBERG commitment
  core/integration/features/liquidity-provision/0044-LIME-028.feature
  core/integration/steps/parties_place_the_following_orders.go
Labels: no-changelog

#9296 Fix 9292
  core/execution/common/liquidity_provision.go
  core/execution/common/liquidity_provision_test.go
  core/liquidity/v2/amendments.go
  core/liquidity/v2/amendments_test.go
  core/liquidity/v2/engine_test.go
  core/liquidity/v2/scores_test.go
  core/liquidity/v2/sla_test.go
  core/liquidity/v2/snapshot_test.go
Labels: bug, no-changelog

#9308 Testing for lp orders on both sides of the book
  core/integration/features/liquidity-provision/0044-LIME-027.feature
Labels: no-changelog

#9297 feat: add test for AC 0044-LIME-065
  core/integration/features/liquidity-provision/0044-LIME-065.feature
Labels: feature tests, no-changelog

#9320 Test for time ordering for lp amendments
  core/integration/features/liquidity-provision/0044-LIME-026.feature
Labels: no-changelog

#9322 Add feature test for SLA Acs
  core/integration/features/liquidity-provision/0044-LIME-063.feature
Labels: feature tests, no-changelog

#9324 Correct penalty for early exit
  core/integration/features/liquidity-provision/0044-LIME-024.feature
Labels: no-changelog

#9330 feat: add test for 0044-077
  core/integration/features/liquidity-provision/0044-LIME-077.feature
Labels: feature tests

#9339 feat: add ft for 0042-043
  core/integration/features/liquidity-provision/0042-LIQF-043.feature
Labels: feature tests

#9340 Check we can always remove commitment even when target stake not met
  core/integration/features/liquidity-provision/0044-LIME-060.feature
  core/liquidity/v2/amendments.go
Labels: no-changelog

#9335 feat: add FTs to cover SLA performance ACs
  core/integration/features/fees/setting-fee-and-rewarding-lps.feature
  core/integration/features/verified/0042-LIQF-SLA.feature
Labels: feature tests, no-changelog, liquidity-sla

#9311 fix: make new engine compatible with old snapshot
  core/banking/engine.go
  core/execution/common/interfaces.go
  core/execution/common/market_activity_tracker_snapshot.go
  core/execution/common/mocks/mocks.go
  core/execution/engine_snapshot.go
  core/execution/engine_snapshot_test.go
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
  core/execution/future/market_snapshot_test.go
  core/execution/future/market_test.go
  core/execution/snapshot_test.go
  core/execution/spot/market.go
  core/execution/spot/market_snapshot.go
  core/liquidity/v2/snapshot.go
  core/liquidity/v2/snapshot_test.go
  core/liquidity/v2/snapshot_v1.go
Labels: no-changelog

#9326 Check all parties get penalty when market under committed level
  core/integration/features/liquidity-provision/0044-LIME-023.feature
Labels: no-changelog

#9355 chore: fix migrations order to fit with the 72.x upgrade
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0021_oracle_data.sql
  datanode/sqlstore/migrations/0021_remove_oracle_data_current_table.sql
  datanode/sqlstore/migrations/0022_upgrade_tables_to_hypertables.sql
  datanode/sqlstore/migrations/0023_market_state_update.sql
  datanode/sqlstore/migrations/0024_sla_governance.sql
  datanode/sqlstore/migrations/0025_oracle_data.sql
  datanode/sqlstore/migrations/0026_periodic_settlement_data.sql
  datanode/sqlstore/migrations/0027_add_rejection_reason_on_stop_orders.sql
  datanode/sqlstore/migrations/0028_market_data_add_funding_rate.sql
  datanode/sqlstore/migrations/0029_market_liquidity_sla_parameters.sql
  datanode/sqlstore/migrations/0030_funding_period_data_points_table_to_hypertable.sql
  datanode/sqlstore/migrations/0031_fee_discounts.sql
  datanode/sqlstore/migrations/0032_activity_streak.sql
Labels: no-changelog, no-issue

#9358 chore: support referrral set command in transaction results event
  core/events/transaction_result.go
Labels: no-changelog

#9362 fix: if nullchain has eth client don't do staking loop hack
  core/protocol/all_services.go
Labels: no-changelog, no-issue

#9366 chore: fix events sent for referral set
  core/events/bus.go
Labels: no-changelog

#9372 chore: error verification for referral code
  core/processor/abci.go
Labels: no-changelog, no-issue

#9336 feat: Adding market sim to PR runs
  Jenkinsfile
Labels: no-changelog, no-issue

#9347 feat: add test for AC 0044-LIME-050
  core/integration/features/liquidity-provision/0044-LIME-050.feature
  core/integration/steps/epoch.go
Labels: no-changelog

#9378 feat: update and tidy up test
  core/integration/features/verified/0042-LIQF-fees_rewards.feature
Labels: no-changelog

#9365 feat: add test for 0044 092 and 094
  core/integration/features/liquidity-provision/0044-LIME-092.feature
Labels: no-changelog

#9381 chore: better metrics for snapshots
  core/metrics/prometheus.go
  core/snapshot/engine.go
  core/snapshot/metrics.go
  core/snapshot/worker.go
Labels: snapshots, no-changelog, no-issue

#9379 feat: change margin calcuations for perps to take into account positi…
  core/products/future.go
  core/products/perpetual.go
  core/products/perpetual_test.go
  core/products/products.go
  core/risk/engine.go
  core/risk/engine_test.go
  core/risk/margins_calculation.go
  libs/num/int.go
Labels: no-changelog

#9390 chore: ensure not lp orders loaded from snapshots are remaining in the book after the 72 upgrade
  core/execution/common/interfaces.go
  core/execution/common/mocks/mocks.go
  core/execution/future/market.go
  core/liquidity/v2/engine.go
  core/liquidity/v2/snapshot_v1.go
Labels: no-changelog, no-issue

#9394 fix: wrong restore of the running volumes in referral program
  core/referral/engine.go
Labels: no-changelog

#9361 feat: Adding integration tests for SLA
  core/integration/features/liquidity-provision/lp-distressed-closeout.feature
  core/integration/features/verified/0044-LIME-SLA.feature
Labels: no-changelog

#9223 fix: fix ds queries in gql
  core/datasource/common/spec.go
  core/datasource/definition/definition.go
  core/datasource/definition/definition_test.go
  datanode/entities/data.go
  datanode/entities/data_source_definition.go
  datanode/entities/data_source_definition_test.go
  datanode/entities/data_source_spec_test.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/oracles_resolver.go
  datanode/gateway/graphql/oracles_resolver_test.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/integration/oracles_test.go
  datanode/integration/testdata/golden/TestOracles_OracleDataConnectionExternal
  datanode/integration/testdata/golden/TestOracles_OracleDataConnectionExternalEthereum
  datanode/integration/testdata/golden/TestOracles_OracleDataConnectionInternal
  datanode/integration/testdata/golden/TestOracles_OracleDataSourceExternal
  datanode/integration/testdata/golden/TestOracles_OracleDataSourceExternalEthereum
  datanode/integration/testdata/golden/TestOracles_OracleDataSourceInternal
  datanode/sqlstore/oracle_spec_test.go
  protos/vega/spec_definition.go
Labels: no-changelog, ethereum-oracles

#9396 chore: optimise market activity tracker
  core/execution/common/market_activity_tracker.go
  core/execution/common/market_activity_tracker_internal_test.go
  core/execution/common/market_activity_tracker_snapshot.go
  core/execution/common/market_activity_tracker_test.go
  core/execution/future/market.go
  libs/num/decimal.go
  protos/sources/vega/checkpoint/v1/checkpoint.proto
  protos/vega/checkpoint/v1/checkpoint.pb.go
Labels: no-changelog, no-issue

#9418 feat: expose party notional taker volume per epoch
  core/events/referral_set.go
  core/referral/engine.go
  core/types/referral_set.go
  protos/sources/vega/events/v1/events.proto
  protos/vega/events/v1/events.pb.go
Labels: no-changelog, no-issue

#9383 Add steps for referral program in integration tests
  core/events/account.go
  core/events/referral_set.go
  core/integration/features/accounts/2943-distressed-trader-has-general-balance.feature
  core/integration/features/auctions/opening-auction-indicative-price.feature
  core/integration/features/auctions/opening-auction-price.feature
  core/integration/features/closeouts/2878-close-out-orders-allowed-when-under-initial.feature
  core/integration/features/closeouts/distressed-safe-event.feature
  core/integration/features/fees/amend-fees.feature
  core/integration/features/fees/setting-fee-and-rewarding-lps.feature
  core/integration/features/fees/trading-fees-pdp.feature
  core/integration/features/liquidity-provision/mid-price-issue-amend.feature
  core/integration/features/orders/stoporders.feature
  core/integration/features/perpetual.feature
  core/integration/features/rewards/asset_fees_rewards.feature
  core/integration/features/settlement/mark_to_market_interval_positions.feature
  core/integration/features/spots/SpotFunctionalTests/TC-0010-Spot-Bid-Decimals.feature
  core/integration/features/successor-markets-ELS.feature
  core/integration/features/successor-markets-SLA.feature
  core/integration/features/system-test-default.feature
  core/integration/features/verified/0011-MARA-016017.feature
  core/integration/features/verified/0019-MCAL-margin_calculator-verified_margins_case5.feature
  core/integration/features/verified/0029-FEES-trading_fees.feature
  core/integration/features/verified/0034-PROB-liquidity_TauScaling.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_multi_lps.feature
  core/integration/features/verified/Funding-treasury.feature
  core/integration/features/verified/Negative-Position-Decimal-Places.feature
  core/integration/features/verified/closeout-LP_New_Exit_Price.feature
  core/integration/features/verified/liquidity-provision-bond-account.feature
  core/integration/main_test.go
  core/integration/setup_test.go
  core/integration/steps/helpers/reader.go
  core/integration/steps/market/defaults/unmarshaler.go
  core/integration/steps/market/fees_config.go
  core/integration/steps/market/liquidity_monitoring.go
  core/integration/steps/market/margin_calculators.go
  core/integration/steps/market/oracle_configs.go
  core/integration/steps/market/price_monitoring.go
  core/integration/steps/market/risk_models.go
  core/integration/steps/market/sla_params.go
  core/integration/steps/parties_apply_the following_referral_codes.go
  core/integration/steps/parties_create_the following_referral_codes.go
  core/integration/steps/referral/benefit_tiers_configs.go
  core/integration/steps/referral/defaults/benefit-tiers/default.json
  core/integration/steps/referral/defaults/staking-tiers/default.json
  core/integration/steps/referral/referral_program_config.go
  core/integration/steps/referral/staking_tiers_configs.go
  core/integration/steps/table_wrapper.go
  core/integration/steps/the_following_trades_happened.go
  core/integration/steps/the_following_transfers_should_happen.go
  core/integration/steps/the_referral_benefit_tiers_configuration.go
  core/integration/steps/the_referral_program.go
  core/integration/steps/the_referral_set_stats_should_be.go
  core/integration/steps/the_referral_staking_tiers_configuration.go
  core/integration/stubs/broker_stub.go
  core/integration/stubs/staking_account_stub.go
  core/referral/engine.go
Labels: no-changelog

#9425 fix: fix field names and 'every' field in EthCallSpec
  core/datasource/definition/definition_test.go
  core/datasource/external/ethcall/common/spec_test.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/oracles_resolver.go
  datanode/gateway/graphql/schema.graphql
  datanode/integration/oracles_test.go
  datanode/integration/testdata/golden/TestOracles_OracleDataConnectionExternal
  datanode/integration/testdata/golden/TestOracles_OracleDataConnectionExternalEthereum
  datanode/integration/testdata/golden/TestOracles_OracleDataConnectionInternal
  datanode/integration/testdata/golden/TestOracles_OracleDataSourceExternal
  datanode/integration/testdata/golden/TestOracles_OracleDataSourceExternalEthereum
  datanode/integration/testdata/golden/TestOracles_OracleDataSourceInternal
Labels: bug, no-changelog, ethereum-oracles

#9389 feat: add test for 0044-088
  core/integration/features/liquidity-provision/0044-LIME-088.feature
Labels: no-changelog

#9325 feat: add test for changing SLA market parameter
  core/integration/features/liquidity-provision/0044-LIME-063.feature
  core/integration/features/liquidity-provision/0044-LIME-091.feature
Labels: no-changelog

#9410 feat: Adding branchRun flag for market sim
  Jenkinsfile
Labels: no-changelog, no-issue

#9439 feat: add feature tests for referral program
  core/execution/engine_snapshot_test.go
  core/execution/future/market_test.go
  core/execution/snapshot_test.go
  core/execution/spot/market_test.go
  core/fee/engine.go
  core/fee/engine_test.go
  core/governance/market_cp_restore_test.go
  core/integration/features/referrals/0083-RFPR-benefit_factors.feature
  core/integration/features/referrals/0083-RFPR-running_volume.feature
  core/integration/features/referrals/0083-RFPR-staking_multipliers.feature
  core/integration/main_test.go
  core/integration/setup_test.go
  core/integration/steps/assets.go
Labels: feature tests, no-changelog, referral

#9452 Testing volume discount program
  core/integration/features/0084-VDPR-012.feature
  core/integration/main_test.go
  core/integration/setup_test.go
  core/integration/steps/volume_discount_program.go
Labels: no-changelog

#9469 Feature test vdpr-0013
  core/integration/features/0084-VDPR-013.feature
  core/integration/main_test.go
  core/integration/steps/volume_discount_program.go
  core/volumediscount/engine.go
Labels: no-changelog

#9479 chore: update default network parameter values for new SLA params
  core/netparams/defaults.go
Labels: no-changelog

#9437 Add steps for vesting and activity streak
  cmd/data-node/commands/start/node.go
  cmd/data-node/commands/start/sqlsubscribers.go
  core/collateral/engine.go
  core/events/bus.go
  core/events/vesting.go
  core/integration/features/activity-streak/0086-ASPR-evaluating_activity.feature
  core/integration/main_test.go
  core/integration/steps/parties_should_have_the_following_account_balances.go
  core/integration/steps/the_activity_streaks_should_be.go
  core/integration/steps/the_vesting_stats_should_be.go
  core/integration/stubs/broker_stub.go
  core/netparams/defaults.go
  core/positions/engine.go
  core/positions/snapshot.go
  core/types/vesting.go
  core/vesting/vesting.go
  core/vesting/vesting_snapshot_test.go
  core/vesting/vesting_test.go
  datanode/api/server.go
  datanode/api/trading_test.go
  datanode/broker/convert.go
  datanode/entities/vesting.go
  datanode/service/stubs.go
  datanode/sqlstore/vesting_stats.go
  datanode/sqlsubscribers/vesting_stats_updated.go
  protos/sources/vega/events/v1/events.proto
  protos/vega/events/v1/events.pb.go
Labels: no-changelog

#9480 Test discount code below minimum trigger level
  core/integration/features/0084-VDPR-014.feature
Labels: no-changelog

#9490 fix: use network parameter to control activity streak limit
  core/activitystreak/activitiystreak.go
  core/activitystreak/activitiystreak_snapshot_test.go
  core/activitystreak/activitiystreak_test.go
  core/integration/features/activity-streak/0086-ASPR-evaluating_activity.feature
  core/integration/main_test.go
  core/integration/setup_test.go
  core/netparams/defaults.go
  core/netparams/keys.go
  core/protocol/all_services.go
Labels: no-changelog, no-issue

#9493 fix: set proposal to enacted when we enact them
  core/processor/abci.go
Labels: no-changelog, no-issue

#9497 fix: reject apply code from referrer not referree
  core/processor/abci.go
Labels: no-changelog, no-issue

#9503 feat: add more tests to cover activity streak and vesting program
  core/integration/features/activity-streak/0086-ASPR-evaluating_activity.feature
  core/integration/features/activity-streak/0086-ASPR-streak_benefits.feature
  core/integration/features/vesting/0085-VSPR-vesting.feature
  core/integration/main_test.go
  core/integration/setup_test.go
  core/integration/steps/assets.go
  core/integration/steps/party_should_have_general_account_balance_for_asset.go
  core/integration/steps/transfers.go
  core/integration/stubs/assets.go
  core/integration/stubs/broker_stub.go
  core/netparams/defaults.go
  core/netparams/keys.go
  core/positions/engine.go
  core/positions/snapshot.go
  core/protocol/all_services.go
Labels: feature tests, referral

#9478 feat: add basic SLA stats to market data
  CHANGELOG.md
  core/execution/common/interfaces.go
  core/execution/common/mocks/mocks.go
  core/execution/future/market.go
  core/execution/spot/market.go
  core/liquidity/v2/engine.go
  core/liquidity/v2/sla.go
  core/liquidity/v2/snapshot.go
  core/types/market.go
  datanode/entities/liquidity_provider.go
  datanode/entities/marketdata.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/liquidity_provider_resolver.go
  datanode/gateway/graphql/market_data_resolvers.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/sqlstore/liquidity_provision.go
  datanode/sqlstore/liquidity_provision_test.go
  datanode/sqlstore/market_data.go
  datanode/sqlstore/migrations/0039_market_data_add_liquidity_provider_sla.sql
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/sources/vega/vega.proto
  protos/vega/snapshot/v1/snapshot.pb.go
  protos/vega/vega.pb.go
Labels: api

#9531 fix: market proto ext does not support new asset types
  protos/vega/market_ext.go
Labels: no-changelog, no-issue

#9459 Add steps for volume discount program
  cmd/data-node/commands/start/sqlsubscribers.go
  core/events/bus.go
  core/events/volume_discount_program.go
  core/integration/main_test.go
  core/integration/steps/the_vesting_stats_should_be.go
  core/integration/steps/the_volume_discount_stats_should_be.go
  core/integration/stubs/broker_stub.go
  core/types/party.go
  core/types/volume_discount_program.go
  core/volumediscount/engine.go
  core/volumediscount/engine_test.go
  core/volumediscount/helpers_for_test.go
  core/volumediscount/snapshot.go
  datanode/broker/buffer_files_event_source.go
  datanode/broker/buffered_event_source.go
  datanode/broker/buffered_event_source_test.go
  datanode/broker/convert.go
  datanode/entities/volume_discount.go
  datanode/networkhistory/service_test.go
  datanode/networkhistory/store/store_test.go
  datanode/service/stubs.go
  datanode/sqlstore/sqlstore.go
  datanode/sqlstore/volume_discount_stats.go
  datanode/sqlsubscribers/volume_discount_stats_updated.go
  protos/sources/vega/events/v1/events.proto
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/events/v1/events.pb.go
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog

#9434 feat: send event with fee rebates stats at end of epoch
  cmd/data-node/commands/start/node.go
  cmd/data-node/commands/start/sqlsubscribers.go
  core/events/bus.go
  core/events/fee_stats.go
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
  core/execution/spot/market.go
  core/execution/spot/market_snapshot.go
  core/fee/engine.go
  core/fee/rebate_stats.go
  core/types/snapshot_nodes.go
  datanode/api/errors.go
  datanode/api/server.go
  datanode/api/trading_data_v2.go
  datanode/api/trading_test.go
  datanode/broker/convert.go
  datanode/entities/referral_set_stats.go
  datanode/gateway/graphql/fee_stats_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/service/stubs.go
  datanode/sqlstore/migrations/0040_referral_fees_and_rewards.sql
  datanode/sqlstore/referral_fee_stats.go
  datanode/sqlstore/referral_fee_stats_test.go
  datanode/sqlstore/sqlstore.go
  datanode/sqlsubscribers/referral_fee_stats.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/embed_test.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
  protos/sources/vega/events/v1/events.proto
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/events/v1/events.pb.go
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog

#9538 fix: do not marshall epoch end time if not set
  core/types/epoch.go
Labels: no-changelog, no-issue

#9534 Adding feature tests for perps order types
  core/integration/features/orders/limit-orders-all-market-types.feature
Labels: no-changelog

#9548 Feature tests for perps MARKET orders
  core/integration/features/orders/market-orders-all-market-types.feature
Labels: no-changelog

#9551 feat: Fix up use correct price value for margin estimate
  datanode/api/trading_data_v2.go
Labels: bug, no-changelog, no-issue

#9565 chore: update rate limit docs linked to by the vega documentation
  CHANGELOG.md
  datanode/ratelimit/README.md
Labels: no-issue

#9556 Check iceberg orders are the same for all market types
  core/integration/features/orders/iceberg-orders-all-market-types.feature
Labels: no-changelog

#9585 Testing stop orders with perps market
  core/integration/features/orders/stop-orders-all-market-types.feature
  core/integration/steps/parties_place_the_following_orders.go
Labels: no-changelog

#9583 feat: rework data node mode options and make the default archive
  CHANGELOG.md
  cmd/data-node/commands/init.go
Labels: breaking-change

#9602 feat: add funding payment APIs
  cmd/data-node/commands/start/node.go
  cmd/data-node/commands/start/sqlsubscribers.go
  datanode/api/server.go
  datanode/api/trading_data_v2.go
  datanode/api/trading_test.go
  datanode/entities/entities.go
  datanode/entities/funding_payment.go
  datanode/gateway/graphql/funding_payment_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/service/stubs.go
  datanode/sqlstore/funding_payments.go
  datanode/sqlstore/funding_payments_test.go
  datanode/sqlstore/migrations/0043_add_funding_payment.sql
  datanode/sqlstore/sqlstore.go
  datanode/sqlsubscribers/funding_payments.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog, no-issue

#9608 fix: estimate position can panic for perps
  datanode/api/trading_data_v2.go
Labels: api, datanode, no-changelog, no-issue

#9597 feat: when auto initialsing from network history recheck latest segment after load and load if required
  CHANGELOG.md
  datanode/networkhistory/initialise.go
  datanode/networkhistory/initialise_test.go
  datanode/networkhistory/mocks/networkhistory_service_mock.go
Labels: no-changelog

#9607 fix: sort data source meta data so events are deterministic
  core/datasource/spec/engine.go
Labels: no-changelog, no-issue

#9610 Fix the associated BusEventType for VolumeDiscountEvent
  core/events/bus.go
  datanode/broker/deserialize.go
Labels: no-changelog

#9618 Remove spaces in filenames
  core/integration/steps/parties_apply_the_following_referral_codes.go
  core/integration/steps/parties_create_the_following_referral_codes.go
Labels: no-changelog, no-issue

#9620 fix: Ensure volume discount program is initialized
  cmd/data-node/commands/start/sqlsubscribers.go
Labels: no-changelog

#9614 fix: fix trigger times in GQL
  datanode/gateway/graphql/oracles_resolver.go
Labels: api, bug, no-changelog, no-issue, ethereum-oracles
