Repository vegaprotocol/vega, pull requests merged in 2023-12, with the labels that each got.

#10183 Fix trading fees register
  CHANGELOG.md
  core/banking/checkpoint_test.go
  core/banking/engine.go
  core/banking/fee_discount.go
  core/banking/fee_discount_test.go
  core/execution/future/market.go
  core/execution/spot/market.go
  datanode/gateway/graphql/schema.graphql
Labels: fees, bug, no-issue

#10198 feat: add test for 0057-TRAN-021
  core/integration/features/transfers/one_off_transfers_fee_discount.feature
Labels: fees, feature tests, transfers, no-changelog

#10199 New transfer test and fix for getting general party account
  core/integration/features/transfers/0057-TRAN-023.feature
  core/integration/stubs/broker_stub.go
Labels: no-changelog

#10206 fix: more flaky game data api unit test fixes
  datanode/entities/game.go
  datanode/sqlstore/games.go
  datanode/sqlstore/games_test.go
  datanode/sqlstore/referral_sets_test.go
  datanode/sqlstore/stop_orders_test.go
  datanode/sqlstore/vesting_stats_test.go
Labels: no-changelog, no-issue

#10171 chore: update snapshot migrations given patches we've done
  core/execution/future/market_snapshot.go
  core/execution/future/market_snapshot_test.go
  core/governance/snapshot.go
  core/products/perpetual_snapshot.go
Labels: no-changelog, no-issue

#10200 0057-TRAN-022
  core/integration/features/transfers/one_off_transfers_fee_discount.feature
Labels: fees, feature tests, transfers, no-changelog

#10209 Adding AC PERP-31
  core/integration/features/settlement/0053-PERP-funding-rate-modifiers2.feature
Labels: no-changelog

#10226 feat: make nullchain staking asset configurable
  core/blockchain/nullchain/staking_loop.go
  core/protocol/all_services.go
Labels: no-changelog, no-issue

#10160 chore: add some more eth rpc monitoring
  core/client/eth/client.go
  core/client/eth/client_wrapper.go
  core/datasource/external/ethcall/engine.go
  core/metrics/prometheus.go
  go.mod
  go.sum
Labels: no-changelog, no-issue

#10149 Add teams statistics API
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/entities/entities.go
  datanode/entities/teams.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/gateway/graphql/team_resolvers.go
  datanode/integration/testdata/events/system_tests.evt
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0062_teams_stats.sql
  datanode/sqlstore/rewards.go
  datanode/sqlstore/rewards_test.go
  datanode/sqlstore/teams.go
  datanode/sqlstore/teams_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/embed_test.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: no-issue

#10236 Extend teams stats API with team members stats API
  datanode/api/trading_data_v2.go
  datanode/entities/entities.go
  datanode/entities/teams.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/gateway/graphql/team_resolvers.go
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0062_teams_stats.sql
  datanode/sqlstore/teams.go
  datanode/sqlstore/teams_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/embed_test.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: no-changelog, no-issue

#10250 Filter ledger by transfer ID
  datanode/entities/aggregated_ledgerentries.go
  datanode/entities/ledgerentry.go
  datanode/entities/ledgerentry_filter.go
  datanode/sqlstore/ledger.go
  datanode/sqlstore/ledger_test.go
  datanode/sqlstore/ledgerentry_filter.go
  datanode/sqlsubscribers/ledger_movement.go
  protos/vega/governance.go
Labels: no-changelog

#10261 Rework some visor error messages to be more user-friendly
  cmd/vega/commands/nodewallet/reload.go
  cmd/visor/main.go
  cmd/visor/run.go
  core/admin/client.go
  datanode/admin/client.go
  visor/client/client.go
  visor/config/visor_config.go
  visor/visor.go
Labels: no-changelog

#10273 feat: add test for perps in isolated margin mode AC 0019-MCAL-053
  core/integration/features/settlement/0019-MCAL_053.feature
  core/integration/features/settlement/0019-MCAL_055.feature
  core/integration/features/settlement/0019-MCAL_058.feature
Labels: feature tests

#10284 Ensure the quantum_rewards are ordered on team members stats API
  datanode/sqlstore/teams.go
Labels: no-changelog, no-issue

#10279 update required go version to 1.21
  .github/workflows/codeql.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/release-binaries.yml
  .github/workflows/release-docs.yml
  .golangci.toml
  docker/data-node.dockerfile
  docker/vega.dockerfile
  docker/vegawallet.dockerfile
  go.mod
  go.sum
Labels: no-changelog, no-issue

#10287 feat: add feature test for isolated margin AC 0019-MCAL-067, and tidy up
  core/integration/features/margin/0019-MCAL-037.feature
  core/integration/features/margin/0019-MCAL-042.feature
  core/integration/features/margin/0019-MCAL-145.feature
  core/integration/features/margin/0019-MCAL-150.feature
Labels: feature tests, no-changelog
