Repository vegaprotocol/vega, pull requests merged in 2023-04, with the labels that each got.

#7975 fix: increase default validation timestamps for the erc20 events
  core/banking/engine.go
Labels: no-changelog, no-issue

#8067 chore: move all vega commands to a separte package
  cmd/vega/commands/announce_node.go
  cmd/vega/commands/blockexplorer.go
  cmd/vega/commands/bridge.go
  cmd/vega/commands/bridge/erc20.go
  cmd/vega/commands/bridge/privkey_signer.go
  cmd/vega/commands/datanode.go
  cmd/vega/commands/faucet/faucet.go
  cmd/vega/commands/faucet/init.go
  cmd/vega/commands/faucet/run.go
  cmd/vega/commands/faucet_test.go
  cmd/vega/commands/genesis/generate.go
  cmd/vega/commands/genesis/genesis.go
  cmd/vega/commands/genesis/load_checkpoint.go
  cmd/vega/commands/genesis/new.go
  cmd/vega/commands/genesis/new_validator.go
  cmd/vega/commands/genesis/update.go
  cmd/vega/commands/init.go
  cmd/vega/commands/main_test.go
  cmd/vega/commands/node.go
  cmd/vega/commands/node/app_wrapper.go
  cmd/vega/commands/node/fetch_genesis.go
  cmd/vega/commands/node/node.go
  cmd/vega/commands/nodewallet/generate.go
  cmd/vega/commands/nodewallet/import.go
  cmd/vega/commands/nodewallet/reload.go
  cmd/vega/commands/nodewallet/root.go
  cmd/vega/commands/nodewallet/show.go
  cmd/vega/commands/nodewallet/verify.go
  cmd/vega/commands/paths/explain.go
  cmd/vega/commands/paths/list.go
  cmd/vega/commands/paths/paths.go
  cmd/vega/commands/propose_upgrade.go
  cmd/vega/commands/query.go
  cmd/vega/commands/query/accounts.go
  cmd/vega/commands/query/assets.go
  cmd/vega/commands/query/client.go
  cmd/vega/commands/query/markets.go
  cmd/vega/commands/query/network_parameters.go
  cmd/vega/commands/query/parties.go
  cmd/vega/commands/query/proposals.go
  cmd/vega/commands/query/validators.go
  cmd/vega/commands/root.go
  cmd/vega/commands/rotate_eth_key.go
  cmd/vega/commands/subcmd_example.go
  cmd/vega/commands/tm.go
  cmd/vega/commands/unsafe_reset_all.go
  cmd/vega/commands/verify.go
  cmd/vega/commands/verify/asset.go
  cmd/vega/commands/verify/genesis.go
  cmd/vega/commands/verify/genesis_test.go
  cmd/vega/commands/verify/reporter.go
  cmd/vega/commands/verify/verifier.go
  cmd/vega/commands/version.go
  cmd/vega/commands/wallet.go
  cmd/vega/commands/watch.go
  cmd/vega/main.go
Labels: no-changelog, no-issue

#8063 feat: report partial batch instruction processing error
  CHANGELOG.md
  core/blockchain/abci/abci.go
  core/blockchain/response.go
  core/processor/batch_market_instructions_processor.go
  core/processor/batch_market_instructions_processor_test.go
Labels: block-explorer

#8068 fix: add tests for ext type with timestamp
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
Labels: no-changelog, no-issue

#8042 API for getting csv data from network history
  CHANGELOG.md
  datanode/api/errors.go
  datanode/api/mocks/networkhistory_service_mock.go
  datanode/api/server.go
  datanode/api/testdata/dummysegment.tar
  datanode/api/trading_data_v2.go
  datanode/api/trading_data_v2_test.go
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/rest/server.go
  datanode/networkhistory/fsutil/fsutil.go
  datanode/networkhistory/initialise_test.go
  datanode/networkhistory/service.go
  datanode/networkhistory/service_test.go
  datanode/networkhistory/snapshot/current.go
  datanode/networkhistory/snapshot/history.go
  datanode/networkhistory/snapshot/history_test.go
  datanode/networkhistory/snapshot/service_create_snapshot.go
  datanode/networkhistory/snapshot/service_load_snapshot.go
  datanode/networkhistory/store/store.go
  datanode/networkhistory/store/store_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/embed_test.go
  protos/sources/buf.yaml
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: breaking-change, DatanodeV2

#8059 feat: notary to keep track of pending signature and send events once in OnTick if needed
  core/notary/notary.go
  core/notary/snapshot.go
  core/types/snapshot_nodes.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog, no-issue

#8087 fix: list order with filter panic fixed
  datanode/api/trading_data_v2.go
Labels: no-changelog, no-issue

#8078 chore: improve key rotation api docs
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/events/v1/events.proto
  protos/vega/events/v1/events.pb.go
Labels: no-changelog

#8066 chore: remove rewards and delegations streams
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/service/delegations.go
  datanode/service/rewards.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/embed_test.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: no-changelog, no-issue

#8098 chore: update dev core version
  protos/blockexplorer/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#8096 fix: allow no party id in ListDeposits and ListWithdrawals
  datanode/api/trading_data_v2.go
Labels: no-changelog, no-issue

#8101 refactor: use mark price price for all margin calcs
  core/execution/engine.go
  core/execution/margin.go
  core/execution/market.go
  core/execution/market_test.go
  core/integration/features/accounts/2943-distressed-trader-has-general-balance.feature
  core/integration/features/liquidity-provision/lp-distressed-closeout-pdp.feature
  core/integration/features/liquidity-provision/lp-distressed-closeout.feature
  core/integration/features/verified/0029-FEES-trading_fees.feature
  core/integration/features/verified/0035-LIQM-liquidity_monitoring.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_large_distribution_time.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_with_decimal.feature
  core/integration/features/verified/closeout-LP_New_Exit_Price.feature
Labels: no-changelog, no-issue

#8108 Expose margin and liquidation price calculations for new API endpoint
  core/risk/engine_test.go
  core/risk/liquidation_calculation.go
  core/risk/margins_calculation.go
Labels: no-changelog, no-issue

#7979 feat: enhance trades query to allow filtering for multiple markets an…
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/market_resolvers.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/service/trade.go
  datanode/sqlstore/trades.go
  datanode/sqlstore/trades_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: breaking-change

#8132 chore: Update CODEOWNERS
  CODEOWNERS
Labels: no-changelog, no-issue

#8140 fix: command validation for heartbeat and announce node signatures
  CHANGELOG.md
  commands/announce_node.go
  commands/announce_node_test.go
  commands/validator_heartbeat.go
  commands/validator_heartbeat_test.go
Labels: no-issue

#8121 feat: use a single http server for both rest and graphql
  CHANGELOG.md
  datanode/broker/buffered_event_source.go
  datanode/gateway/config.go
  datanode/gateway/graphql/server.go
  datanode/gateway/rest/server.go
  datanode/gateway/server/server.go
  datanode/integration/integration_test.go
  datanode/integration/ratelimit_test.go
Labels: no-changelog

#8152 fix: nil pointer protection on state-var bundles
  CHANGELOG.md
  commands/state_var_proposal_submission.go
  core/statevar/snapshot.go
  core/types/statevar/key_value_state_vars.go
Labels: no-issue

#8156 fix: default TTL is maxint when in nullchain mode
  core/processor/codec.go
Labels: no-changelog, no-issue

#8172 feat: add loss socialisation amount tests and position status checks
  core/integration/features/verified/0035-LIQM-liquidity_monitoring.feature
  core/integration/features/verified/closeout-LP_New_Exit_Price.feature
  core/integration/features/verified/closeout-lognormal.feature
  core/integration/main_test.go
  core/integration/steps/parties_should_have_the_following_position_status.go
  core/integration/stubs/broker_stub.go
Labels: no-changelog, no-issue

#8176 fix: add docs for listing rewards summaries calls
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: documentation, rewards, no-changelog

#8181 fix: validate ethereum addresses and cap node vote reference length
  CHANGELOG.md
  commands/announce_node.go
  commands/ethereum_key_rotate_submission.go
  commands/ethereum_key_rotate_submission_test.go
  commands/issue_signatures.go
  commands/node_vote.go
  commands/proposal_submission.go
  commands/state_var_proposal_submission_test.go
  commands/withdraw_submission.go
  commands/withdraw_submission_test.go
  libs/crypto/ethereum.go
Labels: no-issue

#8147 fix: add parser for openAPI documentation
  CHANGELOG.md
  cmd/vegawallet/commands/message_verify.go
  cmd/vegawallet/commands/message_verify_test.go
  cmd/vegawallet/commands/network_import.go
  wallet/api/admin_annotate_key_test.go
  wallet/api/admin_check_transaction.go
  wallet/api/admin_check_transaction_test.go
  wallet/api/admin_close_connection_test.go
  wallet/api/admin_close_connections_to_hostname_test.go
  wallet/api/admin_close_connections_to_wallet_test.go
  wallet/api/admin_create_wallet_test.go
  wallet/api/admin_describe_key_test.go
  wallet/api/admin_describe_network_test.go
  wallet/api/admin_describe_permissions_test.go
  wallet/api/admin_describe_wallet.go
  wallet/api/admin_describe_wallet_test.go
  wallet/api/admin_generate_key_test.go
  wallet/api/admin_import_network.go
  wallet/api/admin_import_network_test.go
  wallet/api/admin_import_wallet_test.go
  wallet/api/admin_isolate_key_test.go
  wallet/api/admin_list_connections_test.go
  wallet/api/admin_list_keys_test.go
  wallet/api/admin_list_networks_test.go
  wallet/api/admin_list_permissions_test.go
  wallet/api/admin_list_wallets_test.go
  wallet/api/admin_purge_permissions_test.go
  wallet/api/admin_remove_network_test.go
  wallet/api/admin_remove_wallet_test.go
  wallet/api/admin_rename_network_test.go
  wallet/api/admin_rename_wallet_test.go
  wallet/api/admin_revoke_permissions_test.go
  wallet/api/admin_rotate_key_test.go
  wallet/api/admin_send_raw_transaction_test.go
  wallet/api/admin_send_transaction.go
  wallet/api/admin_send_transaction_test.go
  wallet/api/admin_sign_message.go
  wallet/api/admin_sign_message_test.go
  wallet/api/admin_sign_transaction.go
  wallet/api/admin_sign_transaction_test.go
  wallet/api/admin_taint_key_test.go
  wallet/api/admin_untaint_key_test.go
  wallet/api/admin_update_network_test.go
  wallet/api/admin_update_passphrase_test.go
  wallet/api/admin_update_permissions_test.go
  wallet/api/admin_verify_message.go
  wallet/api/admin_verify_message_test.go
  wallet/api/client_check_transaction_test.go
  wallet/api/client_get_chain_id_test.go
  wallet/api/client_list_keys_test.go
  wallet/api/client_send_transaction_test.go
  wallet/api/client_sign_transaction_test.go
  wallet/api/openrpc.json
  wallet/api/openrpc_doc_helper_for_test.go
  wallet/api/openrpc_go_helper_for_test.go
  wallet/api/openrpc_helper_for_test.go
  wallet/network/network.go
  wallet/tests/commands_for_test.go
  wallet/wallet/errors.go
  wallet/wallet/permissions.go
Labels: documentation, wallet

#8192 Remove TTL, use PoW instead
  CHANGELOG.md
  cmd/vegawallet/commands/service_run.go
  core/api/core.go
  core/blockchain/abci/abci_test.go
  core/blockchain/abci/tm_node.go
  core/blockchain/abci/types.go
  core/blockchain/response.go
  core/netparams/defaults.go
  core/netparams/keys.go
  core/pow/engine.go
  core/pow/engine_test.go
  core/processor/abci.go
  core/processor/codec.go
  core/processor/gastimator_test.go
  core/processor/mocks/mocks.go
  core/processor/processor.go
  core/processor/tx.go
  core/protocol/all_services.go
  core/spam/vote_spam_policy_test.go
  core/stats/blockchain.go
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/commands/v1/transaction.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/commands/v1/transaction.pb.go
  wallet/api/admin_check_transaction.go
  wallet/api/admin_send_transaction.go
  wallet/api/admin_sign_transaction.go
  wallet/api/api.go
  wallet/api/client_check_transaction.go
  wallet/api/client_check_transaction_test.go
  wallet/api/client_send_transaction.go
  wallet/api/client_send_transaction_test.go
  wallet/api/client_sign_transaction.go
  wallet/api/client_sign_transaction_test.go
  wallet/api/helpers_for_test.go
  wallet/api/node/adapters/grpc_adapter.go
  wallet/api/node/types/types.go
  wallet/api/spam/spam.go
  wallet/commands/commands.go
  wallet/service/service_test.go
  wallet/service/service_v2_test.go
  wallet/service/starter.go
  wallet/service/v2/api.go
  wallet/service/v2/mocks/mocks.go
  wallet/wallets/handler.go
Labels: no-issue

#8198 chore: expose the estimate position endpoint on REST
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/embed_test.go
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: no-changelog, no-issue

#8191 chore: move blockexplorer.proto under api/v1
  blockexplorer/api/grpc/implementation.go
  blockexplorer/api/grpc/server.go
  blockexplorer/api/rest.go
  blockexplorer/blockexplorer.go
  blockexplorer/entities/transaction.go
  blockexplorer/store/transactions.go
  protos/blockexplorer/api/v1/blockexplorer.pb.go
  protos/blockexplorer/api/v1/blockexplorer.pb.gw.go
  protos/blockexplorer/api/v1/blockexplorer_grpc.pb.go
  protos/sources/blockexplorer/api/v1/blockexplorer.proto
Labels: no-changelog, no-issue

#7977 docs: improve wallet api documentation
  datanode/gateway/graphql/schema.graphql
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  wallet/service/openapi.json
Labels: no-changelog

#8196 fix: handle time termination with "lessThan" condition
  CHANGELOG.md
  core/execution/market_test.go
  core/governance/engine_new_market_test.go
  core/governance/engine_update_market_test.go
  core/governance/market.go
  core/oracles/oracle_spec.go
  core/oracles/oracle_spec_test.go
  core/types/data_source.go
  core/types/data_source_internal_tme.go
Labels: oracles

#8207 chore: update doc generation from blockexplore API
  CHANGELOG.md
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/blockexplorer/buf.gen.yaml
  protos/sources/blockexplorer/grpc-rest-bindings.yml
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog

#8217 Add decimal places for oracle spec to datanode
  CHANGELOG.md
  datanode/entities/data.go
  datanode/entities/tradable_instrument.go
  datanode/networkhistory/service_test.go
  protos/sources/vega/data/v1/data.proto
  protos/vega/data/v1/data.pb.go
Labels: oracles, bug

#8219 Fix timestamp error
  core/oracles/oracle_spec.go
Labels: no-changelog, no-issue

#6651 feat: add release note formatting
  .github/release.yml
Labels: no-changelog, no-issue, ignore-for-release
