Repository vegaprotocol/vega, pull requests merged in 2023-05, with the labels that each got.

#8240 feat: add ttl to wallet calls to the nodes
  cmd/vegawallet/commands/cmd.go
  cmd/vegawallet/commands/network_describe.go
  cmd/vegawallet/commands/raw_transaction_send.go
  cmd/vegawallet/commands/transaction_check.go
  cmd/vegawallet/commands/transaction_send.go
  cmd/vegawallet/commands/transaction_sign.go
  wallet/api/admin_check_transaction.go
  wallet/api/admin_check_transaction_test.go
  wallet/api/admin_describe_network.go
  wallet/api/admin_describe_network_test.go
  wallet/api/admin_network.go
  wallet/api/admin_send_raw_transaction.go
  wallet/api/admin_send_raw_transaction_test.go
  wallet/api/admin_send_transaction.go
  wallet/api/admin_send_transaction_test.go
  wallet/api/admin_sign_transaction.go
  wallet/api/admin_sign_transaction_test.go
  wallet/api/admin_update_network.go
  wallet/api/admin_update_network_test.go
  wallet/api/api.go
  wallet/api/helpers_for_test.go
  wallet/api/node/builder.go
  wallet/api/node/retrying_node.go
  wallet/api/node/retrying_node_test.go
  wallet/api/openrpc.json
  wallet/api/openrpc_go_helper_for_test.go
  wallet/api/openrpc_helper_for_test.go
  wallet/network/network.go
  wallet/network/network_test.go
  wallet/network/store/v1/file_store_test.go
  wallet/node/forwarder.go
  wallet/service/config.go
  wallet/service/starter.go
  wallet/service/store/v1/store.go
  wallet/tests/commands_for_test.go
  wallet/tests/sc_describe_network_test.go
Labels: no-changelog, no-issue

#8245 fix: clean up listBalanceChanges docs
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: documentation, no-changelog

#8253 chore: final sweep tidy up on the API docs
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/commands/v1/commands.proto
  protos/sources/vega/data/v1/data.proto
  protos/sources/vega/events/v1/events.proto
  protos/sources/vega/governance.proto
  protos/sources/vega/vega.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/commands/v1/commands.pb.go
  protos/vega/data/v1/data.pb.go
  protos/vega/events/v1/events.pb.go
  protos/vega/governance.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog

#8244 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_ticket.md
  .github/ISSUE_TEMPLATE/release_ticket.md
  .github/ISSUE_TEMPLATE/spike_ticket.md
  .github/ISSUE_TEMPLATE/technical_task.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: no-changelog, no-issue, ignore-for-release

#8274 fix: update UPGRADING.md
  CHANGELOG.md
  UPGRADING.md
Labels: documentation

#8277 fix: validate checksum address
  core/validators/topology.go
Labels: no-changelog, no-issue

#8284 chore: speed up unittest where possible
  Jenkinsfile
  cmd/vegawallet/commands/init_test.go
  core/collateral/snapshot_test.go
  core/governance/engine_test.go
  core/integration/main_test.go
  core/statevar/state_var_test.go
  core/validators/announce_node_test.go
  core/validators/erc20multisig/checkpoint_test.go
  core/validators/topology_checkpoint_test.go
  core/validators/witness_snapshot_test.go
  datanode/integration/integration_test.go
  datanode/sqlstore/blocks_test.go
  datanode/sqlstore/deposits_test.go
  datanode/sqlstore/helpers/helpers.go
  datanode/sqlstore/liquidity_provision_test.go
  datanode/sqlstore/margin_level_test.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/orders_test.go
  datanode/sqlstore/parties_test.go
  datanode/sqlstore/risk_factor_test.go
  datanode/sqlstore/trades_test.go
  datanode/sqlstore/withdrawals_test.go
  libs/crypto/proof_of_work_test.go
  wallet/service/v1/auth_test.go
Labels: no-changelog

#8285 feat: add wallet disclaimer
  CHANGELOG.md
  cmd/vegawallet/commands/disclaimer.go
  cmd/vegawallet/commands/root.go
Labels: no-changelog

#8289 chore: update some deps to migrate to go1.20
  datanode/networkhistory/store/store.go
  go.mod
  go.sum
Labels: no-changelog, no-issue

#8292 chore: add deprecation section to the release note generator
  .github/release.yml
Labels: low, no-changelog, no-issue, ignore-for-release-notes

#8304 fix: update godog flag binding
  core/integration/main_test.go
Labels: no-changelog, no-issue

#8291 chore: deprecate network parameters by disallowing update proposals a…
  CHANGELOG.md
  core/netparams/keys.go
  core/netparams/netparams.go
  datanode/integration/testdata/golden/TestNetParams_Network_Parameters
  datanode/sqlstore/network_parameters.go
  datanode/sqlstore/network_parameters_test.go
Labels: deprecation

#8326 docs: update rate limiting for wss
  datanode/ratelimit/README.md
Labels: no-changelog

#8351 chore: log the error in gov checkpoint
  core/governance/checkpoint.go
Labels: no-changelog, no-issue

#8329 fix: stop deprecated netparams being in the default set
  cmd/vega/commands/verify/genesis.go
  cmd/vega/commands/verify/genesis_test.go
  core/netparams/genesis_state.go
  core/netparams/keys.go
  core/netparams/netparams.go
  core/netparams/netparams_test.go
  datanode/integration/testdata/golden/TestNetParams_Network_Parameters
  datanode/sqlstore/network_parameters.go
  datanode/sqlstore/network_parameters_test.go
Labels: no-changelog, no-issue

#8389 Wording
  datanode/entities/position_test.go
Labels: no-changelog

#8390 Do not set deployment height
  core/netparams/netparams_test.go
  core/netparams/snapshot.go
  datanode/sqlstore/network_parameters.go
Labels: no-changelog, no-issue
