Repository vegaprotocol/vega, pull requests merged in 2023-08, with the labels that each got.

#8958 chore: rename perps to perpetual in protos
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  core/datasource/datasource.go
  core/limits/engine.go
  core/netparams/keys.go
  core/types/governance_new_market.go
  core/types/governance_proposal.go
  core/types/governance_update_market.go
  core/types/market.go
  protos/sources/vega/governance.proto
  protos/sources/vega/markets.proto
  protos/sources/vega/vega.proto
  protos/vega/governance.pb.go
  protos/vega/markets.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#8975 fix: update position-tracking tests
  core/integration/features/position_tracking/verified-positions-resolution-5-lognormal.feature
  core/integration/features/position_tracking/verified-positions-resolution-5-lognormal_pdp.feature
Labels: feature tests, no-changelog, no-issue

#8998 fix: set ethereum oracles check for update market
  core/processor/abci.go
Labels: bug, no-changelog

#9005 Wire the teams engine to the ABCI
  core/processor/abci.go
  core/protocol/all_services.go
  core/protocol/protocol.go
  core/teams/engine.go
  core/teams/engine_test.go
  core/teams/errors.go
  core/teams/helpers_for_test.go
  core/teams/snapshot.go
  core/teams/snapshot_test.go
  core/txn/command.go
Labels: no-changelog, no-issue

#9069 feat: run vega-core pipeline in the office servers
  Jenkinsfile
Labels: no-changelog, no-issue

#9003 Feat/8762 perpetual markets support in existing apis
  CHANGELOG.md
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/instrument_configuration_resolver.go
  datanode/gateway/graphql/instrument_resolver.go
  datanode/gateway/graphql/liquidity_sla_resolver.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/perps_resolver.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/resolvers_test.go
  datanode/gateway/graphql/schema.graphql
  datanode/gateway/graphql/spot_resolver.go
  datanode/sqlstore/markets_test.go
  datanode/sqlstore/proposals_test.go
  protos/vega/vega.go
Labels: api, breaking-change

#9064 chore: add a unittest for perps margin increase
  core/products/perpetual_test.go
Labels: no-changelog

#9019 test: add simplified check tx tool
  CHANGELOG.md
  cmd/vegatools/checktx.go
  cmd/vegatools/checktx_test.go
  cmd/vegatools/root.go
  vegatools/checktx/check.go
  vegatools/checktx/check_test.go
  vegatools/checktx/checktx_testdata.go
  vegatools/checktx/file.go
  vegatools/checktx/file_test.go
Labels: tools

#9115 fix: do not duplicate data when inserting data points
  core/products/perpetual.go
  core/products/perpetual_test.go
Labels: no-changelog, no-issue

#9128 feat: Fix up decimal logic
  core/execution/common/liquidity_provision.go
  core/integration/features/verified/0042-LIQF-fees_rewards_with_decimal.feature
Labels: liquidity-sla

#9139 Eth leave infinite retry if cancelled
  core/evtforward/ethereum/filterer.go
Labels: no-changelog, no-issue

#9165 Revert "chore: exit infinite retry if context was cancelled"
  core/evtforward/ethereum/filterer.go
Labels: no-changelog, no-issue

#9123 Added instructions on how to build from source
  BUILDING.md
Labels: documentation, no-changelog

#9178 SLA related panic
  CHANGELOG.md
  core/execution/common/liquidity_provision.go
Labels: no-changelog

#9188 ci: add option to trigger docs release manually
  .github/workflows/release-docs.yml
Labels: ci, no-changelog

#9175 Feat/migrate fund period data points to hypertable
  datanode/networkhistory/service_test.go
  datanode/sqlstore/funding_period.go
  datanode/sqlstore/funding_period_test.go
  datanode/sqlstore/migrations/0023_periodic_settlement_data.sql
  datanode/sqlstore/migrations/0028_funding_period_data_points_table_to_hypertable.sql
  datanode/sqlstore/sqlstore.go
Labels: no-changelog, no-issue

#9186 chore: update schema transfer type
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog, no-issue

#9201 chore: migrate data when converting the stop_orders table to hypertable
  datanode/sqlstore/migrations/0027_upgrade_tables_to_hypertables.sql
Labels: no-changelog, no-issue

#9224 chore: remove temp hack to restore stop orders
  core/types/snapshot_nodes.go
Labels: no-changelog, no-issue

#9194 feat: add feature test for SLA
  core/execution/common/liquidity_provision.go
  core/integration/features/verified/0044-LIME-SLA.feature
  core/liquidity/v2/sla.go
Labels: bug, no-changelog

#9226 chore: don't collect ipfs garbage on startup
  datanode/networkhistory/store/store.go
Labels: no-changelog, no-issue

#9233 Test for LP early exit penalties
  core/integration/features/liquidity-provision/0044-LIME-025.feature
  core/liquidity/v2/sla.go
Labels: no-changelog

#9235 feat: add support for transfers out of the vested account
  CHANGELOG.md
  commands/transfer_funds.go
  commands/transfer_funds_test.go
  core/collateral/engine.go
Labels: no-changelog, no-issue

#9236 fix: handle extreme edge case in twap calcs
  core/products/perpetual.go
  core/products/perpetual_test.go
Labels: no-changelog, no-issue

#9243 chore: disallow transfers meant for metric reward accounds without a …
  commands/transfer_funds.go
Labels: no-changelog, no-issue

#9237 feat: add feature test for 0044
  core/integration/features/liquidity-provision/0044-LIME-LP_amendment.feature
Labels: feature tests, no-changelog, no-issue

#9169 fix: asset id on ledger entry export
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/sqlstore/ledger.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: breaking-change
