Repository vegaprotocol/vega, pull requests merged in 2023-10, with the labels that each got.

#9626 fix: only download the minimum block count when loading from history
  datanode/networkhistory/initialise.go
Labels: no-changelog, no-issue

#9629 fix: add new account types to ledger export sql
  datanode/sqlstore/ledger.go
Labels: no-changelog, no-issue

#9631 fix: do not return early if account does not exist
  core/execution/future/market.go
Labels: no-changelog, no-issue

#9635 chore: remove unused proto message
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#9640 Output the API V2 in the wallet service config commands
  cmd/vegawallet/commands/service_config_describe.go
  cmd/vegawallet/commands/service_config_reset.go
Labels: no-changelog, no-issue

#9632 Rework referral set stats
  CHANGELOG.md
  Makefile
  datanode/api/errors.go
  datanode/api/trading_data_v2.go
  datanode/entities/entities.go
  datanode/entities/referral_set_stats.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/referral_set_resolver.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/integration/testdata/events/system_tests.evt
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0045_unnecessary_referral_set_referee_stats.sql
  datanode/sqlstore/referral_sets.go
  datanode/sqlstore/referral_sets_test.go
  datanode/sqlstore/volume_discount_stats_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: breaking-change

#9646 chore: tagging missing referral ac codes to existing test
  core/integration/features/referrals/0083-RFPR-benefit_factors.feature
  core/integration/features/vesting/0085-VSPR-vesting.feature
Labels: feature tests, no-changelog, referral

#9644 Added AC tag
  core/integration/features/orders/stop-orders-all-market-types.feature
Labels: no-changelog, no-issue

#9645 feat: optionally print out last block in tendermint block store in sn…
  cmd/vegatools/snapshot.go
Labels: no-changelog, no-issue

#9524 feat: Adding test for LIME-062
  .vscode/launch.json
  core/integration/features/liquidity-provision/0044-LIME-062.feature
Labels: no-changelog

#9428 feat: add feature test for edge case when LP_min_time is 0
  core/integration/features/liquidity-provision/0044-LIME-014.feature
Labels: feature tests, no-changelog, no-issue

#9652 feat: add SLA feature tests
  core/integration/features/verified/0034-PROB-liquidity_TauScaling.feature
  core/integration/features/verified/0042-LIQF-SLA.feature
Labels: feature tests, no-changelog, liquidity-sla

#9653 feat: add test for 0044-102
  core/integration/features/liquidity-provision/0044-LIME-102.feature
Labels: feature tests, no-changelog

#9684 chore: increase channels sizes
  core/snapshot/engine.go
Labels: no-changelog, no-issue

#9688 ci: print messages in more colours on Slack at the end of Jenkins pipeline
  Jenkinsfile
Labels: no-changelog, no-issue

#9662 feat: create test for 0070-MKTD-018, 19, 20
  core/integration/features/settlement/0019-MCAL_018.feature
  core/integration/steps/the_markets.go
Labels: feature tests, no-changelog

#9667 chore: remove shapes from the liquidity provision submission command
  protos/sources/vega/commands/v1/commands.proto
  protos/vega/commands/v1/commands.pb.go
Labels: no-changelog, no-issue

#9663 chore: fix error logs formatting
  core/datasource/external/ethcall/engine.go
  core/execution/engine.go
Labels: no-changelog, no-issue

#9696 fix: distribute rewards amongst teams pro-rata by multipliers
  core/integration/features/rewards/team-rewards.feature
  core/integration/setup_test.go
  core/rewards/contribution_reward_calculator.go
  core/rewards/contribution_reward_calculator_test.go
  core/teams/engine.go
Labels: rewards, no-changelog, no-issue

#9713 feat: move tool for parsing events into json into
  cmd/vegatools/events.go
  cmd/vegatools/root.go
  core/snapshot/README.md
  datanode/broker/buffer_files_event_source.go
  datanode/broker/buffered_event_source.go
  vegatools/events/events.go
Labels: no-changelog

#9703 Add epoch data on Volume Discount and Referral Program events
  core/events/referral_program.go
  core/events/volume_discount_program.go
  core/referral/engine.go
  core/volumediscount/engine.go
  datanode/sqlstore/referral_programs.go
  datanode/sqlstore/referral_programs_test.go
  datanode/sqlstore/volume_discount_program.go
  datanode/sqlstore/volume_discount_programs_test.go
  datanode/sqlsubscribers/referral_programs.go
  datanode/sqlsubscribers/volume_discount_programs.go
  protos/sources/vega/events/v1/events.proto
  protos/sources/vega/vega.proto
  protos/vega/events/v1/events.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog

#9730 fix: filter null volume discount stats out
  datanode/sqlstore/volume_discount_stats.go
Labels: no-changelog

#9724 fix: round(0) running volume in volume discount program
  core/volumediscount/engine.go
Labels: no-changelog, high, no-issue

#9737 fix: add integration test for AC 0013-ACCT-028
  core/integration/features/transfers/one_off_transfers.feature
  core/integration/features/transfers/recurring_transfers.feature
Labels: no-changelog

#9742 feat: allow referral fee stats to be filtered by party
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0047_referral_fee_and_set_stats_breakdown.sql
  datanode/sqlstore/referral_fee_stats.go
  datanode/sqlstore/referral_fee_stats_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: api, no-changelog, no-issue, referral

#9739 fix: cleanup liquidity v1 on BeginBlock to use a propoer block context
  core/execution/common/interfaces.go
  core/execution/engine.go
  core/execution/future/market.go
  core/execution/spot/market.go
  core/processor/abci.go
  core/processor/mocks/mocks.go
  core/processor/processor.go
Labels: no-changelog, no-issue

#9744 fix: add missing rest binding for funding payments
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/embed_test.go
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: no-changelog, no-issue

#9763 fix: add a more complex scenario testing the insurance pool draining
  CHANGELOG.md
  core/execution/future/market.go
  core/integration/features/settlement/insurance-pools-at-settlement.feature
Labels: no-changelog, no-issue

#9771 fix: allow creation of general account on demand for transferring fees
  core/collateral/engine.go
Labels: no-changelog, no-issue

#9767 Rename endpoints from refferralFeeStats to feesStats
  CHANGELOG.md
  cmd/data-node/commands/start/node.go
  cmd/data-node/commands/start/sqlsubscribers.go
  core/events/bus.go
  core/events/fee_stats.go
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
  core/execution/spot/market.go
  core/execution/spot/market_snapshot.go
  core/fee/engine.go
  core/fee/rebate_stats.go
  core/types/snapshot_nodes.go
  datanode/api/errors.go
  datanode/api/server.go
  datanode/api/trading_data_v2.go
  datanode/api/trading_test.go
  datanode/broker/convert.go
  datanode/entities/referral_set_stats.go
  datanode/gateway/graphql/fees_stats_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/mocks/mocks.go
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/service/stubs.go
  datanode/sqlstore/fees_stats.go
  datanode/sqlstore/fees_stats_test.go
  datanode/sqlstore/migrations/0048_rename_referral_fee_stats_to_fees_stats.sql
  datanode/sqlstore/referral_sets.go
  datanode/sqlstore/sqlstore.go
  datanode/sqlsubscribers/referral_fee_stats.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/data-node/grpc-rest-bindings.yml
  protos/sources/vega/events/v1/events.proto
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/events/v1/events.pb.go
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: breaking-change

#9769 fix: add integration test SM for AC 0013-ACCT-032
  core/integration/features/successor-markets-insurance.feature
Labels: no-changelog

#9783 Transfer acs
  core/integration/features/transfers/one_off_transfers.feature
  core/integration/main_test.go
  core/integration/steps/assets.go
Labels: no-changelog

#9745 feat: add test for LP fee reward bug
  core/integration/features/verified/rewards_lp_fees.feature
Labels: feature tests, rewards, bug, no-changelog, no-issue, liquidity-sla

#9789 fix: allow liquidity provision submission during suspended by governa…
  core/execution/common/liquidity_provision.go
  core/integration/features/liquidity-provision/0044-LIME-020.feature
  core/integration/features/liquidity-provision/0044-LIME-063.feature
  core/integration/features/liquidity-provision/0044-LIME-LP_amendment.feature
  core/processor/abci.go
Labels: no-changelog, no-issue

#9803 fix: add global insurance pool tests
  core/integration/features/successor-markets-insurance.feature
Labels: integration-tests, no-changelog, no-issue, successor-markets

#9820 Correct typo in fees stats gql API
  datanode/gateway/graphql/fees_stats_resolver.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog, no-issue

#9824 Ensure block-explorer tests works accross different timezones
  blockexplorer/store/transactions_test.go
Labels: no-changelog, no-issue

#9823 chore: standardise doc-strings for newly added API
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/governance.proto
  protos/sources/vega/vega.proto
  protos/vega/governance.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#9816 Remove link to documentation website in wallet doc
  wallet/service/openapi.json
Labels: no-changelog, no-issue

#9830 fix: add integration test for recurring transfer to network treasury
  core/integration/features/transfers/recurring_transfers.feature
Labels: transfers, no-changelog

#9851 chore: improve activity streak multiplier validation
  core/types/activity_streak_benefit_tiers.go
  core/types/activity_streak_benefit_tiers_test.go
Labels: no-changelog, no-issue

#9761 chore: update new network parameters defaults
  core/governance/engine_update_discount_volume_program_test.go
  core/governance/engine_update_referral_program_test.go
  core/netparams/defaults.go
  core/types/activity_streak_benefit_tiers.go
  core/types/activity_streak_benefit_tiers_test.go
  core/types/vesting.go
Labels: no-changelog, no-issue

#9848 chore: improve doc-strings for transaction types and rpc endpoints
  commands/liquidity_provision_submission.go
  commands/liquidity_provision_submission_test.go
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/commands/v1/commands.proto
  protos/sources/vega/commands/v1/data.proto
  protos/sources/vega/commands/v1/signature.proto
  protos/sources/vega/commands/v1/transaction.proto
  protos/sources/vega/commands/v1/validator_commands.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/core_grpc.pb.go
  protos/vega/commands/v1/commands.pb.go
  protos/vega/commands/v1/data.pb.go
  protos/vega/commands/v1/signature.pb.go
  protos/vega/commands/v1/transaction.pb.go
  protos/vega/commands/v1/validator_commands.pb.go
Labels: no-changelog

#9867 chore: add risk factors rest API
  protos/data-node/api/v2/trading_data.pb.gw.go
  protos/embed_test.go
  protos/sources/data-node/grpc-rest-bindings.yml
Labels: no-changelog, no-issue

#9879 fix: re-enable apply referral code
  commands/apply_referral_code.go
  commands/apply_referral_code_test.go
  core/processor/abci.go
Labels: no-changelog

#9898 fix locked balances API
  datanode/sqlstore/migrations/0052_locked_and_vesting_balances.sql
  datanode/sqlstore/party_locked_balance.go
  datanode/sqlstore/party_locked_balance_test.go
  datanode/sqlsubscribers/vesting_summary.go
Labels: no-changelog, no-issue

#9906 fix: return running volume over window
  core/integration/features/0084-VDPR-012.feature
  core/integration/features/0084-VDPR-013.feature
  core/integration/features/0084-VDPR-014.feature
  core/volumediscount/engine.go
  core/volumediscount/engine_test.go
Labels: no-changelog, no-issue

#9907 feat: add test for discounts from multiple sources
  core/integration/features/verified/0029-FEES-multiple_discounts.feature
Labels: feature tests, no-changelog, no-issue

#9903 feat: tidy up feature test 0029-trading-fee
  core/integration/features/verified/0029-FEES-trading_fees.feature
Labels: no-changelog, no-issue

#9933 chore: set version to 0.74.0-dev
  protos/blockexplorer/api/v1/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/api/v1/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#9938 fix: map wasEligible field in referralSetStats in datanode
  datanode/entities/referral_set_stats.go
Labels: no-changelog, no-issue
