Repository vegaprotocol/vega, pull requests merged in 2023-02, with the labels that each got.

#7415 Deprecate X-Vega-Connection HTTP header
  CHANGELOG.md
  cmd/data-node/commands/start/node_pre.go
  datanode/api/mocks/core_service_client_mock.go
  datanode/api/server.go
  datanode/api/trading.go
  datanode/api/trading_test.go
Labels: breaking-change, removal

#7475 chore: Prepare code base for v0.68.0
  protos/blockexplorer/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#7434 chore: update design-architecture diagram
  CHANGELOG.md
  core/docs/README.md
  core/docs/diagrams/design-architecture-2023-01-26.svg
Labels: no-issue

#7471 feat: allow issue signatures to be submitted by non-validators
  CHANGELOG.md
  core/netparams/defaults.go
  core/netparams/keys.go
  core/processor/abci.go
  core/protocol/all_services.go
  core/spam/engine.go
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/commands/v1/commands.proto
  protos/sources/vega/commands/v1/validator_commands.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/commands/v1/commands.pb.go
  protos/vega/commands/v1/validator_commands.pb.go
Labels: breaking-change

#7432 EpochRewardSummary filter with FromEpoch, ToEpoch, MarketIDs and AssetIDs
  CHANGELOG.md
  datanode/api/trading_data_v2.go
  datanode/entities/reward_summary_filter.go
  datanode/entities/reward_summary_filter_test.go
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/gqlgen.yml
  datanode/gateway/graphql/resolvers.go
  datanode/gateway/graphql/reward_summary_filter_resolver.go
  datanode/gateway/graphql/schema.graphql
  datanode/integration/reward_summaries_test.go
  datanode/integration/testdata/golden/TestRewardSummaries_RewardSummaries
  datanode/service/rewards.go
  datanode/sqlstore/rewards.go
  datanode/sqlstore/rewards_test.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: breaking-change

#7458 fix: Github redirect & support zip files
  go.mod
  go.sum
  visor/config/visor_config.go
  visor/github/assets_fetcher.go
  visor/utils/utils.go
  visor/visor-config.md
  visor/visor.go
  visor/visor_folders.go
Labels: no-changelog

#7522 fix: prevent panic if wallet/core mismatch
  wallet/api/node/adapters/insecure_grpc_adapter.go
Labels: no-changelog, no-issue

#7524 fix: data-node tests fail intermittently
  datanode/integration/integration_test.go
Labels: integration-tests, DatanodeV2, no-changelog, no-issue

#7512 chore: remove most of the busEvents from graphql
  datanode/gateway/graphql/generated.go
  datanode/gateway/graphql/modelext.go
  datanode/gateway/graphql/models.go
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog, no-issue

#7523 Feature test: Closeout LP with a trader with a crazy order
  core/integration/features/verified/closeout-LP_with_crazy_order.feature
Labels: feature tests, no-changelog, no-issue

#7488 chore: there is no connection associated to this authentication token
  wallet/service/service_v2_test.go
  wallet/service/v2/connections/errors.go
  wallet/service/v2/connections/manager.go
Labels: no-changelog, no-issue

#7566 refactor: wallet openapi fixes
  .github/workflows/release-docs.yml
  wallet/service/openapi.json
Labels: no-changelog, no-issue

#7572 fix: send market depth event at end of block
  CHANGELOG.md
  datanode/broker/sqlstore_broker.go
  datanode/service/market_depth.go
  datanode/sqlsubscribers/market_depth.go
Labels: bug

#7554 Remove redundant margin update for all parties during auction
  core/execution/margin.go
  core/integration/features/auctions/opening-auction-price.feature
  core/integration/features/auctions/opening-auction-uncross.feature
  core/integration/features/closeouts/position-resolution-after-auction.feature
  core/integration/features/verified/Negative-Position-Decimal-Places.feature
  core/risk/engine.go
  core/risk/engine_test.go
  core/risk/margins_calculation.go
Labels: no-changelog, no-issue

#7590 chore: move misplaced changed to the correct release
  CHANGELOG.md
Labels: no-changelog, no-issue

#7579 chore: update data node docs architecture diagram
  datanode/docs/README.md
  datanode/docs/diagrams/design-architecture-191003001.svg
  datanode/docs/diagrams/design-architecture-2023-01-26.drawio
  datanode/docs/diagrams/design-architecture-2023-01-26.svg
  datanode/docs/diagrams/design-architecture.drawio.xml
Labels: no-changelog, no-issue

#7594 feat: reduce amount of events send byt the position engine
  core/execution/market.go
  core/execution/market_test.go
  core/integration/setup_test.go
  core/positions/config.go
  core/positions/engine.go
Labels: no-changelog, no-issue

#7604 fix: validation in transfer funds command
  commands/transfer_funds.go
  commands/transfer_funds_test.go
Labels: no-changelog, no-issue

#7606 Update JSON-RPC documentation to reflect the update on the network configuration
  wallet/api/openrpc.json
Labels: no-changelog, no-issue

#7584 Add steps to check number of events
  core/integration/features/closeouts/position-resolution-after-auction.feature
  core/integration/features/margin/6202-release-excess-on-amend.feature
  core/integration/features/verified/0019-MCAL-margin_calculator-risk_parameters.feature
  core/integration/features/verified/0042-LIQF-fees_rewards.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_VirtualStake.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_large_distribution_time.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_multi_lps.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_with_decimal.feature
  core/integration/features/verified/0070-MKTD-market-decimal-places.feature
  core/integration/features/verified/Negative-Position-Decimal-Places.feature
  core/integration/features/verified/closeout-LP_with_crazy_order.feature
  core/integration/features/verified/liquidity-provision-bond-account-dp.feature
  core/integration/features/verified/liquidity-provision-bond-account.feature
  core/integration/features/verified/risk-parameters-ranges-test.feature
  core/integration/features/verified/risk-parameters-sigma-test.feature
  core/integration/helpers/account_changes.go
  core/integration/main_test.go
  core/integration/setup_test.go
  core/integration/steps/debug_all_events.go
  core/integration/steps/event_count.go
  core/integration/steps/parties_deposit_assets.go
  core/integration/steps/parties_should_have_the_following_account_balances.go
  core/integration/steps/parties_withdraw_the_following_assets.go
  core/integration/steps/total_of_events_should_be_emitted.go
  core/integration/stubs/broker_stub.go
Labels: feature tests, no-changelog, no-issue

#7611 fix: make the app prop required in the describe network result type
  wallet/api/openrpc.json
Labels: wallet, bug, no-changelog, no-issue

#7408 feat: add test for 0032-PRIM-018 and 0032-PRIM-019
  core/integration/features/settlement/0002-STTL-settlement_at_expiry_with_dp.feature
  core/integration/features/settlement/mark_to_market_interval_positions.feature
Labels: feature tests, no-changelog, no-issue

#7448 feat: AC 0034-PROB-006, check impact from tau.scaling parameter
  core/integration/features/verified/0034-PROB-liquidity_TauScaling.feature
Labels: feature tests, no-changelog

#7612 fix: Add missing JSON tags on network metadata
  wallet/api/admin_describe_network.go
Labels: no-changelog, no-issue

#7498 chore: fix docs for datanode proto definitions
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog

#7616 fix: save m.parties in snapshot so that we don't have to worry the lo…
  CHANGELOG.md
  core/execution/market.go
  core/execution/market_snapshot.go
  core/types/snapshot_nodes.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: breaking-change

#7617 chore: remove pretty formatting on rest API
  datanode/gateway/rest/server.go
Labels: no-changelog, no-issue

#7622 fix: visor restart - clean data node binary path
  CHANGELOG.md
  visor/binaries_runner.go
Labels: no-issue

#7618 chore: spelling/typo fixes for protos
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog, no-issue

#7624 fix: make network config props optional where they can be missing
  wallet/api/openrpc.json
Labels: no-changelog, no-issue

#7610 fix: reduce amount of liquidity orders events emitted
  core/execution/2965_refresh_lp_orders_size_test.go
  core/execution/order_test.go
  core/execution/special_orders.go
Labels: no-changelog, no-issue

#7603 feat: send 1 margin levels events per transaction processing.
  core/execution/liquidity_provision.go
  core/execution/market.go
  core/integration/setup_test.go
  core/positions/engine.go
  core/risk/config.go
  core/risk/engine.go
  core/risk/engine_test.go
Labels: no-changelog, no-issue

#7639 fix: market depth from order event changes
  .golangci.toml
  cmd/data-node/commands/start/sqlsubscribers.go
  datanode/sqlsubscribers/market_depth.go
  datanode/sqlsubscribers/order.go
Labels: no-changelog

#7642 fix: listend to end of block event
  datanode/sqlsubscribers/order.go
Labels: no-changelog, no-issue

#7652 fix: add missing core proxy method on datanode api
  datanode/api/trading.go
Labels: no-changelog, no-issue

#7654 fix: save market's closed field in snapshot
  core/execution/market_snapshot.go
  core/types/snapshot_nodes.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog, no-issue

#7565 Add feature test to cover new slippage cap/factor
  core/integration/features/verified/closeout-LP_with_crazy_order.feature
Labels: feature tests, no-changelog, no-issue

#7659 Tidy up protos for docs consistency
  CHANGELOG.md
  datanode/integration/testdata/system_tests-old.evt.gz
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: documentation

#7668 chore: update version to 0.69.0-dev
  protos/blockexplorer/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#7669 Ensure the `admin.update_network` check for validity
  wallet/api/admin_update_network.go
  wallet/api/admin_update_network_test.go
Labels: no-changelog, no-issue

#7676 fix: populate closed field in market snapshot state
  core/execution/market_snapshot.go
Labels: no-changelog, no-issue

#7678 fix: actually override the right config for tendermint
  core/blockchain/abci/tm_node.go
Labels: no-changelog, no-issue

#7693 chore: fix the way we're not waiting for slow unnecessary validators
  core/blockchain/abci/tm_node.go
Labels: no-changelog, no-issue

#7690 fix: handle ledger entries multiple of same value
  datanode/sqlstore/ledger.go
  datanode/sqlstore/ledger_test.go
  datanode/sqlstore/ledgerentry_filter.go
Labels: bug, no-changelog

#7718 Fix ft in verified folder
  core/integration/features/verified/0026-AUCT-auction_interaction.feature
  core/integration/features/verified/0035-LIQM-liquidity_monitoring.feature
  core/integration/features/verified/0042-LIQF-fees_rewards.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_VirtualStake.feature
  core/integration/features/verified/0042-LIQF-fees_rewards_growing_market.feature
  core/integration/features/verified/Funding-insurance_pool.feature
  core/integration/features/verified/Funding-treasury.feature
  core/integration/features/verified/closeout-LP_New_Exit_Price.feature
  core/integration/features/verified/closeout-LP_with_crazy_order.feature
  core/integration/features/verified/liquidity-provision-bond-account-dp.feature
  core/integration/features/verified/liquidity-provision-bond-account.feature
  core/integration/features/verified/verified-positions-resolution-1.feature
  core/integration/features/verified/verified-positions-resolution-2.feature
  core/integration/features/verified/verified-positions-resolution-3.feature
  core/integration/features/verified/verified-positions-resolution-4.feature
Labels: no-issue, not-a-bug
