Repository vegaprotocol/vega, pull requests merged in 2024-04, with the labels that each got.

#11051 test: check auction behaviour with multiple triggers and uncrossing price with multiple orders
  core/integration/features/auctions/opening-auction-uncross.feature
  core/integration/features/price_monitoring/price-monitoring-lognormal.feature
Labels: no-changelog, no-issue

#11050 fix: providing an invalid date-range to ListBalanceChanges no longer …
  datanode/api/errors.go
  datanode/entities/date_range.go
  datanode/entities/date_range_test.go
Labels: no-changelog, no-issue, api-cleanup

#11049 chore: add contract addresses to stagnet1 migrations code
  core/netparams/bridge_mapping.go
  core/netparams/snapshot.go
Labels: no-changelog, no-issue

#11031 chore: improve candle docs
  datanode/gateway/graphql/schema.graphql
  protos/data-node/api/v2/trading_data.pb.go
  protos/data-node/api/v2/trading_data_grpc.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog

#10996 chore: fix typo in error message
  core/governance/market.go
Labels: no-changelog, no-issue

#11069 feat: improve check on block finality
  core/client/eth/ethereum_confirmations.go
  core/client/eth/ethereum_confirmations_test.go
Labels: no-changelog

#11006 Adding test for 0034-PROB-010
  core/integration/features/spot/orders/0034-PROB-010.feature
Labels: no-changelog

#11052 fix: add missing proposal rejection reason for failed batch proposals
  CHANGELOG.md
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog, no-issue

#11075 Merge master
  CHANGELOG.md
Labels: no-changelog, no-issue

#11072 fix: handle more market decimals than asset decimals properly
  CHANGELOG.md
  core/execution/common/liquidity_provision.go
  core/execution/common/liquidity_provision_test.go
  core/execution/future/liquidation.go
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
  core/execution/future/special_orders.go
  core/execution/spot/market.go
  core/execution/spot/market_snapshot.go
  core/execution/spot/special_orders.go
  core/integration/features/verified/negative_price_factor.feature
  core/integration/features/verified/negative_price_factor_spot.feature
  core/matching/snapshot.go
  core/matching/snapshot_test.go
  core/types/matching.go
Labels: no-changelog, spot

#11078 chore: add testnet bridge mapping
  core/netparams/bridge_mapping.go
Labels: no-changelog, no-issue

#11085 fix: wire in liquidity fee settings when updating a spot market
  core/governance/engine.go
  core/types/governance_update_spot_market.go
Labels: no-changelog, no-issue

#11083 chore: add feature tests for 0042-LIQF
  core/integration/features/spot/liquidity_provision/0042-LIQF-spots.feature
Labels: no-changelog

#11086 feat: spot market target stake feature tests
  core/integration/features/spot/liquidity_provision/0041-TSTK.feature
Labels: feature tests, no-changelog

#11093 fix: do migration of asset chain-id for non-validator nodes later
  core/assets/erc20/erc20.go
  core/assets/snapshot.go
Labels: no-changelog, no-issue

#11094 chore: do not send out extra events on second bridge migrations
  core/assets/snapshot.go
Labels: no-changelog, no-issue

#11097 chore: amend spot feature tests
  core/integration/features/orders/spot-amend-order.feature
  core/integration/features/orders/spot_trader_amends_his_orders.feature
Labels: no-changelog, no-issue

#11096 test: show how triggers with short horizons can expire mid-auction
  core/integration/features/price_monitoring/price-monitoring-lognormal-identical-bounds.feature
Labels: no-changelog, no-issue

#11001 refactor: address the underlying cause of #10997
  core/execution/common/interfaces.go
  core/execution/common/mark_price.go
  core/execution/future/market.go
  core/execution/future/market_test.go
  core/integration/features/mark-price/panic-upon-leaving-opening-auction.feature
  core/integration/features/verified/0044-LIME_lp_at_termination.feature
  core/monitor/price/pricemonitoring.go
Labels: no-changelog, no-issue

#11104 Remove redundant price monitoring checks
  core/execution/future/auction.go
  core/execution/future/market.go
  core/execution/spot/auction.go
  core/monitor/price/pricemonitoring.go
Labels: no-changelog, no-issue

#11107 fix: retro fill migration should use current transfers only
  datanode/sqlstore/migrations/0103_retro_fill_team_reward_totals.sql
Labels: no-changelog, no-issue

#11110 feat: set an end-block in on-chain log filtering to account for faste…
  core/bridges/erc20_logic_view.go
Labels: no-changelog

#11111 chore: cover spot SLA ACs
  core/integration/features/verified/0042-LIQF-SLA_spot.feature
Labels: no-changelog

#11115 chore: 0042-LIQF-069 0042-LIQF-070 0042-LIQF-071
  core/integration/features/spot/liquidity_provision/0042-LIQF-spots.feature
  core/integration/steps/the_spot_markets.go
Labels: no-changelog

#11124 fix: add missing validation on liquidity fee settings in spot proposa…
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  commands/proposal_submission_update_market_test.go
Labels: no-changelog

#11125 chore: cover ACs 0044-LIME-119 and 0044-LIME-114
  core/integration/features/liquidity-provision/0044-LIME-115.feature
  core/integration/features/liquidity-provision/0044-LIME-119.feature
  core/integration/features/verified/0044-LIME-SLA_spot.feature
Labels: no-changelog

#11131 feat: relax Arbitrum block finality check to speed up deposits
  cmd/vega/commands/node/node.go
  core/banking/asset_action.go
  core/client/eth/ethereum_confirmations.go
  core/client/eth/ethereum_confirmations_test.go
  core/client/eth/l2_clients.go
  core/datasource/external/ethverifier/verifier.go
  core/governance/node_validation.go
  core/netparams/bridge_mapping.go
  core/protocol/all_services.go
  core/staking/accounting.go
  core/staking/accounting_snapshot.go
  core/staking/stake_verifier.go
  core/staking/stake_verifier_snapshot.go
  core/staking/staking.go
  core/types/ethereum.go
  core/types/ethereum_secondary.go
  core/validators/erc20multisig/topology.go
  core/validators/witness.go
  core/validators/witness_test.go
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog

#11119 Add high level function to send transaction with wallet
  wallet/pkg/send_transaction.go
Labels: no-changelog, no-issue

#11135 chore: add AC for LIQF-100
  core/integration/features/liquidity-provision/0042-LIQF-100.feature
  core/integration/features/liquidity-provision/0044-LIME-113.feature
Labels: no-changelog

#11117 Order events
  core/events/bus.go
  core/events/cancelled_orders.go
  core/execution/future/event_generation_test.go
  core/execution/future/market.go
  core/execution/future/market_test.go
  core/execution/future/order_test.go
  core/execution/spot/market.go
  core/integration/features/orders/market-depth-4.feature
  core/integration/features/spot/orders/0074-BTCH-019.feature
  core/integration/steps/the_iceberg_orders_should_have_the_following_states.go
  core/integration/steps/the_orders_should_have_the_following_states.go
  core/integration/steps/the_pegged_orders_should_have_the_following_states.go
  core/integration/stubs/broker_stub.go
  core/subscribers/market_depth.go
  datanode/broker/convert.go
  datanode/sqlsubscribers/order.go
  protos/sources/vega/events/v1/events.proto
  protos/vega/events/v1/events.pb.go
Labels: no-changelog

#11102 feat: add tests for spot market marginal cost method
  core/integration/features/spot/liquidity_provision/0042-LIQF-marginal_cost.feature
Labels: no-changelog

#11144 feat: spot sla tests for time fraction on book
  core/integration/features/verified/0042-LIQF-SLA_spot.feature
Labels: feature tests, no-changelog, spot, liquidity-sla

#11148 fix: stop order fixes for spot market + AC covered
  core/execution/spot/market.go
  core/integration/features/orders/stoporders_spot-auctions.feature
  core/integration/features/orders/stoporders_spot.feature
Labels: no-changelog

#11149 chore: restore the batch behaviour of cancel order for spots
  core/execution/spot/market.go
Labels: no-changelog, no-issue

#11146 Add test for SLA in spot market
  core/integration/features/spot/liquidity_provision/0044-LIME-107.feature
Labels: no-changelog, no-issue

#11145 fix: send tree-keys into snapshot worker async so we don't deadlock
  core/snapshot/engine.go
Labels: no-changelog, no-issue

#11150 feat: Adding new spot tests and removing deprecated
  core/integration/features/liquidity-provision/0044-LIME-102.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-102.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-103.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-104.feature
Labels: no-changelog

#11137 chore: change the netparameter for evm chains config to be a list
  cmd/vega/commands/faucet/init.go
  core/client/eth/config.go
  core/client/eth/secondary_client.go
  core/config/config.go
  core/evtforward/config.go
  core/evtforward/engine.go
  core/evtforward/ethereum/config.go
  core/evtforward/evm_forwarders.go
  core/evtforward/forwarder.go
  core/integration/setup_test.go
  core/netparams/bridge_mapping.go
  core/netparams/defaults.go
  core/netparams/keys.go
  core/netparams/netparams.go
  core/netparams/snapshot.go
  core/processor/abci.go
  core/processor/process_chain_event.go
  core/protocol/all_services.go
  core/protocol/engines.go
  core/protocol/protocol.go
  core/snapshot/providers.go
  core/types/ethereum_secondary.go
  core/types/event_forwarder_snapshot.go
  core/types/snapshot.go
  core/types/snapshot_nodes.go
  core/validators/erc20multisig/erc20multisig.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/sources/vega/vega.proto
  protos/vega/snapshot/v1/snapshot.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog

#11163 chore: stop panic when relaod config on non-validator's who don't nee…
  core/protocol/all_services.go
Labels: no-changelog, no-issue

#11164 test: add integration test for the new order cancellation event
  core/integration/features/orders/cancel_all_orders.feature
  core/integration/main_test.go
  core/integration/steps/cancelled_orders.go
Labels: no-changelog, no-issue

#11173 fix: manually set defaults for unset values in EVM bridge configs sin…
  core/evtforward/ethereum/config.go
  core/evtforward/ethereum/engine.go
Labels: no-changelog, no-issue

#11175 chore: fix typo in transaction result for stop_orders_{submission/can…
  core/events/transaction_result.go
  protos/sources/vega/events/v1/events.proto
  protos/vega/events/v1/events.pb.go
Labels: no-changelog, no-issue

#11176 chore: account for new slippage factor in protocol upgrade
  core/types/liquidation.go
Labels: no-changelog, no-issue

#11116 test: add coverage for another AC
  core/integration/features/spot/liquidity_provision/0042-LIQF-084.feature
Labels: no-changelog, no-issue

#11179 chore: adding missing labels for ACs
  core/integration/features/orders/spot_trader_amends_his_orders.feature
Labels: no-changelog, no-issue

#11181 10909 chain in signatures
  cmd/vega/commands/bridge/erc20.go
  core/assets/assets_test.go
  core/assets/erc20/erc20.go
  core/assets/erc20/erc20_test.go
  core/assets/erc20/mocks/eth_client_mock.go
  core/bridges/erc20_asset_pool.go
  core/bridges/erc20_asset_pool_test.go
  core/bridges/erc20_common.go
  core/bridges/erc20_logic.go
  core/bridges/erc20_logic_test.go
  core/bridges/erc20_multisigcontrol.go
  core/bridges/erc20_multisigcontrol_test.go
  core/client/eth/client.go
  core/client/eth/secondary_client.go
  core/validators/signatures.go
Labels: no-changelog

#11188 chore: arb bridges addresses for testnet and staging
  core/netparams/bridge_mapping.go
Labels: no-changelog, no-issue

#11189 fix: various fixes for supporting the difference between no metric an…
  core/banking/recurring_transfers.go
  core/execution/common/market_activity_tracker.go
  core/execution/common/market_activity_tracker_internal_test.go
  core/integration/features/rewards/0056-REWA-108.feature
  core/integration/features/rewards/average_position_with_liquidation_reward.feature
  core/integration/features/rewards/realised_returns.feature
  core/integration/features/rewards/team-rewards.feature
  core/integration/features/teams/0083-RFPR-062.feature
  core/integration/features/teams/0083-RFPR-063.feature
  core/integration/features/verified/rewards-over-window.feature
  core/rewards/reward_distribution.go
Labels: no-changelog

#11195 chore: update arb bridge contract addresses
  core/netparams/bridge_mapping.go
Labels: no-changelog, no-issue

#11191 Add feature test for make relative return reward include losses
  core/integration/features/rewards/0056-REWA-111.feature
  core/integration/features/rewards/0056-REWA-116.feature
  core/integration/features/rewards/0056-REWA-117.feature
  core/integration/features/rewards/relative_return_rewards.feature
Labels: no-changelog

#11198 fix: when a newAsset proposal fail, properly reject the asset
  core/governance/engine.go
Labels: no-changelog, no-issue

#11202 feat: add a FT to replicate bug found in incentive
  core/execution/spot/market.go
  core/integration/features/spot/orders/0080-SPOT-024.feature
Labels: no-changelog, no-issue

#11204 feat: add tests to cover rewards from spot markets
  core/integration/features/rewards/spot-rewards.feature
  core/integration/steps/the_markets.go
Labels: feature tests, rewards, no-changelog, spot

#11199 fix: marshal newAsset proposal in batch term toProto
  core/types/governance_proposal_terms.go
Labels: no-changelog, no-issue

#11216 feat: add AC code for 0043-MKTL-012, 013
  core/integration/features/auctions/opening-auction-expiry.feature
  core/integration/features/spots/opening-auction-expires.feature
Labels: no-changelog
