Repository vegaprotocol/vega, pull requests merged in 2024-09, with the labels that each got.

#11639 fix: prevent overflow when calculating tradable volume outside of sid…
  core/execution/amm/pool.go
  core/execution/amm/pool_test.go
Labels: no-changelog, no-issue

#11640 Release version 0.78.1
  CHANGELOG.md
  core/evtforward/ethereum/engine.go
  core/execution/amm/engine.go
  core/execution/amm/pool.go
  core/execution/amm/pool_test.go
  core/execution/amm/shape.go
  core/execution/amm/shape_test.go
  core/integration/features/amm/0090-VAMM-auction.feature
  core/matching/orderbook.go
  core/matching/orderbook_amm_test.go
  core/matching/side.go
  core/matching/side_test.go
  libs/errors/errors.go
  libs/errors/errors_test.go
  protos/blockexplorer/api/v1/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/api/v1/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#11649 fix: add tier number to volume rebate resolver
  datanode/gateway/graphql/volume_rebate_program_resolver.go
Labels: no-changelog

#11653 fix: a selection of fixes to stablise AMM's during fuzz runs
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/amm/pool.go
  core/execution/amm/pool_test.go
  core/execution/amm/shape.go
  core/execution/future/market.go
  core/integration/features/amm/0090-VAMM-market-ticks.feature
Labels: no-changelog

#11657 fix: set the tier number in party stats tiers
  datanode/service/party_stats.go
Labels: no-changelog, no-issue

#11651 feat: add FT to check opening auction price
  core/integration/features/auctions/opening-auction-price.feature
Labels: no-issue

#11662 fix: remove reference to public from query
  datanode/sqlstore/volume_discount_stats.go
Labels: no-changelog, no-issue

#11664 fix: remove unneeded check for market length in GetPartyStats
  datanode/service/party_stats.go
Labels: no-changelog, no-issue

#11675 fix: check for empty tier slices and use int for slice indexes
  datanode/service/party_stats.go
Labels: no-changelog, no-issue

#11670 feat: set max program window lenghts to 200
  commands/errors.go
  commands/proposal_submission.go
  commands/proposal_submission_update_referral_program_test.go
  commands/proposal_submission_update_volume_discount_program_test.go
Labels: no-changelog, no-issue

#11677 fix: check for nil values before dereferencing
  datanode/service/party_stats.go
Labels: no-changelog, no-issue

#11678 Hvmr coverage
  commands/proposal_submission.go
  commands/proposal_submission_update_rebate_program_test.go
  core/governance/engine_update_referral_program_test.go
  core/integration/features/verified/finite-rewards.feature
  core/integration/features/verified/quick-test.feature
  core/integration/features/volume-rebate/0095-HVMR-cap.feature
  core/integration/features/volume-rebate/0095-HVMR-multiple.feature
  core/integration/features/volume-rebate/0095-HVMR.feature
  core/integration/main_test.go
  core/integration/steps/the_following_trades_happened.go
  core/integration/steps/volume_rebate_program.go
Labels: no-changelog, no-issue

#11689 fix: set max window length to 200
  core/referral/engine.go
  core/volumediscount/engine.go
  core/volumerebate/engine.go
Labels: no-changelog, no-issue

#11693 feat: add validation when loading tendermint pubkey
  cmd/vega/commands/nodewallet/import.go
Labels: no-changelog, no-issue

#11694 fix: add resolver for high volume maker fee
  datanode/gateway/graphql/resolvers.go
Labels: no-changelog

#11703 fix: include most recent candles in the API response
  datanode/candlesv2/candle_updates.go
Labels: no-changelog, no-issue

#11706 11705 datanode panics
  core/execution/amm/estimator.go
  core/execution/amm/estimator_test.go
  datanode/service/market_depth_amm.go
  datanode/service/market_depth_amm_test.go
Labels: no-changelog

#11712 fix: unmarshal referral prog discount factors properly when loading f…
  core/referral/engine.go
Labels: no-changelog, no-issue

#11719 fix: init pool cache in snapshot path, and write a snapshot test
  core/execution/amm/engine_test.go
  core/execution/amm/pool.go
Labels: no-changelog, no-issue
