Repository vegaprotocol/vega, pull requests merged in 2024-01, with the labels that each got.

#10292 Send event when party updates margin mode
  core/events/bus.go
  core/events/margin_mode.go
  core/execution/engine.go
  core/execution/engine_test.go
  core/execution/future/liquidity_provision.go
  core/execution/future/market.go
  core/integration/features/margin/0019-MCAL-100.feature
  core/integration/features/margin/0019-MCAL-105.feature
  core/integration/features/margin/0019-MCAL-107.feature
  core/integration/features/margin/0019-MCAL-128.feature
  core/integration/features/margin/0019-MCAL-150.feature
  datanode/broker/convert.go
  protos/sources/vega/events/v1/events.proto
  protos/vega/events/v1/events.pb.go
Labels: no-issue

#10256 chore: update migration versions given mainnet patches
  core/execution/future/market_snapshot.go
  core/execution/future/market_snapshot_test.go
  core/governance/snapshot.go
  core/products/perpetual_snapshot.go
  core/vesting/vesting_snapshot.go
  core/vesting/vesting_snapshot_test.go
Labels: no-changelog, no-issue

#10311 fix: set default values instead of running update for new margin columns
  datanode/sqlstore/migrations/0063_isolated_margin.sql
Labels: no-changelog, no-issue

#10313 fix: new columns did not provide a default value and allowed existing…
  datanode/sqlstore/migrations/0064_market_data_next_network_closeout.sql
Labels: datanode, no-changelog, no-issue

#10312 AC to cover loss socialisation of network account
  core/integration/features/closeouts/0012-POSR-010.feature
Labels: no-changelog

#10320 docs: add note to core state protos
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/corestate_grpc.pb.go
Labels: no-changelog

#10302 fix: raise disposal size
  core/execution/liquidation/engine.go
  core/execution/liquidation/engine_test.go
  core/integration/features/verified/network_position_disposal.feature
Labels: no-changelog, no-issue, liquidation

#10329 feat: add test for network profit and loss
  core/integration/features/verified/network_pnl.feature
  core/plugins/positions.go
Labels: feature tests, no-changelog, liquidation

#10344 Make sure the team's allow_list is set
  core/teams/engine.go
  core/teams/engine_test.go
  core/teams/helpers_for_test.go
  core/teams/snapshot.go
  core/teams/snapshot_test.go
Labels: no-changelog, no-issue

#10345 Implement future market settlement examples tests
  core/integration/features/verified/0002-STTL-settlement_future_example_paths.feature
Labels: no-changelog

#10353 chore: update snapshot migrations given mainnet patches
  core/execution/future/market_snapshot.go
  core/execution/future/market_snapshot_test.go
  core/governance/snapshot.go
  core/products/perpetual_snapshot.go
Labels: no-changelog, no-issue

#10357 feat: allow to pass downstream node label
  Jenkinsfile
Labels: no-changelog, no-issue

#10306 feat: Adding AC for network holding closed out position
  core/integration/features/closeouts/0012-POSR-009.feature
Labels: no-changelog

#10366 fix: slow migration in 0083
  datanode/sqlstore/migrations/0083_mark_price.sql
Labels: no-changelog, no-issue

#10368 chore: add protection and test for empty source weights
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  core/execution/future/market.go
Labels: no-changelog, no-issue

#10341 Adding AC for 0014-ORDT-130
  Makefile
  core/execution/common/errors.go
  core/execution/future/market.go
  core/integration/features/orders/stoporders.feature
  core/integration/steps/parties_place_the_following_orders.go
  core/types/stop_orders.go
  datanode/entities/enums.go
  datanode/gateway/graphql/schema.graphql
  datanode/networkhistory/service_test.go
  datanode/sqlstore/migrations/0085_stop_order_reject_reason_oco_expiry_times_much_not_be_the_same.sql
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog

#10371 test: ensure we wait for the end of the test if needed
  Jenkinsfile
  core/validators/witness_test.go
Labels: no-changelog, no-issue

#10384 fix: add missing entry in graphql account type
  datanode/gateway/graphql/schema.graphql
Labels: no-changelog, no-issue

#10385 fix: add method for update margin mode event
  core/events/margin_mode.go
Labels: no-changelog, no-issue

#10388 fix: avoid nil ptr panic
  datanode/entities/market.go
Labels: error handling, no-changelog, high, no-issue

#10379 0014-ORDT-131 AC
  core/execution/future/market.go
  core/execution/stoporders/stop_orders.go
  core/execution/stoporders/stop_orders_test.go
  core/integration/features/orders/stoporders.feature
Labels: no-changelog

#10390 fix: do not touch retention policies for non-data-node schemas
  CHANGELOG.md
  datanode/sqlstore/sqlstore.go
Labels: bug, no-issue

#10398 feat: set default chain ID
  core/execution/engine.go
  core/execution/engine_snapshot.go
  core/governance/engine.go
  core/governance/snapshot.go
  core/processor/abci.go
  core/processor/mocks/mocks.go
  core/processor/processor.go
  core/protocol/protocol.go
  core/snapshot/providers.go
  core/types/governance_new_market.go
  core/types/governance_update_market.go
Labels: oracles

#10391 chore: add oracle supports for composite price in feature tests
  core/execution/future/mark_price.go
  core/execution/future/market.go
  core/integration/features/mark-price/0009-MRKP-012.feature
  core/integration/main_test.go
  core/integration/steps/market/oracle_configs.go
  core/integration/steps/the_markets.go
  core/integration/steps/the_oracle_spec_for_composite_price.go
  core/products/composite_price_oracles.go
  core/types/governance_new_market.go
Labels: no-changelog, no-issue

#10404 Adding mark price algo check step
  core/integration/features/mark-price/0009-MRKP-010.feature
  core/integration/main_test.go
  core/integration/steps/the_mark_price_algo_for_a_market.go
  core/integration/stubs/broker_stub.go
Labels: no-changelog, no-issue

#10406 feat: improve validation of evm config netparam
  core/netparams/checks/checks.go
  core/netparams/defaults.go
  core/netparams/values.go
  core/netparams/values_test.go
  core/types/activity_streak_benefit_tiers.go
  core/types/ethereum.go
  core/types/ethereum_test.go
  core/types/vesting.go
  protos/sources/vega/chain_events.proto
  protos/sources/vega/data_source.proto
  protos/sources/vega/vega.proto
  protos/vega/chain_events.pb.go
  protos/vega/data_source.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#10405 chore: add AC code 0013-ACCT-033 to feature test
  core/integration/features/successor-markets-insurance.feature
Labels: no-changelog

#10365 feat: add tests to cover liquidation ACs
  core/integration/features/verified/network_disposing_position_outside_bounds.feature
  core/integration/features/verified/network_pnl.feature
  core/integration/features/verified/network_position_disposal.feature
  core/integration/steps/the_markets.go
Labels: feature tests, no-changelog, liquidation

#10408 feat: Adding AC for marginal cost
  commands/proposal_submission.go
  commands/proposal_submission_new_market_test.go
  core/integration/features/fees/0042-LIQF-fees_settings.feature
Labels: no-changelog

#10415 fix: add missing governance conversions for index price config
  core/governance/market.go
  core/types/governance_new_market.go
Labels: no-changelog, no-issue

#10424 fix: only confirm the chain-id if the client is set
  core/datasource/external/ethcall/engine.go
  core/protocol/all_services.go
  core/protocol/l2_eth_call_engines.go
Labels: no-changelog, no-issue

#10423 feat: add more tests for 002, 011 and 013
  core/integration/features/mark-price/0009-MRKP-001.feature
  core/integration/features/mark-price/0009-MRKP-010.feature
  core/integration/features/mark-price/0009-MRKP-012.feature
Labels: no-changelog

#10428 feat: add feature tests for mark price ACs
  core/integration/features/mark-price/0009-MRKP-022.feature
  core/integration/features/mark-price/0009-MRKP-026.feature
Labels: feature tests, no-changelog

#10433 fix: only set up config watching is evm clients have been initialised
  Jenkinsfile
  core/protocol/all_services.go
Labels: no-changelog, no-issue

#10440 Adding AC for correct order of funding calculation scaling and …
  core/integration/features/settlement/0053-PERP-040.feature
Labels: no-changelog

#10425 AC for 0053-PERP-039
  core/integration/features/settlement/0053-PERP-039.feature
Labels: no-changelog

#10443 fix: stop double polling evm-call-engines when starting from a snapshot
  core/datasource/external/ethcall/engine.go
  core/datasource/external/ethverifier/l2_verifier_snapshot.go
  core/protocol/l2_eth_call_engines.go
  libs/context/context.go
  libs/context/context_test.go
Labels: no-changelog

#10446 fix: list game return invalid games
  datanode/sqlstore/games.go
Labels: no-changelog, no-issue

#10447 chore: update cometbft to 0.38.3
  go.mod
  go.sum
Labels: no-changelog, no-issue

#10445 feat: Updated tests with AC tag
  commands/proposal_submission_new_market_test.go
Labels: no-changelog

#10450 feat: Adding coverage for attempting to submit wrong side stop orders
  core/integration/features/orders/stoporders.feature
Labels: no-changelog

#10452 feat: Testing rounding of fractional position override stop orders
  core/integration/features/orders/stoporders.feature
Labels: no-changelog

#10449 feat: add network funding test
  core/integration/features/verified/network_pnl_funding.feature
Labels: no-changelog

#10453 feat: Testing stop order rejection with 0% position size
  core/integration/features/orders/stoporders.feature
Labels: no-changelog

#10465 fix: AC tags for 0090-MKPR-022 and 0090-MKPR-023
  core/integration/features/mark-price/0009-MRKP-022.feature
Labels: no-changelog, no-issue

#10466 fix: AC tags for 0009-MKPR-022 and 0009-MKPR-023
  core/integration/features/mark-price/0009-MRKP-022.feature
Labels: no-changelog, no-issue

#10467 fix: incorrect AC codes
  core/integration/features/mark-price/0009-MRKP-022.feature
Labels: no-changelog, no-issue

#10463 chore: update cometbft version to v0.38.4
  go.mod
  go.sum
Labels: no-changelog, no-issue

#10455 Fix/10419 migrate old tx results
  CHANGELOG.md
  blockexplorer/blockexplorer.go
  blockexplorer/store/config.go
  blockexplorer/store/migrations/0005_add_block_height_to_tx_result.sql
  blockexplorer/store/migrator.go
  blockexplorer/store/migrator_test.go
  blockexplorer/store/store.go
  blockexplorer/store/transactions.go
  blockexplorer/store/transactions_test.go
  core/blockchain/abci/abci.go
Labels: no-changelog

#10473 fix: block explorer is missing an index on block height and index col…
  blockexplorer/store/migrations/0005_add_block_height_to_tx_result.sql
Labels: no-changelog, no-issue, block-explorer

#10476 chore: update unit tests to make sure the query works
  datanode/sqlstore/referral_sets_test.go
Labels: no-changelog, no-issue, not-a-bug

#10478 chore: add update_party_profile ac codes
  commands/update_party_profile_test.go
Labels: no-changelog

#10479 chore: update cometbft to 0.38.5
  go.mod
  go.sum
Labels: no-changelog, no-issue

#10485 Fix migration and Game ID for broken migration
  datanode/entities/transfer.go
  datanode/sqlstore/migrations/0080_batch_proposals.sql
Labels: no-changelog, no-issue

#10499 chore: prune old evt forward hashes
  core/evtforward/acked_events.go
  core/evtforward/config.go
  core/evtforward/forwarder.go
  core/evtforward/forwarder_test.go
  core/evtforward/snapshot.go
  core/types/snapshot_nodes.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog

#10494 fix: handle isolated margin amends properly and fix mishandled fees on failure
  CHANGELOG.md
  core/execution/future/market.go
  core/integration/features/margin/0019-MCAL-037.feature
  core/integration/features/margin/0019-MCAL-043.feature
  core/integration/features/margin/0019-MCAL-160.feature
  core/integration/features/margin/0019-MCAL-164.feature
  core/integration/features/margin/0019-MCAL-168.feature
  core/integration/features/margin/0019-MCAL-172.feature
  core/integration/features/margin/0019-MCAL-176.feature
  core/integration/features/margin/0019-MCAL-200.feature
  core/integration/features/margin/0019-MCAL-201.feature
  core/integration/features/margin/0019-MCAL-202.feature
  core/integration/features/margin/0019-MCAL-203.feature
  core/integration/features/margin/testnet_crash.feature
  core/integration/features/orders/amend-trade-panic.feature
  core/risk/isolated_margin.go
  core/risk/isolated_margin_test.go
Labels: no-changelog

#10509 fix: move transaction type one-of to the correct range
  protos/sources/vega/commands/v1/transaction.proto
  protos/vega/commands/v1/transaction.pb.go
Labels: no-changelog, no-issue

#10512 chore: fix docs categories for margins and transations results
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog, no-issue
