Repository vegaprotocol/vega, pull requests merged in 2024-08, with the labels that each got.

#11539 fix: order spam check for spot fixed
  CHANGELOG.md
  core/execution/spot/market.go
Labels: no-changelog, no-issue

#11550 fix: do not panic if commitment is super low in estimate-AMM bounds a…
  core/execution/amm/estimator.go
  core/execution/amm/estimator_test.go
Labels: no-changelog, no-issue

#11551 fix: empty-factor struct comparison does not work because decimal con…
  core/fee/engine.go
  core/types/referral_program.go
Labels: no-changelog, no-issue

#11554 test: coverage for edge cases with vAMM
  core/integration/features/amm/0090-VAMM-028.feature
  core/integration/features/amm/vamm-wash-trade.feature
  core/integration/main_test.go
  core/integration/steps/parties_place_the_following_orders.go
Labels: no-changelog, no-issue

#11559 chore: add doc string to rank table for lottery
  protos/sources/vega/vega.proto
  protos/vega/vega.pb.go
Labels: no-changelog, no-issue

#11552 refactor: cover some of the remaining vAMM ACs
  core/integration/features/amm/0090-VAMM-035.feature
  core/integration/features/rewards/0056-REWA-170.feature
Labels: no-changelog

#11538 feat: add FT for 0029 fee overhaul
  core/integration/features/fees/0029-FEES-high_volume_maker.feature
  core/integration/features/verified/0029-FEES-040.feature
  core/integration/features/verified/0029-FEES-fees.feature
  core/integration/main_test.go
Labels: no-changelog

#11557 feat: add FT for high volume maker rebate
  core/integration/features/fees/0029-FEES-high_volume_maker.feature
Labels: no-changelog, no-issue

#11566 chore: add AC for market depth expansion
  datanode/service/market_depth.go
  datanode/service/market_depth_amm_test.go
Labels: no-changelog

#11573 fix: add missing rebate program validation
  commands/proposal_submission.go
Labels: no-changelog, no-issue

#11574 fix: referral set stats API unmarshalls discount factors properly
  datanode/sqlstore/referral_sets.go
  datanode/sqlstore/referral_sets_test.go
Labels: no-changelog, no-issue

#11589 test: update test to include changes to protos
  datanode/sqlstore/referral_programs_test.go
  datanode/sqlstore/volume_discount_programs_test.go
Labels: no-changelog

#11581 fix: send empty factors for party that does no quality
  core/volumediscount/engine.go
  core/volumediscount/helpers_for_test.go
Labels: no-changelog, no-issue

#11565 chore: rename staking bridge events
  core/assets/erc20/erc20.go
  core/assets/erc20/erc20_test.go
  core/bridges/erc20_asset_pool.go
  core/bridges/erc20_asset_pool_test.go
  core/bridges/erc20_logic.go
  core/bridges/erc20_logic_test.go
  core/bridges/erc20_multisigcontrol.go
  core/bridges/erc20_multisigcontrol_test.go
  core/client/eth/client.go
  core/contracts/ERC20_Bridge_Logic_Restricted.abi
  core/contracts/MultisigControl.abi
  core/contracts/erc20_bridge_logic_restricted/erc20_bridge_logic_restricted.go
  core/contracts/multisig_control/multisig_control.go
  core/evtforward/ethereum/filterer.go
  core/netparams/values.go
  core/staking/staking_bridge_abi.go
  core/staking/staking_bridge_abi.json
  core/validators/signatures.go
Labels: no-changelog, no-issue

#11594 fix: actually set err so that the defer to cleanup after amend runs
  core/execution/future/market.go
Labels: no-changelog

#11591 feat: add HVMR feature tests
  core/integration/features/volume-rebate/0095-HVMR.feature
  core/integration/steps/the_following_trades_happened.go
Labels: no-changelog

#11597 chore: add lottery ACs
  core/integration/features/rewards/return_volatility_rewards.feature
  core/integration/steps/transfers.go
Labels: no-changelog

#11600 chore: add ACs for total fees
  core/integration/features/0084-VDPR-012.feature
  core/integration/steps/the_fees_configuration.go
  core/integration/steps/the_following_trades_happened.go
Labels: no-changelog

#11598 feat: add volume rebate factor cap feature tests
  core/integration/features/volume-rebate/0095-HVMR-cap.feature
Labels: feature tests, no-changelog

#11572 chore: set the default for buy back and treasury fee to 0
  core/netparams/defaults.go
Labels: no-changelog, no-issue

#11602 chore: add tag for PRAC-006
  core/integration/features/auctions/0094-PRAC-008.feature
Labels: no-changelog

#11603 test: add coverage for 0084-VDPR-018
  core/integration/features/0084-VDPR-018.feature
  core/integration/features/fees/0042-LIQF-fees_settings.feature
  core/integration/main_test.go
  core/integration/steps/volume_discount_program.go
Labels: no-changelog

#11605 fix: count sub-key ELS for the parent key when voting
  CHANGELOG.md
  core/execution/common/interfaces.go
  core/execution/engine.go
  core/execution/future/market.go
  core/execution/spot/market.go
Labels: no-issue

#11609 feat: add feature tests for vamm with SLA penalty
  core/integration/features/amm/0090-VAMM-092.feature
Labels: feature tests, no-changelog

#11604 feat: add ability to not create a referral set with CreateReferralSet and not join a team with ApplyReferralCode
  commands/create_referral_set.go
  core/processor/abci.go
  core/teams/engine.go
  datanode/sqlstore/teams.go
  protos/sources/vega/commands/v1/commands.proto
  protos/vega/commands/v1/commands.pb.go
Labels: no-changelog, no-issue

#11618 fix: prevent AMM's from being created outside of range on capped futu…
  core/execution/common/errors.go
  core/execution/future/market.go
  core/execution/future/market_test.go
Labels: no-changelog, no-issue

#11622 fix: buyer fees stored in the wrong order in the trade DB
  datanode/sqlstore/trades.go
Labels: no-changelog, no-issue

#11623 fix: populate treasury and buyback fee fields in trade API
  datanode/entities/trade.go
Labels: no-changelog, no-issue

#11631 fix: check for circular references
  libs/errors/errors.go
  libs/errors/errors_test.go
Labels: no-changelog, no-issue
