Repository vegaprotocol/vega, pull requests merged in 2024-05, with the labels that each got.

#11220 feat: add checking on asset releasing
  core/integration/features/auctions/opening-auction-expiry.feature
  core/integration/features/spots/opening-auction-expires.feature
Labels: no-changelog, no-issue

#11238 fix: serliase stop orders into spot market
  core/execution/spot/market_snapshot.go
Labels: no-changelog

#11245 fix: typos expiringOrders -> expiringStopOrders
  core/types/snapshot_nodes.go
Labels: no-changelog

#11256 Release/v0.76.1
  CHANGELOG.md
  core/execution/future/market.go
  core/types/snapshot_nodes.go
  datanode/gateway/graphql/new_transfer_resolver.go
  protos/blockexplorer/api/v1/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/api/v1/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#11275 fix: add cache map to order sqlsubscriber
  datanode/sqlsubscribers/order.go
Labels: no-changelog, no-issue

#11214 chore: update cometbft version to the last 38.7 patch
  go.mod
  go.sum
Labels: no-changelog, no-issue

#11278 chore: add validators testnet bridge mapping
  core/netparams/bridge_mapping.go
Labels: no-changelog, no-issue

#11284 fix: do not account for started block in the past block range
  core/pow/engine.go
  core/pow/engine_test.go
Labels: no-changelog, no-issue

#11287 chore: remove old rate limit from processor
  core/processor/abci.go
  core/processor/config.go
  core/processor/ratelimit/config.go
  core/processor/ratelimit/ratelimit.go
  core/processor/ratelimit/ratelimit_test.go
Labels: no-changelog, no-issue

#11295 fix: volume change for price calcs is signed based on buy or sell
  core/execution/amm/engine_test.go
  core/execution/amm/pool.go
  core/execution/amm/pool_test.go
  core/integration/features/amm/0090-VAMM-006-014.feature
  core/integration/features/amm/0090-VAMM-020.feature
  core/integration/features/amm/0090-VAMM-021.feature
  core/integration/features/amm/0090-VAMM-028.feature
  core/integration/features/amm/0090-VAMM-rebase.feature
Labels: no-changelog, no-issue

#11302 fix: positions stream should still filter on party when it has no der…
  datanode/api/trading_data_v2.go
Labels: no-changelog

#11303 feat: add test for AC 163 stop order in spot market
  core/integration/features/spot/orders/0014-ORDT-163.feature
Labels: feature tests, no-changelog, no-issue

#11310 fix: handle invalid offset for pegged on market update when tick size…
  core/execution/future/market.go
  core/execution/spot/market.go
Labels: no-changelog, no-issue

#11309 fix: save AMM's proposed fee into snapshot
  core/execution/amm/pool.go
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog

#11311 fix: typos in snapshot serialisation between AMM upper and lower curv…
  core/execution/amm/pool.go
Labels: no-changelog

#11315 fix: restore votes on batch proposals undergoing node-validation when…
  core/governance/node_validation.go
Labels: no-changelog

#11317 binary settlement tests (oracles + governance)
  core/integration/features/capped-futures/0016-PFUT-020-ignore.feature
  core/integration/steps/the_market_state_should_be_for_market.go
Labels: no-changelog, no-issue

#11292 feat: add test for 0016-PFUT-026, check margin for hard coded risk model
  core/integration/features/margin/0016-PFUT-026.feature
Labels: feature tests, no-changelog, no-issue

#11324 Fix governance engine
  core/execution/common/interfaces.go
  core/execution/engine.go
  core/execution/future/market.go
  core/execution/spot/market.go
  core/governance/engine.go
  core/governance/engine_update_market_state_test.go
  core/governance/market.go
  core/governance/mocks/mocks.go
  core/integration/features/capped-futures/0016-PFUT-022-max.feature
Labels: no-changelog, no-issue

#11333 fix: orderbook shape can create zero volume steps if we step tolerant…
  core/execution/amm/pool.go
  core/execution/amm/pool_test.go
Labels: no-changelog

#11332 fix: delay setting ipv cache until position engine is loaded
  core/execution/common/amm_score_stake.go
  core/execution/common/liquidity_provision_snapshot_test.go
  core/matching/cached_orderbook.go
  core/matching/snapshot.go
Labels: no-changelog

#11322 archive integration test report for failures only
  Jenkinsfile
Labels: no-changelog, no-issue

#11335 feat: factor returns by asset decimals to lower the values
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
Labels: no-changelog, no-issue
