Repository vegaprotocol/vega, pull requests merged in 2024-03, with the labels that each got.

#10678 feat: add feature test for spot SLA 045
  core/integration/features/spot/liquidity_provision/0044-LIME-045.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-046.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-047.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-048.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-056.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-064.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-078.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-080.feature
Labels: no-changelog

#10777 More iceberg feature tests
  core/integration/features/spot/orders/0014-ORDT-091.feature
  core/integration/features/spot/orders/0014-ORDT-092.feature
  core/integration/features/spot/orders/0014-ORDT-093.feature
  core/integration/features/spot/orders/0014-ORDT-094.feature
Labels: no-changelog

#10791 feat: stop distressed pools, and only cancel reducing pools after MTM
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/amm/pool.go
  core/execution/future/market.go
Labels: no-changelog, no-issue

#10813 chore: check for nil pointer
  core/datasource/external/ethverifier/l2_verifier_snapshot.go
Labels: no-changelog, no-issue

#10817 chore: backport changes from 74.9 tag
  core/datasource/external/ethverifier/l2_verifier_snapshot.go
Labels: no-changelog, no-issue

#10801 fix: unit test for using correct markets when filtering party taker fees paid in epoch
  core/execution/common/market_activity_tracker_test.go
Labels: no-changelog, no-issue

#10808 feat: Adding ACs for tick size/spot
  core/integration/features/spot/orders/0025-OCRE-006.feature
  core/integration/features/tick_size/0004-AMND-060.feature
Labels: no-changelog

#10824 Add individual AMM scope for rewards
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/common/interfaces.go
  core/execution/common/market_activity_tracker.go
  core/execution/common/market_activity_tracker_snapshot.go
  core/execution/common/market_activity_tracker_test.go
  core/execution/common/mocks_amm/mocks.go
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
  core/integration/steps/transfers.go
  datanode/gateway/graphql/schema.graphql
  protos/sources/vega/checkpoint/v1/checkpoint.proto
  protos/sources/vega/vega.proto
  protos/vega/checkpoint/v1/checkpoint.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog

#10794 feat: stop all AMM's and release balances when market is closed
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/future/market.go
Labels: no-changelog, no-issue

#10830 Small fix for AC 022 behaviour
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/integration/features/amm/0087-VAMM-022.feature
Labels: no-changelog, no-issue

#10822 feat: create feature tests for spot market 0024
  core/integration/features/spot/orders/0024-OSTA-030.feature
  core/integration/features/spot/orders/0024-OSTA-033.feature
Labels: no-changelog

#10836 feat: add ft for 0024 034 wash trade in spot
  core/integration/features/spot/orders/0024-OSTA-034.feature
Labels: no-changelog

#10835 fix: sort amm states before submitting their ELS stake
  core/execution/amm/engine.go
  core/execution/common/liquidity_provision.go
Labels: no-changelog, no-issue

#10659 feat: add test to cover amending order during auction in isolated margin
  core/execution/future/market.go
  core/integration/features/margin/0019-MCAL-206.feature
Labels: feature tests, no-changelog, no-issue

#10834 Iceberg feature tests
  core/integration/features/spot/orders/0014-ORDT-104.feature
  core/integration/features/spot/orders/0014-ORDT-105.feature
  core/integration/features/spot/orders/0014-ORDT-106.feature
  core/integration/features/spot/orders/0014-ORDT-107.feature
  core/integration/features/spot/orders/0014-ORDT-108.feature
  core/integration/features/spot/orders/0014-ORDT-109.feature
  core/integration/features/spot/orders/0014-ORDT-110.feature
Labels: no-changelog

#10833 test: add coverage for AC 023
  core/collateral/engine.go
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/amm/mocks/mocks.go
  core/execution/amm/pool.go
  core/execution/common/interfaces.go
  core/execution/common/mocks/mocks.go
  core/integration/features/amm/0087-VAMM-006-014.feature
  core/integration/features/amm/0087-VAMM-020.feature
  core/integration/features/amm/0087-VAMM-021.feature
  core/integration/features/amm/0087-VAMM-023.feature
  core/integration/features/amm/0087-VAMM-024-026.feature
  core/integration/features/amm/0087-VAMM-031.feature
  core/integration/features/amm/0087-VAMM-032.feature
  core/types/amm.go
Labels: no-changelog

#10848 feat: add feature test for 0009 034 and 035 mark price using median method
  core/integration/features/mark-price/0009-MRKP-034.feature
Labels: no-changelog

#10857 feat: add feature test for AC 0009036 and 0032040
  core/integration/features/mark-price/0009-MRKP-036.feature
  core/integration/features/mark-price/0032-PRIM-040.feature
Labels: no-changelog

#10844 More iceberg spot market tests
  core/integration/features/spot/orders/0014-ORDT-111.feature
  core/integration/features/spot/orders/0014-ORDT-112.feature
  core/integration/features/spot/orders/0014-ORDT-113.feature
  core/integration/features/spot/orders/0014-ORDT-118.feature
Labels: no-changelog

#10861 fix: ensure we hit leave auction trigger on mark-price calc, and hand…
  core/execution/common/mark_price.go
  core/execution/future/market.go
  core/integration/features/perpetual.feature
  core/integration/features/price-mon-trigger-leaving-auction.feature
  core/products/perpetual.go
  core/products/perpetual_auctions_test.go
Labels: no-changelog

#10839 feat: create a ft for isolated margin rf greater than 1
  core/integration/features/margin/0019-MCAL-208.feature
  core/integration/steps/the_parties_update_margin_mode.go
Labels: no-changelog

#10704 test: add feature test reproduce existing markets and check price monitoring bounds
  core/integration/features/price_monitoring/BTC_USDT-perp-bounds.feature
  core/integration/features/price_monitoring/ETH_USDT-perp-bounds.feature
  core/integration/features/price_monitoring/INJ_USDT-perp-bounds.feature
  core/integration/features/price_monitoring/LDO_USDT-perp-bounds.feature
  core/integration/features/price_monitoring/SNX_USDT-perp-bounds.feature
Labels: no-changelog, no-issue

#10723 chore: backport future changes to spot
  core/execution/spot/auction.go
  core/execution/spot/market.go
Labels: no-changelog, no-issue, spot

#10874 feat: add FT for spot orders
  core/integration/features/spot/orders/0024-OSTA-040.feature
Labels: no-changelog

#10897 fix: tw notional pos store not initialised
  cmd/data-node/commands/start/sqlsubscribers.go
Labels: datanode, no-changelog, no-issue

#10887 chore: improve doc-strings for add/remove signer sig-bundle API
  datanode/gateway/graphql/schema.graphql
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog, no-issue, bridges

#10867 Auction spot market testing
  core/integration/features/spot/orders/0026-AUCT-024.feature
  core/integration/features/spot/orders/0026-AUCT-029.feature
  core/integration/features/spot/orders/0026-AUCT-031.feature
  core/integration/features/spot/orders/0026-AUCT-032.feature
  core/integration/features/spot/orders/0032-PRIM-023.feature
  core/integration/features/spot/orders/0032-PRIM-024.feature
  core/integration/features/spot/orders/0032-PRIM-025.feature
  core/integration/features/spot/orders/0032-PRIM-027.feature
  core/integration/features/spot/orders/0032-PRIM-028.feature
  core/integration/features/spots/0080-SPOT-010.feature
Labels: no-changelog, spot

#10899 feat: add FT for 0034-008
  core/integration/features/fees/setting-fee-and-rewarding-lps.feature
  core/integration/features/spot/liquidity_provision/0034-PROB-008.feature
  core/integration/features/verified/Issue-6004-ProbOfTrading_Refactoring.feature
Labels: no-changelog

#10906 More price monitoring feature tests
  core/execution/spot/holding_account_tracker.go
  core/execution/spot/market.go
  core/integration/features/spot/orders/0032-PRIM-037.feature
  core/integration/features/spot/orders/0032-PRIM-038.feature
  core/integration/features/spot/orders/0068-MATC-080.feature
Labels: no-changelog

#10922 0068 080
  core/integration/features/spot/liquidity_provision/0044-LIME-078.feature
  core/integration/features/spot/orders/0068-MATC-080.feature
Labels: no-changelog

#10923 feat: add calculation for margin level
  core/integration/features/margin/0019-MCAL-070.feature
Labels: no-changelog, no-issue

#10934 feat: add test for 0068-067
  core/integration/features/spot/orders/0068-MATC-068.feature
Labels: no-changelog

#10929 Adding tests for MATC acceptance criteria
  core/integration/features/spot/orders/0068-MATC-073.feature
  core/integration/features/spot/orders/0068-MATC-074.feature
  core/integration/features/spot/orders/0068-MATC-075.feature
  core/integration/features/spot/orders/0068-MATC-076.feature
Labels: no-changelog

#10935 chore: update develop version to v0.76.x-dev
  CHANGELOG.md
  protos/blockexplorer/api/v1/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/api/v1/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-issue

#10938 feat: add FT for 0068-072
  core/integration/features/spot/orders/0011-MARA-continuous.feature
Labels: no-changelog

#10925 test: check PM partial trades
  core/integration/features/price_monitoring/price-monitoring-lognormal.feature
  core/integration/steps/parties_should_have_the_following_profit_and_loss.go
Labels: no-changelog, no-issue

#10948 chore: allow simple risk model for spots
  core/governance/market.go
Labels: no-changelog, no-issue, spot

#10942 Adding feature test for 0068-MATC
  core/integration/features/spot/orders/0068-MATC-077.feature
  core/integration/features/spot/orders/0068-MATC-078.feature
  core/integration/features/spot/orders/0068-MATC-079.feature
Labels: no-changelog

#10940 feat: add FT for spot market SLA
  core/integration/features/spot/liquidity_provision/0044-LIME-043.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-044.feature
  core/integration/features/spot/liquidity_provision/0044-LIME-054.feature
Labels: no-changelog

#10964 Batch order feature tests
  core/integration/features/spot/orders/0074-BTCH-015.feature
  core/integration/features/spot/orders/0074-BTCH-016.feature
  core/integration/main_test.go
  core/integration/steps/parties_place_the_following_orders.go
Labels: no-changelog

#10981 chore: remove unneeded workaround for auction
  core/monitor/auction.go
Labels: no-changelog

#10986 fix: GetOrdersPerParty sorts before returning as a slice
  core/matching/orderbook.go
Labels: no-changelog

#10992 chore: add test for 0083-RFPR-068
  core/integration/features/rewards/0083-RFPR-068.feature
  core/integration/setup_test.go
Labels: no-changelog

#10991 Adding code for amends and cancels testing in batches
  core/integration/execution_test.go
  core/integration/features/spot/orders/0074-BTCH-012.feature
  core/integration/features/spot/orders/0074-BTCH-019.feature
  core/integration/main_test.go
  core/integration/steps/execution.go
  core/integration/steps/parties_place_the_following_orders.go
Labels: no-changelog

#10967 feat: add FT for spot market decimal places
  core/integration/features/spot/accounts_and_fees/0070-MKTD-011.feature
Labels: no-changelog

#10994 feat: rewards.team.minEpochsInTeam can now be set to 0
  CHANGELOG.md
  core/integration/features/rewards/0083-RFPR-068.feature
  core/netparams/defaults.go
Labels: no-issue

#10993 chore: add clarification to docs
  datanode/gateway/graphql/schema.graphql
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/data-node/api/v2/trading_data.proto
Labels: no-changelog

#11022 Pricemon snapshot fix
  core/monitor/price/snapshot.go
  core/monitor/price/snapshot_test.go
Labels: no-changelog, no-issue
