Repository vegaprotocol/vega, pull requests merged in 2024-02, with the labels that each got.

#10536 fix: serialise funding rate upper bound properly
  core/types/governance_update_market.go
Labels: no-changelog

#10528 Mcal extra coverage
  core/execution/future/market.go
  core/integration/features/margin/0019-MCAL-037.feature
  core/integration/features/margin/0019-MCAL-168.feature
  core/integration/features/margin/0019-MCAL-200.feature
  core/integration/features/margin/0019-MCAL-204.feature
  core/integration/features/margin/testnet_crash.feature
  core/integration/features/orders/amend-trade-panic.feature
  core/matching/orderbook.go
  core/matching/orderbook_test.go
  core/matching/pricelevel.go
  core/matching/side.go
  core/matching/side_test.go
Labels: no-changelog, no-issue

#10548 chore: update snapshot migration version given upcoming mainnet patch
  core/evtforward/forwarder_test.go
  core/evtforward/snapshot.go
  core/execution/engine_snapshot.go
  core/execution/future/market_snapshot.go
  core/execution/future/market_snapshot_test.go
  core/governance/snapshot.go
  core/products/perpetual_snapshot.go
Labels: no-changelog, no-issue

#10547 feat: restrict max number of proposal in a batch proposal to at most 250
  commands/batch_proposal_submission.go
  commands/errors.go
Labels: no-changelog, no-issue

#10572 fix: rename net param appropriately for spam create/update referral s…
  core/netparams/defaults.go
  core/netparams/keys.go
  core/processor/abci.go
  core/protocol/all_services.go
  core/referral/engine.go
Labels: no-changelog, no-issue

#10579 Better reward filtering on teams stats SQL procedure
  datanode/sqlstore/migrations/0076_teams_stats.sql
  datanode/sqlstore/teams_test.go
Labels: no-changelog, no-issue

#10580 feat: implement order matching for hybrid AMM and CLOB
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/amm/pool.go
  core/execution/amm/pool_test.go
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
  core/execution/spot/market.go
  core/matching/cached_orderbook.go
  core/matching/helpers_test.go
  core/matching/mocks/mocks.go
  core/matching/orderbook.go
  core/matching/orderbook_amm_test.go
  core/matching/orderbook_test.go
  core/matching/side.go
  core/matching/side_test.go
  core/positions/engine.go
  core/types/matching.go
  protos/sources/vega/commands/v1/transaction.proto
  protos/sources/vega/events/v1/events.proto
  protos/sources/vega/snapshot/v1/snapshot.proto
Labels: no-changelog

#10590 fix: set market type properly in liquidity engine for spot code path
  core/execution/spot/market_snapshot.go
Labels: no-changelog, no-issue

#10591 backport mainnet fixes
  core/execution/common/market_activity_tracker.go
Labels: no-changelog, no-issue

#10598 fix: set default mark price config for spot so it doesn't fall over i…
  core/governance/market.go
Labels: bug, no-changelog, no-issue, spot

#10603 fix: mark price config from last trade to weighted fix for nil reference
  core/execution/future/mark_price.go
  core/execution/future/market.go
Labels: no-changelog, no-issue

#10614 feat: handle market position factor
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/amm/pool.go
  core/execution/amm/pool_test.go
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
Labels: no-changelog, no-issue

#10615 fix: wire oracle scaling function in update of internal composite price
  core/execution/future/market.go
Labels: bug, no-changelog, no-issue

#10640 chore: move mark price to common - no functional change
  core/execution/common/mark_price.go
  core/execution/common/mark_price_snapshot_test.go
  core/execution/common/mark_price_utils.go
  core/execution/common/mark_price_utils_test.go
  core/execution/future/market.go
  core/execution/future/market_snapshot.go
  core/products/perpetual.go
  core/products/perpetual_snapshot.go
  core/products/products.go
  core/products/products_snapshot.go
Labels: no-changelog, no-issue

#10642 fix: resend eth-oracle activations after snapshot restore
  core/broker/broker.go
  core/broker/broker_test.go
  core/broker/mocks/broker_mock.go
  core/datasource/spec/engine.go
  core/events/bus.go
  core/events/bus_test.go
  core/integration/stubs/broker_stub.go
  core/protocol/all_services.go
  datanode/broker/broker_test.go
Labels: no-changelog, no-issue

#10646 fix: always leave liquidity auction straightaway after upgrade
  CHANGELOG.md
  core/execution/future/auction.go
Labels: bug, no-changelog

#10637 feat: Adding feature test for 0080-spot-020
  core/integration/features/spots/SpotFunctionalTests/0080-SPOT-020.feature
Labels: no-changelog

#10645 feat: amm cancellation
  commands/cancel_amm.go
  commands/cancel_amm_test.go
  core/collateral/engine.go
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/amm/mocks/mocks.go
  core/execution/amm/pool.go
  core/execution/common/interfaces.go
  core/execution/common/mocks/mocks.go
  core/execution/engine.go
  core/execution/future/market.go
  core/execution/spot/market.go
  core/matching/side.go
  core/processor/abci.go
  core/processor/mocks/mocks.go
  core/processor/processor.go
  core/types/amm.go
  core/types/transfer.go
  protos/sources/vega/commands/v1/commands.proto
  protos/sources/vega/events/v1/events.proto
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/sources/vega/vega.proto
  protos/vega/commands/v1/commands.pb.go
  protos/vega/events/v1/events.pb.go
  protos/vega/snapshot/v1/snapshot.pb.go
  protos/vega/vega.pb.go
Labels: no-changelog

#10680 refactor: fix an error in logic for perps margin calculation
  core/risk/engine_test.go
  core/risk/margins_calculation.go
Labels: no-changelog, no-issue

#10682 Estimate margin decrease too
  datanode/api/trading_data_v2.go
  datanode/api/trading_data_v2_test.go
Labels: no-changelog, no-issue

#10694 chore: reproduce iceberg panic with a small unit test
  core/matching/orderbook_iceberg_uncrossing_test.go
  core/matching/side.go
Labels: no-changelog, no-issue

#10706 Fixes amm
  core/collateral/engine.go
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/amm/mocks/mocks.go
  core/execution/common/interfaces.go
  core/execution/common/mocks/mocks.go
  core/execution/engine.go
  core/execution/future/market.go
  core/execution/spot/market.go
  core/processor/abci.go
  core/processor/mocks/mocks.go
  core/processor/processor.go
Labels: no-changelog, no-issue

#10709 fix: when suspending market via governance, use second for monitoring auction extension
  core/execution/future/market.go
Labels: no-changelog, no-issue

#10711 fix: use seconds unit for auction extension for governance and return…
  CHANGELOG.md
  core/execution/future/auction.go
  core/execution/spot/auction.go
  core/execution/spot/market.go
Labels: no-changelog, no-issue

#10713 fix: call .EnsureChainID when parameters updates
  core/protocol/l2_eth_call_engines.go
Labels: no-changelog, no-issue

#10663 Adding AC for 0080-SPOT-021
  core/execution/spot/holding_account_tracker.go
  core/execution/spot/market.go
  core/integration/features/spots/SpotFunctionalTests/0080-SPOT-021.feature
Labels: no-changelog

#10671 Adding-ac-for-0008-trad-003
  core/integration/features/mark-price/0008-TRAD-008.feature
Labels: no-changelog

#10731 Double entry book keeping test to make sure we don't lose assets
  core/integration/features/spot/accounts_and_fees/0013-ACCT-024.feature
Labels: no-changelog, no-issue

#10728 FT to check that only 2 holding accounts are created per user
  core/integration/features/spot/accounts_and_fees/0013-ACCT-031.feature
Labels: no-changelog

#10732 fix: FOK market orders now work when trading against an AMM
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/matching/orderbook_amm_test.go
  core/matching/side.go
Labels: no-changelog

#10738 feat: handle on-sided-curves and allow trades to flip an amm's position
  commands/submit_amm.go
  commands/submit_amm_test.go
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/execution/amm/pool.go
  core/execution/amm/pool_test.go
  core/execution/common/interfaces.go
  core/execution/common/liquidity_provision_test.go
  core/execution/common/mocks_amm/mocks.go
  core/integration/features/amm/0087-VAMM-005.feature
  core/types/amm.go
  protos/sources/vega/commands/v1/commands.proto
  protos/sources/vega/snapshot/v1/snapshot.proto
  protos/vega/commands/v1/commands.pb.go
  protos/vega/snapshot/v1/snapshot.pb.go
Labels: no-changelog, no-issue

#10736 AC for testing passive orders obey the price level ordering
  core/integration/features/spot/orders/0014-ORDT-081.feature
  core/integration/features/spot/orders/0014-ORDT-082.feature
  core/integration/features/spot/orders/0014-ORDT-083.feature
  core/integration/features/spot/orders/0014-ORDT-084.feature
  core/integration/features/spot/orders/0014-ORDT-085.feature
  core/integration/features/spot/orders/0014-ORDT-086.feature
  core/integration/steps/parties_place_the_following_orders.go
Labels: no-changelog

#10741 fix: stop matching when fake-uncrossing if filled, add missing enum t…
  core/matching/side.go
  datanode/sqlstore/migrations/0094_amm_pools.sql
Labels: no-changelog, no-issue

#10757 chore: reduce the amount of event hash saved in evt forwarder
  cmd/vega/commands/node.go
  core/config/watcher.go
  core/evtforward/config.go
Labels: no-changelog, no-issue

#10715 chore: set version to 0.75.0-dev and remove some 74.3 specific migration
  core/datasource/spec/engine.go
  core/evtforward/forwarder_test.go
  core/evtforward/snapshot.go
  core/execution/engine_snapshot.go
  core/execution/future/market_snapshot.go
  core/execution/future/market_snapshot_test.go
  core/governance/snapshot.go
  core/products/perpetual_snapshot.go
  protos/blockexplorer/api/v1/blockexplorer.pb.go
  protos/data-node/api/v2/trading_data.pb.go
  protos/sources/blockexplorer/api/v1/blockexplorer.proto
  protos/sources/data-node/api/v2/trading_data.proto
  protos/sources/vega/api/v1/core.proto
  protos/sources/vega/api/v1/corestate.proto
  protos/vega/api/v1/core.pb.go
  protos/vega/api/v1/corestate.pb.go
  version/version.go
Labels: no-changelog, no-issue

#10761 feat: feat: include AMM's in best bid/ask queries on orderbook
  core/execution/amm/engine.go
  core/execution/amm/engine_test.go
  core/matching/mocks/mocks.go
  core/matching/orderbook.go
  core/matching/orderbook_amm_test.go
Labels: no-changelog, no-issue

#10765 fix: reinitialise external TWAP when we leave opening auction so we p…
  core/products/perpetual.go
  core/products/perpetual_test.go
Labels: no-changelog

#10687 fix: Update snapshot debug instructions
  core/snapshot/README.md
Labels: no-changelog, no-issue

#10775 feat: update feature test for closeout trades and auctions 0012-POSR-030
  core/integration/features/verified/network_disposing_position_outside_bounds.feature
Labels: no-changelog
